### ISSUE TITLE
Problem with Prefix and Offline RDF generation

### ISSUE THREAD

**Issue by Nadzy** [usc-isi-i2/Web-Karma#143]
Hi,
working with Karma v2.023, I've noticed that by making my online model and exporting triples through the interface, I get a different result than using the corrispondant published R2RML model, with the Offline generator. Here's an example:

Through Karma Web:
<http://www.disit.org/km4city/resource/Abetone1405339154000> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.disit.org/km4city/schema#WeatherReport> .
<http://www.disit.org/km4city/resource/Abetone14053391540001giorno> <http://www.disit.org/km4city/schema#uv> "4"^^<http://www.w3.org/2001/XMLSchema#integer> .

Through Offline Generator:
<Abetone1405339154000> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.disit.org/km4city/schema#WeatherReport> .
<Abetone14053391540001giorno> <http://www.disit.org/km4city/schema#uv> "4"^^<http://www.w3.org/2001/XMLSchema#integer> .

As you can see, the subject profix is missing for RDF triples generated Offline...
can anyone tell me why this happens?

thank you so much! :)

**Comment by dkapoor** [comment]
This should be fixed.
