### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by davidyoung3313** [usc-isi-i2/Web-Karma#148]
I'm running into an issue compiling web-mr due to a connection time out at http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/

Here's a clip of the error log, but I can post the full thing if needed. Is the site just down temporarily?

[INFO] karma-mr ........................................... FAILURE [ 31.701 s]
[INFO] karma-storm ........................................ SKIPPED
[INFO] karma-web-services ................................. SKIPPED
[INFO] web-services-rdf ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:21 min
[INFO] Finished at: 2014-11-08T09:17:49-05:00
[INFO] Final Memory: 64M/491M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project karma-mr: Could not resolve dependencies for project edu.isi:karma-mr:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at edu.isi.karma.services:entityExtraction:jar:0.0.1: Failed to read artifact descriptor for edu.isi.karma.services:entityExtraction:jar:0.0.1: Could not transfer artifact edu.isi.karma.services:entityExtraction:pom:0.0.1 from/to colo-vm41 (http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/): Connect to colo-vm41.isi.edu:8081 [colo-vm41.isi.edu/128.9.144.168] failed: Connection timed out: connect -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :karma-mr

**Comment by syxxzonz** [comment]
It seems that the server is down again.  I'm running into the same issue.  Can you look into this?  Or is there an update to the pom to include a more reliable server?

**Comment by muzavan** [comment]
I experienced same issue. Is it the server again?

**Comment by dkapoor** [comment]
The server is up. Can you try building again.

**Comment by muzavan** [comment]
@dkapoor thanks! Finally it succeed.

**Comment by mknavin** [comment]
Same issue. Seems that the server is down again. Can u pl bring it up

**Comment by dkapoor** [comment]
We apologize for that. I just checked and the server it up. Can you try
again.
Thanks.

**Comment by veuncent** [comment]
Is the server down again? I'm getting this error on the master branch while doing: mvn clean install

```
[ERROR] Failed to execute goal on project karma-web: Could not resolve dependencies for project edu.isi:karma-web:war:0.0.1-SNAPSHOT: Failed to collect depend
encies at edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Failed to read artifact descriptor for edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Could not transfer artifact
 edu.isi:karma-common:pom:0.0.1-SNAPSHOT from/to colo-vm41 (http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/): Connect to colo-vm41.isi.ed
u:8081 [colo-vm41.isi.edu/128.9.144.168] failed: Connection refused -> [Help 1]
```




Also, when trying the same mvn command with tag 2.051 I get this error:

`[ERROR] Failed to execute goal on project karma-web: Could not resolve dependencies for project edu.isi:karma-web:war:0.0.1-SNAPSHOT: Failed to collect dependencies at edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Failed to read artifact descriptor for edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Could not transfer artifact edu.isi:karma-common:pom:0.0.1-SNAPSHOT from/to KarmaRepo (http://repo.karma.isi.edu/artifactory/libs-release-local): Failed to transfer file: http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]`

**Comment by dkapoor** [comment]
The server is up. karma-common is actually not from the repository, but is built when you run `mvn clean install`. Can you make sure that you are not in any of the sub-folders of karma, but in the root Web-Karma folder and try `mvn clean install` again. 
Thanks.

**Comment by veuncent** [comment]
Thanks for the quick answer. I can confirm that I was running it from the root folder.
I am running it in a Docker container:

RUN git clone https://github.com/usc-isi-i2/Web-Karma.git
RUN cd Web-Karma &&\
	git checkout tags/v2.051 &&\
        mvn -e -X clean install


Also tried tag 2.049, same error

**Comment by veuncent** [comment]
Running that install command on the master branch now completes successfully, but then when i run `mvn jitty:run` I get the same error as with the tags:

```
[ERROR] Failed to execute goal on project karma-web: Could not resolve dependencies for project edu.isi:karma-web:war:0.0.1-SNAPSHOT: Failed to collect dependencies at edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Failed to read artifact descriptor for edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Could not transfer artifact edu.isi:karma-common:pom:0.0.1-SNAPSHOT from/to KarmaRepo (http://repo.karma.isi.edu/artifactory/libs-release-local): Failed to transfer file: http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]
```

**Comment by ChowRaj** [comment]
Hi, http://repo.karma.isi.edu/artifactory/libs-release-local is not working, I am getting connection refused error while building from maven. 

Can you please help
