### ISSUE TITLE
RDF generation issue.

### ISSUE THREAD

**Issue by ithkiam** [usc-isi-i2/Web-Karma#149]
Sorry if this is a replicated request. I am using ver.2.032 to model people.csv with vivo-isf ontology, and publish PDF. The Preloaded Ontology files include: VIVO-ISF, ref-schema, one VIVO-Ontology  extension file (additional classes and properties for VIVO).

The below is what I got. I have tried both master and development branches, The results are same.Thanks in advance to help me out.

(This is the one individual, the others are same.)
_:vivo_FacultyMember1_da39a3ee5e6b4b0d3255bfef95601890afd80709_N16_723954f9a9d06939b353c275793cae25fc84142e_N15_3801ff8dcedb0de739a3e046eb1a0dd0f708fbed_N18_81b3bdf355fe0ead809aea1553cfd2577ff9de25_N17_2e132849e08f1985e527da711db8f2916e1af897_N14_7172ca691e578058d8982816b652e5ee77ec076f_N21_864c165155eb3f7643a9fb270fec2da7b2fdd839_N20_c448eedb05c2055f623323e190032a2515d7915f_N22 <http://www.w3.org/2000/01/rdf-schema#label> "Burks, Rosella " .
_:vivo_FacultyMember1_da39a3ee5e6b4b0d3255bfef95601890afd80709_N16_723954f9a9d06939b353c275793cae25fc84142e_N15_3801ff8dcedb0de739a3e046eb1a0dd0f708fbed_N18_81b3bdf355fe0ead809aea1553cfd2577ff9de25_N17_2e132849e08f1985e527da711db8f2916e1af897_N14_7172ca691e578058d8982816b652e5ee77ec076f_N21_864c165155eb3f7643a9fb270fec2da7b2fdd839_N20_c448eedb05c2055f623323e190032a2515d7915f_N22 <http://www.w3.org/2006/vcard/ns#telephone> "963.555.1253" .
_:vivo_FacultyMember1_da39a3ee5e6b4b0d3255bfef95601890afd80709_N16_723954f9a9d06939b353c275793cae25fc84142e_N15_3801ff8dcedb0de739a3e046eb1a0dd0f708fbed_N18_81b3bdf355fe0ead809aea1553cfd2577ff9de25_N17_2e132849e08f1985e527da711db8f2916e1af897_N14_7172ca691e578058d8982816b652e5ee77ec076f_N21_864c165155eb3f7643a9fb270fec2da7b2fdd839_N20_c448eedb05c2055f623323e190032a2515d7915f_N22 <http://www.w3.org/2006/vcard/ns#familyName> "Burks" .
_:vivo_FacultyMember1_da39a3ee5e6b4b0d3255bfef95601890afd80709_N16_723954f9a9d06939b353c275793cae25fc84142e_N15_3801ff8dcedb0de739a3e046eb1a0dd0f708fbed_N18_81b3bdf355fe0ead809aea1553cfd2577ff9de25_N17_2e132849e08f1985e527da711db8f2916e1af897_N14_7172ca691e578058d8982816b652e5ee77ec076f_N21_864c165155eb3f7643a9fb270fec2da7b2fdd839_N20_c448eedb05c2055f623323e190032a2515d7915f_N22 <http://www.w3.org/2006/vcard/ns#givenName> "Rosella" .
_:vivo_FacultyMember1_da39a3ee5e6b4b0d3255bfef95601890afd80709_N16_723954f9a9d06939b353c275793cae25fc84142e_N15_3801ff8dcedb0de739a3e046eb1a0dd0f708fbed_N18_81b3bdf355fe0ead809aea1553cfd2577ff9de25_N17_2e132849e08f1985e527da711db8f2916e1af897_N14_7172ca691e578058d8982816b652e5ee77ec076f_N21_864c165155eb3f7643a9fb270fec2da7b2fdd839_N20_c448eedb05c2055f623323e190032a2515d7915f_N22 <http://www.w3.org/2006/vcard/ns#uid> "3130" .
_:vivo_FacultyMember1_da39a3ee5e6b4b0d3255bfef95601890afd80709_N16_723954f9a9d06939b353c275793cae25fc84142e_N15_3801ff8dcedb0de739a3e046eb1a0dd0f708fbed_N18_81b3bdf355fe0ead809aea1553cfd2577ff9de25_N17_2e132849e08f1985e527da711db8f2916e1af897_N14_7172ca691e578058d8982816b652e5ee77ec076f_N21_864c165155eb3f7643a9fb270fec2da7b2fdd839_N20_c448eedb05c2055f623323e190032a2515d7915f_N22 <http://www.w3.org/2006/vcard/ns#email> "BurksR@univ.edu" .
_:vivo_FacultyMember1_da39a3ee5e6b4b0d3255bfef95601890afd80709_N16_723954f9a9d06939b353c275793cae25fc84142e_N15_3801ff8dcedb0de739a3e046eb1a0dd0f708fbed_N18_81b3bdf355fe0ead809aea1553cfd2577ff9de25_N17_2e132849e08f1985e527da711db8f2916e1af897_N14_7172ca691e578058d8982816b652e5ee77ec076f_N21_864c165155eb3f7643a9fb270fec2da7b2fdd839_N20_c448eedb05c2055f623323e190032a2515d7915f_N22 <http://vivoweb.org/ontology/core#hrJobTitle> "Professor " .
_:vivo_FacultyMember1_da39a3ee5e6b4b0d3255bfef95601890afd80709_N16_723954f9a9d06939b353c275793cae25fc84142e_N15_3801ff8dcedb0de739a3e046eb1a0dd0f708fbed_N18_81b3bdf355fe0ead809aea1553cfd2577ff9de25_N17_2e132849e08f1985e527da711db8f2916e1af897_N14_7172ca691e578058d8982816b652e5ee77ec076f_N21_864c165155eb3f7643a9fb270fec2da7b2fdd839_N20_c448eedb05c2055f623323e190032a2515d7915f_N22 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#FacultyMember>

**Comment by mbgross** [comment]
Hi, I'm a very new user to Karma and having the same problem with blank nodes. Using Karma v2.033 and vivo.isf-public-1.6.owl ontology. I'm confused at what to set as the base uri vs the RDF graphs option in the publish dialog, and whether tthat's the source of the problem. I cannot figure out how to define a URI for a class individually. Thanks in advance.

**Comment by dkapoor** [comment]
If you FacultyMembers in the dataset have identifiers, then you can set the URI of the class to be that identifier. The Base URI can be the URI that you would want to be prepended to the FacultyMember URIs, that could be the URI for vivo or your own uri. Example: http://faculty.com/v1/
So the URI of a FacultyMember with identifier 14567899 would get generated as http://faculty.com/v1/14567899.

The options in the Publish RDF are:
RDF Graphs: 
* You can either create a new context or select an existing context
* If you choose an existing context, you can choose to append to the context or replace it.
* Add Inverse Properties lets you add the inverse properties of the links if they exist in the ontology, even though you have not added them to the model

**Comment by gneissone** [comment]
Thank you for the response. I've managed to assign URIs to members by following the instructions in the step-by-step wiki at https://github.com/InformationIntegrationGroup/karma-step-by-step/wiki. It's mostly working now. I'm still getting some blank nodes so I'm guessing my model needs tweaked. I was originally using https://www.youtube.com/watch?v=EQcMc4TrfuE as a reference, which I realize is an old video. Part of my confusion stemmed from the RDF Graphs dropdown replacing the namespace box, coupled with the addition of the Base URI option.
