### ISSUE TITLE
Cannot remove links

### ISSUE THREAD

**Issue by KarinBecker** [usc-isi-i2/Web-Karma#154]
![observationmapping](https://cloud.githubusercontent.com/assets/8549420/5324393/f7811c88-7c8e-11e4-8909-1cbd41ea0335.png)

I cannot remove the link value between Resource1 and Resource2 (value). I tried through delete, and manage link of both Resource1 and Resource2.

**Comment by dkapoor** [comment]
As per https://webkarma.atlassian.net/browse/WK-418, the delete should work now.
