### ISSUE TITLE
py transform is not working correctly when converted to ref

### ISSUE THREAD

**Issue by KarinBecker** [usc-isi-i2/Web-Karma#158]
tried the return getValue("attribute")+"@en".
Value transformed correctly.
When ref was generated, value was value of the attribute@en@en (duplicated).

**Comment by dkapoor** [comment]
We not have the feature to add the language when setting the semantic type.
So now the PyTransform should return just `return getValue("attribute")` and then when setting the semantic type, you can select the language to be `en` and it will generate the correct output.
