### ISSUE TITLE
cannot handle all ontologies in t/l format correctly

### ISSUE THREAD

**Issue by KarinBecker** [usc-isi-i2/Web-Karma#159]
Put all ontologies in pre-loaded ontology folder in ttl format.
When started karma, it complained about some of them (e.g. org.ttl).
Verified t/l using a validator, and it was correct. Generated a equivalent .owl file, and started karma again, and everything was fine.

**Comment by dkapoor** [comment]
Tried loading schema.org.ttl file from here https://github.com/antlr/grammars-v4/blob/master/turtle/examples/schema.org.ttl and it loaded fine. This issue seems to be resolved.
