### ISSUE TITLE
cannot find concepts in the pre-loaded ontology

### ISSUE THREAD

**Issue by KarinBecker** [usc-isi-i2/Web-Karma#160]
cube ontology was loaded in the preloaded ontology folder in ttl format. Some property concepts are not found by karma during set semantic type operation (e.g. qb:measure, qb:dimension).

Verified ontology, changed ontology to owl file, problem persisted.

**Comment by dkapoor** [comment]
Created a bug in JIRA for this: https://webkarma.atlassian.net/browse/WK-468. Closing it here.
