### ISSUE TITLE
Complex text in .xls spoils the load

### ISSUE THREAD

**Issue by jmvanel** [usc-isi-i2/Web-Karma#164]
A Complex text in a cell , with line feeds and punctuation period, like this, fools the loading, and the different sentences delimited by a period appear in different cells in Karma.

___
AgroNergy propose aux installations collectives de taille intermédiaire une solution intégrée et innovante de chauffage par la biomasse triplement performante. Sur la base d’un brevet déposé, AgroNergy produit des granulés à base de déchets agricoles non utilisables, auxquels est ajouté un additif formulé spécifiquement. AgroNergy installe ensuite les chaudières (100kW à 1000kW) appropriées chez ses clients, qui ne paient que les calories consommées.
Une solution écologiquement performante : AgroNergy propose une énergie propre et renouvelable, sans mâchefer ni pollution atmosphérique.
Une solution économiquement performante.  Le client ne paye que la chaleur qu'il a consommée : le coût global est compétitif, et découplé de la hausse des combustibles fossiles. De plus, il n'a pas à engager d'investissement dans la chaudière. AgroNergy garantit l’approvisionnement en agropellets et la mise à disposition d'une chaudière adaptée pour une meilleure maitrise de la facture énergétique.
Une solution techniquement performante : AgroNergy offre une solution brevetée agréée par les fabricants de chaudières et répondant à la norme européenne (prEN 14961-6). Le PCI des agropellets est supérieur à celui des granulés bois.
___

**Comment by dkapoor** [comment]
We are using Apache POI version 3.8.
