### ISSUE TITLE
Build Error on Mac

### ISSUE THREAD

**Issue by gauteremen** [usc-isi-i2/Web-Karma#168]
![skjermbilde 2015-01-26 kl 20 40 49](https://cloud.githubusercontent.com/assets/7688952/5906937/b760c0a0-a59b-11e4-874f-9f2831bdbff5.png)
![skjermbilde 2015-01-26 kl 20 41 00](https://cloud.githubusercontent.com/assets/7688952/5906941/b9a703ce-a59b-11e4-9dd6-da5cd982e44b.png)

Hi!

I downloaded Karma to work with development on semantic apps. 
I read a issue further down about a build error, and I am getting the same error. I run mvn clean install from the root directory of Karma (web-karma-master), updated maven to v.3.2.5 and java to 1.7. 
I also have defined the path to the Java JDK on my mac. 

I am out of ideas.. Is there any solution to this?

**Comment by dkapoor** [comment]
can you do mvn --version and let me know what output it gives you

**Comment by gauteremen** [comment]
Sure!

Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /users/gautegjerlowremen/downloads/apache-maven-3.2.5
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: nb_NO, platform encoding: MacRoman
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"

**Comment by dkapoor** [comment]
If you see in the output of mvn --version, your java home is still pointing to jdk1.6.
Can you set JAVA_HOME to your JDK 1.7 and then make sure mvn --version displays the right version/path

**Comment by gauteremen** [comment]
Yep done. Still getting the build error though..

Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /users/gautegjerlowremen/downloads/apache-maven-3.2.5
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/jre
Default locale: nb_NO, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"

**Comment by dkapoor** [comment]
Can you run 'mvn clean' and if that passes then run 'mvn install'

**Comment by gauteremen** [comment]
Seems like it is some wierd error somewhere. Both the path of maven and java reset when I exit terminal. However, they when i’m sure both are loaded, there is still no build. mvn clean did not pass .. 


-- 
Med vennlig hilsen
Gaute Gjerløw Remen


På 26. januar 2015 på 22.10.42, dkapoor (notifications@github.com) skrev:

Can you run 'mvn clean' and if that passes then run 'mvn install'

**Comment by dkapoor** [comment]
mvn clean is just deleting directories.
It not passing is a permission issue. Can you make sure you have permission to modify the karma folder and all its sub-folders.

**Comment by gauteremen** [comment]
I see..

It would be great to have a conversation on Skype on this issue.
If you have the time and possibility? 

And if so, can we arrange a time to do this?

-- 
Kind Regards
Gaute Gjerløw Remen


På 27. januar 2015 på 20.50.24, dkapoor (notifications@github.com) skrev:

mvn clean is just deleting directories.
It not passing is a permission issue. Can you make sure you have permission to modify the karma folder and all its sub-folders.

**Comment by dkapoor** [comment]
How about 10am tomorrow. My skype id is dipsykapoor

**Comment by gauteremen** [comment]
Yes, that is possible depending on which timezone you live in. I have some things to take care of today, and I live in Norway. :)

-- 
Med vennlig hilsen
Gaute Gjerløw Remen


På 28. januar 2015 på 03.55.37, dkapoor (notifications@github.com) skrev:

How about 10am tomorrow. My skype id is dipsykapoor

**Comment by dkapoor** [comment]
PST. Or we could do it tomorrow if that works better

**Comment by gauteremen** [comment]
Sure, that would be great. I will try some more to make it work. 
around 10am then, 7pm here. 

Sounds good? 
-- 
Med vennlig hilsen
Gaute Gjerløw Remen


På 28. januar 2015 på 16.11.44, dkapoor (notifications@github.com) skrev:

PST. Or we could do it tomorrow if that works better

**Comment by dkapoor** [comment]
Yes, sounds good.

**Comment by gauteremen** [comment]
Hi again!

I bought myself a laptop (with windows 7) and managed to install Karma 
on it.
So now I will try it out now!

So, as of the skype meeting - I don't need to get guidance right now.
Thank you anyways!

Kind Regards,
Gaute

Den 28.01.2015 17:23, skrev dkapoor:

**Comment by gauteremen** [comment]
Hi!

I just want to say that Karma works perfectly!
Making our work so much easier.

Thanks for the good work!

-- 
Best Regards,
Gaute Gjerløw Remen


På 28. januar 2015 på 17.23.27, dkapoor (notifications@github.com) skrev:

Yes, sounds good.

**Comment by goldsminkle** [comment]
Hello, I am having the same issue on Yosemite with Java 1.7 and maven3. Where is the "mvn --version"'s Java version coming from? 

$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home

$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home

$ mvn --version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
Maven home: /opt/local/share/java/maven3
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"

$ rm ~/.m2 -rf

$ mvn clean

[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ web-services-publish-es ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ISI Karma Maven Webapp ............................. SUCCESS [  0.958 s]
[INFO] karma-util ......................................... SUCCESS [  0.025 s]
[INFO] karma-typer ........................................ SUCCESS [  0.014 s]
[INFO] karma-common ....................................... SUCCESS [  0.039 s]
[INFO] karma-cleaning ..................................... SUCCESS [  0.029 s]
[INFO] karma-commands ..................................... SUCCESS [  0.015 s]
[INFO] commands-common .................................... SUCCESS [  0.076 s]
[INFO] commands-update .................................... SUCCESS [  0.011 s]
[INFO] commands-worksheet ................................. SUCCESS [  0.014 s]
[INFO] commands-cleaning .................................. SUCCESS [  0.017 s]
[INFO] commands-alignment ................................. SUCCESS [  0.013 s]
[INFO] commands-python .................................... SUCCESS [  0.012 s]
[INFO] commands-alignment-openrdf ......................... SUCCESS [  0.025 s]
[INFO] commands-publish ................................... SUCCESS [  0.013 s]
[INFO] karma-jdbc ......................................... SUCCESS [  0.010 s]
[INFO] commands-publish-jdbc .............................. SUCCESS [  0.018 s]
[INFO] commands-publish-alignment-openrdf ................. SUCCESS [  0.009 s]
[INFO] commands-update-jdbc ............................... SUCCESS [  0.012 s]
[INFO] commands-import .................................... SUCCESS [  0.008 s]
[INFO] import-common ...................................... SUCCESS [  0.008 s]
[INFO] import-csv ......................................... SUCCESS [  0.013 s]
[INFO] import-database .................................... SUCCESS [  0.009 s]
[INFO] import-excel ....................................... SUCCESS [  0.012 s]
[INFO] import-file ........................................ SUCCESS [  0.009 s]
[INFO] import-ontology .................................... SUCCESS [  0.008 s]
[INFO] import-json ........................................ SUCCESS [  0.016 s]
[INFO] import-service ..................................... SUCCESS [  0.010 s]
[INFO] import-spatial ..................................... SUCCESS [  0.012 s]
[INFO] import-xml ......................................... SUCCESS [  0.009 s]
[INFO] import-avro ........................................ SUCCESS [  0.008 s]
[INFO] commands-include ................................... SUCCESS [  0.017 s]
[INFO] karma-web .......................................... SUCCESS [  0.011 s]
[INFO] karma-offline ...................................... SUCCESS [  0.008 s]
[INFO] commands-bloom ..................................... SUCCESS [  0.009 s]
[INFO] karma-mr ........................................... SUCCESS [  0.017 s]
[INFO] karma-storm ........................................ SUCCESS [  3.802 s]
[INFO] karma-web-services ................................. SUCCESS [  0.008 s]
[INFO] web-services-rdf ................................... SUCCESS [  0.009 s]
[INFO] web-services-publish-es ............................ SUCCESS [  0.009 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.994 s
[INFO] Finished at: 2015-03-10T22:55:08-07:00
[INFO] Final Memory: 13M/81M
[INFO] ------------------------------------------------------------------------

$ mvn clean install

[INFO] Reactor Summary:
[INFO] 
[INFO] ISI Karma Maven Webapp ............................. SUCCESS [  1.184 s]
[INFO] karma-util ......................................... FAILURE [  3.233 s]
[INFO] karma-typer ........................................ SKIPPED
[INFO] karma-common ....................................... SKIPPED
[INFO] karma-cleaning ..................................... SKIPPED
[INFO] karma-commands ..................................... SKIPPED
[INFO] commands-common .................................... SKIPPED
[INFO] commands-update .................................... SKIPPED
[INFO] commands-worksheet ................................. SKIPPED
[INFO] commands-cleaning .................................. SKIPPED
[INFO] commands-alignment ................................. SKIPPED
[INFO] commands-python .................................... SKIPPED
[INFO] commands-alignment-openrdf ......................... SKIPPED
[INFO] commands-publish ................................... SKIPPED
[INFO] karma-jdbc ......................................... SKIPPED
[INFO] commands-publish-jdbc .............................. SKIPPED
[INFO] commands-publish-alignment-openrdf ................. SKIPPED
[INFO] commands-update-jdbc ............................... SKIPPED
[INFO] commands-import .................................... SKIPPED
[INFO] import-common ...................................... SKIPPED
[INFO] import-csv ......................................... SKIPPED
[INFO] import-database .................................... SKIPPED
[INFO] import-excel ....................................... SKIPPED
[INFO] import-file ........................................ SKIPPED
[INFO] import-ontology .................................... SKIPPED
[INFO] import-json ........................................ SKIPPED
[INFO] import-service ..................................... SKIPPED
[INFO] import-spatial ..................................... SKIPPED
[INFO] import-xml ......................................... SKIPPED
[INFO] import-avro ........................................ SKIPPED
[INFO] commands-include ................................... SKIPPED
[INFO] karma-web .......................................... SKIPPED
[INFO] karma-offline ...................................... SKIPPED
[INFO] commands-bloom ..................................... SKIPPED
[INFO] karma-mr ........................................... SKIPPED
[INFO] karma-storm ........................................ SKIPPED
[INFO] karma-web-services ................................. SKIPPED
[INFO] web-services-rdf ................................... SKIPPED
[INFO] web-services-publish-es ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.923 s
[INFO] Finished at: 2015-03-10T22:56:26-07:00
[INFO] Final Memory: 13M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project karma-util: Fatal error compiling: invalid target release: 1.7 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :karma-util

**Comment by dkapoor** [comment]
As per maven documentation: http://maven.apache.org/download.cgi, it picks the java from JAVA_HOME, but that doesnt seem to be happening in your case.
Can you see what java -version returns? and if it points to 1.6, then fix it to point to 1.7.

**Comment by goldsminkle** [comment]
Hi,

$  java -version
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)

**Comment by dkapoor** [comment]
Can you try $JAVA_HOME/bin/java -version

**Comment by drdn** [comment]
Hi,

I'm having similar problems as above.

No proxies, no firewall, and I can access the repositories through my browser.

$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home

$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"

$ rm -rf .m2

$ mvn clean

[INFO] Reactor Summary:
[INFO] 
[INFO] ISI Karma Maven Webapp ............................. SUCCESS [  3.462 s]
[INFO] karma-util ......................................... SUCCESS [  0.007 s]
[INFO] karma-typer ........................................ SUCCESS [  0.002 s]
[INFO] karma-common ....................................... SUCCESS [  0.002 s]
[INFO] karma-cleaning ..................................... SUCCESS [  0.002 s]
[INFO] karma-commands ..................................... SUCCESS [  0.002 s]
[INFO] commands-common .................................... SUCCESS [  0.001 s]
[INFO] commands-update .................................... SUCCESS [  0.002 s]
[INFO] commands-worksheet ................................. SUCCESS [  0.001 s]
[INFO] commands-cleaning .................................. SUCCESS [  0.002 s]
[INFO] commands-alignment ................................. SUCCESS [  0.001 s]
[INFO] commands-python .................................... SUCCESS [  0.002 s]
[INFO] commands-alignment-openrdf ......................... SUCCESS [  0.001 s]
[INFO] commands-publish ................................... SUCCESS [  0.002 s]
[INFO] karma-jdbc ......................................... SUCCESS [  0.002 s]
[INFO] commands-publish-jdbc .............................. SUCCESS [  0.002 s]
[INFO] commands-publish-alignment-openrdf ................. SUCCESS [  0.002 s]
[INFO] commands-update-jdbc ............................... SUCCESS [  0.001 s]
[INFO] commands-import .................................... SUCCESS [  0.001 s]
[INFO] import-common ...................................... SUCCESS [  0.002 s]
[INFO] import-csv ......................................... SUCCESS [  0.001 s]
[INFO] import-database .................................... SUCCESS [  0.001 s]
[INFO] import-excel ....................................... SUCCESS [  0.002 s]
[INFO] import-file ........................................ SUCCESS [  0.001 s]
[INFO] import-ontology .................................... SUCCESS [  0.001 s]
[INFO] import-json ........................................ SUCCESS [  0.001 s]
[INFO] import-service ..................................... SUCCESS [  0.001 s]
[INFO] import-spatial ..................................... SUCCESS [  0.002 s]
[INFO] import-xml ......................................... SUCCESS [  0.001 s]
[INFO] import-avro ........................................ SUCCESS [  0.001 s]
[INFO] commands-include ................................... SUCCESS [  0.003 s]
[INFO] karma-web .......................................... SUCCESS [  0.001 s]
[INFO] karma-offline ...................................... SUCCESS [  0.002 s]
[INFO] commands-bloom ..................................... SUCCESS [  0.001 s]
[INFO] karma-jsonld ....................................... SUCCESS [  0.002 s]
[INFO] karma-mr ........................................... SUCCESS [  0.001 s]
[INFO] karma-storm ........................................ SUCCESS [  0.706 s]
[INFO] karma-web-services ................................. SUCCESS [  0.002 s]
[INFO] web-services-rdf ................................... SUCCESS [  0.001 s]
[INFO] web-services-publish-es ............................ SUCCESS [  0.002 s]
[INFO] karma-spark ........................................ SUCCESS [  0.002 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.774 s
[INFO] Finished at: 2016-03-22T14:13:28-04:00
[INFO] Final Memory: 18M/310M
[INFO] ------------------------------------------------------------------------

$ mvn install

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ISI Karma Maven Webapp ............................. SUCCESS [ 16.968 s]
[INFO] karma-util ......................................... SUCCESS [02:01 min]
[INFO] karma-typer ........................................ FAILURE [01:23 min]
[INFO] karma-common ....................................... SKIPPED
[INFO] karma-cleaning ..................................... SKIPPED
[INFO] karma-commands ..................................... SKIPPED
[INFO] commands-common .................................... SKIPPED
[INFO] commands-update .................................... SKIPPED
[INFO] commands-worksheet ................................. SKIPPED
[INFO] commands-cleaning .................................. SKIPPED
[INFO] commands-alignment ................................. SKIPPED
[INFO] commands-python .................................... SKIPPED
[INFO] commands-alignment-openrdf ......................... SKIPPED
[INFO] commands-publish ................................... SKIPPED
[INFO] karma-jdbc ......................................... SKIPPED
[INFO] commands-publish-jdbc .............................. SKIPPED
[INFO] commands-publish-alignment-openrdf ................. SKIPPED
[INFO] commands-update-jdbc ............................... SKIPPED
[INFO] commands-import .................................... SKIPPED
[INFO] import-common ...................................... SKIPPED
[INFO] import-csv ......................................... SKIPPED
[INFO] import-database .................................... SKIPPED
[INFO] import-excel ....................................... SKIPPED
[INFO] import-file ........................................ SKIPPED
[INFO] import-ontology .................................... SKIPPED
[INFO] import-json ........................................ SKIPPED
[INFO] import-service ..................................... SKIPPED
[INFO] import-spatial ..................................... SKIPPED
[INFO] import-xml ......................................... SKIPPED
[INFO] import-avro ........................................ SKIPPED
[INFO] commands-include ................................... SKIPPED
[INFO] karma-web .......................................... SKIPPED
[INFO] karma-offline ...................................... SKIPPED
[INFO] commands-bloom ..................................... SKIPPED
[INFO] karma-jsonld ....................................... SKIPPED
[INFO] karma-mr ........................................... SKIPPED
[INFO] karma-storm ........................................ SKIPPED
[INFO] karma-web-services ................................. SKIPPED
[INFO] web-services-rdf ................................... SKIPPED
[INFO] web-services-publish-es ............................ SKIPPED
[INFO] karma-spark ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:41 min
[INFO] Finished at: 2016-03-22T14:17:59-04:00
[INFO] Final Memory: 30M/319M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project karma-typer: Could not resolve dependencies for project edu.isi:karma-typer:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.apache.commons:commons-math3:jar:3.4-modified: Failed to read artifact descriptor for org.apache.commons:commons-math3:jar:3.4-modified: Could not transfer artifact org.apache.commons:commons-math3:pom:3.4-modified from/to colo-vm41 (http://colo-vm41.isi.edu/artifactory/simple/libs-release-local/): Connect to colo-vm41.isi.edu:80 [colo-vm41.isi.edu/128.9.144.168] failed: Operation timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :karma-typer

**Comment by dkapoor** [comment]
We restarted the service. Can you run `mvn clean install` again. Thanks.

**Comment by drdn** [comment]
I ran it again and this time `mvn clean install` (and `mvn clean`) failed on karma-util.

[INFO] Reactor Summary:
[INFO] 
[INFO] ISI Karma Maven Webapp ............................. SUCCESS [  0.110 s]
[INFO] karma-util ......................................... FAILURE [  1.066 s]
[INFO] karma-typer ........................................ SKIPPED
[INFO] karma-common ....................................... SKIPPED
[INFO] karma-cleaning ..................................... SKIPPED
[INFO] karma-commands ..................................... SKIPPED
[INFO] commands-common .................................... SKIPPED
[INFO] commands-update .................................... SKIPPED
[INFO] commands-worksheet ................................. SKIPPED
[INFO] commands-cleaning .................................. SKIPPED
[INFO] commands-alignment ................................. SKIPPED
[INFO] commands-python .................................... SKIPPED
[INFO] commands-alignment-openrdf ......................... SKIPPED
[INFO] commands-publish ................................... SKIPPED
[INFO] karma-jdbc ......................................... SKIPPED
[INFO] commands-publish-jdbc .............................. SKIPPED
[INFO] commands-publish-alignment-openrdf ................. SKIPPED
[INFO] commands-update-jdbc ............................... SKIPPED
[INFO] commands-import .................................... SKIPPED
[INFO] import-common ...................................... SKIPPED
[INFO] import-csv ......................................... SKIPPED
[INFO] import-database .................................... SKIPPED
[INFO] import-excel ....................................... SKIPPED
[INFO] import-file ........................................ SKIPPED
[INFO] import-ontology .................................... SKIPPED
[INFO] import-json ........................................ SKIPPED
[INFO] import-service ..................................... SKIPPED
[INFO] import-spatial ..................................... SKIPPED
[INFO] import-xml ......................................... SKIPPED
[INFO] import-avro ........................................ SKIPPED
[INFO] commands-include ................................... SKIPPED
[INFO] karma-web .......................................... SKIPPED
[INFO] karma-offline ...................................... SKIPPED
[INFO] commands-bloom ..................................... SKIPPED
[INFO] karma-jsonld ....................................... SKIPPED
[INFO] karma-mr ........................................... SKIPPED
[INFO] karma-storm ........................................ SKIPPED
[INFO] karma-web-services ................................. SKIPPED
[INFO] web-services-rdf ................................... SKIPPED
[INFO] web-services-publish-es ............................ SKIPPED
[INFO] karma-spark ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.490 s
[INFO] Finished at: 2016-03-22T14:51:44-04:00
[INFO] Final Memory: 13M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project karma-util: Failed to clean project: Failed to delete /Users/durden/Web-Karma-master/karma-util/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :karma-util

**Comment by dkapoor** [comment]
It is not able to delete the /Users/durden/Web-Karma-master/karma-util/target directory. Can you manually delete and try again.
Can you make sure you have read, write and execute permissions on all subfolders of Web-Karma.

**Comment by drdn** [comment]
rxw for all folders. Manually deleted the directory and re-ran the command. `mvn clean` passes and `mvn install` returns:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ISI Karma Maven Webapp ............................. SUCCESS [  0.171 s]
[INFO] karma-util ......................................... SUCCESS [  1.141 s]
[INFO] karma-typer ........................................ FAILURE [01:15 min]
[INFO] karma-common ....................................... SKIPPED
[INFO] karma-cleaning ..................................... SKIPPED
[INFO] karma-commands ..................................... SKIPPED
[INFO] commands-common .................................... SKIPPED
[INFO] commands-update .................................... SKIPPED
[INFO] commands-worksheet ................................. SKIPPED
[INFO] commands-cleaning .................................. SKIPPED
[INFO] commands-alignment ................................. SKIPPED
[INFO] commands-python .................................... SKIPPED
[INFO] commands-alignment-openrdf ......................... SKIPPED
[INFO] commands-publish ................................... SKIPPED
[INFO] karma-jdbc ......................................... SKIPPED
[INFO] commands-publish-jdbc .............................. SKIPPED
[INFO] commands-publish-alignment-openrdf ................. SKIPPED
[INFO] commands-update-jdbc ............................... SKIPPED
[INFO] commands-import .................................... SKIPPED
[INFO] import-common ...................................... SKIPPED
[INFO] import-csv ......................................... SKIPPED
[INFO] import-database .................................... SKIPPED
[INFO] import-excel ....................................... SKIPPED
[INFO] import-file ........................................ SKIPPED
[INFO] import-ontology .................................... SKIPPED
[INFO] import-json ........................................ SKIPPED
[INFO] import-service ..................................... SKIPPED
[INFO] import-spatial ..................................... SKIPPED
[INFO] import-xml ......................................... SKIPPED
[INFO] import-avro ........................................ SKIPPED
[INFO] commands-include ................................... SKIPPED
[INFO] karma-web .......................................... SKIPPED
[INFO] karma-offline ...................................... SKIPPED
[INFO] commands-bloom ..................................... SKIPPED
[INFO] karma-jsonld ....................................... SKIPPED
[INFO] karma-mr ........................................... SKIPPED
[INFO] karma-storm ........................................ SKIPPED
[INFO] karma-web-services ................................. SKIPPED
[INFO] web-services-rdf ................................... SKIPPED
[INFO] web-services-publish-es ............................ SKIPPED
[INFO] karma-spark ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:17 min
[INFO] Finished at: 2016-03-22T15:34:14-04:00
[INFO] Final Memory: 30M/316M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project karma-typer: Could not resolve dependencies for project edu.isi:karma-typer:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.apache.commons:commons-math3:jar:3.4-modified: Failed to read artifact descriptor for org.apache.commons:commons-math3:jar:3.4-modified: Could not transfer artifact org.apache.commons:commons-math3:pom:3.4-modified from/to colo-vm41 (http://colo-vm41.isi.edu/artifactory/simple/libs-release-local/): Connect to colo-vm41.isi.edu:80 [colo-vm41.isi.edu/128.9.144.168] failed: Operation timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :karma-typer

**Comment by dkapoor** [comment]
After restarting our artifacts server, the server url has changed. We just committed changes with the new url. Can you pull the latest version and try again. Thanks.

**Comment by drdn** [comment]
The install is still breaking at karma-typer (http://colo-vm41.isi.edu/artifactory/libs-release-local/org/apache/commons/commons-math3/3.4-modified/commons-math3-3.4-modified.pom).

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:17 min
[INFO] Finished at: 2016-03-22T15:59:55-04:00
[INFO] Final Memory: 26M/310M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project karma-typer: Could not resolve dependencies for project edu.isi:karma-typer:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.apache.commons:commons-math3:jar:3.4-modified: Failed to read artifact descriptor for org.apache.commons:commons-math3:jar:3.4-modified: Could not transfer artifact org.apache.commons:commons-math3:pom:3.4-modified from/to colo-vm41 (http://colo-vm41.isi.edu/artifactory/libs-release-local): Connect to colo-vm41.isi.edu:80 [colo-vm41.isi.edu/128.9.144.168] failed: Operation timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :karma-typer
