### ISSUE TITLE
Import Oracle Table Error

### ISSUE THREAD

**Issue by johnrey1** [usc-isi-i2/Web-Karma#169]
When trying to use the 'import table' function on my Oracle database i received the following

`Error occured while generating worksheet from Import Database Table!
edu.isi.karma.webserver.KarmaException: Unable to get data for limited rows ORA-00911: invalid character`

believe due to invalid escaping, going to submit pull request

**Comment by dkapoor** [comment]
Thanks John. We have merged the pull request.

**Comment by johnrey1** [comment]
great!
