### ISSUE TITLE
datasets folder not present in karma home directory

### ISSUE THREAD

**Issue by ananya11** [usc-isi-i2/Web-Karma#172]
Hi,

I installed Karma v2.033 on ubuntu 14.04. I want to load museum-ls
data.json file from datasets folder. But I couldn't find the datasets folder in karma home directory. Is this a new change because the step-by-step tutorial I am following was created on v2.002? If so, how can I get sample dataset to play around with the tool?

Below is a snapshot of what I see in terminal
ananya@nds-ananya-opt:~/karma$ pwd
/home/ananya/karma
ananya@nds-ananya-opt:~/karma$ ls
alignment-graph  models-graphviz       python               user-uploaded-files
config           models-json           semantic-type-files
models-autosave  preloaded-ontologies  user-preferences
ananya@nds-ananya-opt:~/karma$ 

Thanks,
Ananya

**Comment by dkapoor** [comment]
When you get Karma from github, it does not bundle any datasets or preloaded ontologies.
If you are following the step-by-step tutorial you can copy the datasets and ontologies from here: https://github.com/usc-isi-i2/karma-step-by-step. There is a folder for datasets and preloaded-ontologies. Copy these two in your karma home directory.

**Comment by ananya11** [comment]
thanks.
