### ISSUE TITLE
POM for edu.isi:commands-include:pom:0.0.1-SNAPSHOT is missing

### ISSUE THREAD

**Issue by inlutero** [usc-isi-i2/Web-Karma#175]
This had been working for me two weeks ago, tried it this week and the following problems:

------------------

Downloading: http://repo1.maven.org/maven2/edu/isi/commands-include/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://download.osgeo.org/webdav/geotools/edu/isi/commands-include/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo1.maven.org/maven2/edu/isi/commands-include/0.0.1-SNAPSHOT/commands-include-0.0.1-SNAPSHOT.pom
Downloading: https://repository.cloudera.com/artifactory/cloudera-repos/edu/isi/commands-include/0.0.1-SNAPSHOT/commands-include-0.0.1-SNAPSHOT.pom
Downloading: http://download.osgeo.org/webdav/geotools/edu/isi/commands-include/0.0.1-SNAPSHOT/commands-include-0.0.1-SNAPSHOT.pom
[WARNING] The POM for edu.isi:commands-include:pom:0.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:44 min
[INFO] Finished at: 2015-03-03T13:41:51-05:00
[INFO] Final Memory: 13M/491M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project karma-web: Could not resolve dependencies for project edu.isi:karma-web:war:0.0.1-SNAPSHOT: Failure to find edu.isi:commands-include:pom:0.0.1-SNAPSHOT in http://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

----------------

Any help appreciated

**Comment by dkapoor** [comment]
Can you switch back to the root Web-Karma folder and run `mvn clean` and then `mvn install` and then try again.

Thanks.

**Comment by inlutero** [comment]
----------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:36 min
[INFO] Finished at: 2015-03-03T14:22:01-05:00
[INFO] Final Memory: 75M/883M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project karma-mr: Could not resolve dependencies for project edu.isi:karma-mr:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.apache.hadoop:hadoop-minicluster:jar:2.4.0.2.1.3.0-563: Failed to read artifact descriptor for org.apache.hadoop:hadoop-minicluster:jar:2.4.0.2.1.3.0-563: Could not transfer artifact org.apache.hadoop:hadoop-minicluster:pom:2.4.0.2.1.3.0-563 from/to HDPReleases (http://repo.hortonworks.com/content/repositories/releases/): Connect to repo.hortonworks.com:80 [repo.hortonworks.com/54.225.131.199] failed: Connection refused -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn \<goals\> -rf :karma-mr
--------


Seems to have the same error....

**Comment by inlutero** [comment]
that failed on the build after the clean...

**Comment by dkapoor** [comment]
That is now a different error than before. It is not able to download some jars from the hortonworks repository as the site seems to be temporarily down: http://repo.hortonworks.com/content/repositories/releases/.

However, this affects you only if you are using Karma on a cluster. If you are running Karma using the web version or karma-offline, you should be able to still run the system.
Just `cd karma-web` and run `mvn jetty:run`

**Comment by inlutero** [comment]
I swear i tried that yesterday, but seems to have done the trick! Thank you kindly!
