### ISSUE TITLE
Windows-Publishing models,rdf,.. 

### ISSUE THREAD

**Issue by shivajah** [usc-isi-i2/Web-Karma#178]
On windows, karma can only publish each model,rdf,etc once. When I want to republish the model, it gives me this error:"The requested operation cannot be performed on a file with a user-mapped section open".
I have tried it on different windows systems, it doesn't work.It seems that it doesn't close the model file after publishing it, so it cannot open it to rewrite for second time.

**Comment by dkapoor** [comment]
What windows version are you trying this on?
We tested on Windows 7, 64 bit using the latest version of Karma (Master branch) and were able to publish models again

**Comment by shivajah** [comment]
we used latest version of karma on windows 8 and 8.1, 64 bit.

**Comment by dkapoor** [comment]
We could reproduce this issue on Windows 8.1 and have fixed the issue.
You could pull the latest version of Karma(v2.035) and try again.

**Comment by ffagnoni** [comment]
Sorry to say, but I have the same issue with Karma v2.037. My operating system is Windows 8.1 Pro.

If I try to publish the model more than once Karma give me this error: 
```
Error occured while generating R2RML model!
```
If I try to publish the RDF instead, the error message is a little more verbose:
```
Error occured while generating RDF: C:\iTeam\karma\Web-Karma-master\karma-web\src\main\webapp\publish\RDF\WSP1WS1.ttl (Unable to perform the specified operation on a file whose user-mapped section is open)
```

**Comment by dkapoor** [comment]
Can you follow the instructions on the wiki to fix this issue: https://github.com/usc-isi-i2/Web-Karma/wiki/Troubleshooting#in-windows-when-i-re-publish-my-model-or-json-or-any-other-file-it-gives-me-an-error-and-is-not-able-to-perform-the-operation
If you dont have the commented section in your pom, you can add it as per the instructions.

**Comment by ffagnoni** [comment]
thank you for your help, now it works like a beauty
