### ISSUE TITLE
RDF Generation Issue on Windows

### ISSUE THREAD

**Issue by NLSVTN** [usc-isi-i2/Web-Karma#179]
When a model is applied to an imported raw model, publishing of JSON, Model, Report is working fine, but RDF publishing gives an exception. Below you can see the screenshots of the windows prompt output.
![error1](https://cloud.githubusercontent.com/assets/5591700/6724691/07214132-cdba-11e4-8c08-2af6e5afd87c.jpg)
![error2](https://cloud.githubusercontent.com/assets/5591700/6724692/10951b1c-cdba-11e4-9c04-ea5b5b738865.jpg)

**Comment by dkapoor** [comment]
Could you send your Karma home directory, the dataset and model to dipsy@isi.edu
Thanks.

**Comment by dkapoor** [comment]
Also, what version of Karma are you using? We had an update to fix some Windows related issues. Can you make sure you are on v2.035
