### ISSUE TITLE
Compatible properties list empty when editing a link

### ISSUE THREAD

**Issue by raonischal** [usc-isi-i2/Web-Karma#180]
When I am editing a link, if I choose a different class, the list of compatible properties is not shown.

Attached is a screenshot for reference
![links](https://cloud.githubusercontent.com/assets/11553687/6727645/cb4f3ff2-cde0-11e4-9f68-78579f423b53.png)

**Comment by dkapoor** [comment]
Could you attach your karma home folder or send it to dipsy@isi.edu
For a work around, you can still select the property from "All Properties"

**Comment by dkapoor** [comment]
Tracked as: https://webkarma.atlassian.net/browse/WK-436
