### ISSUE TITLE
Karma takes a long time to load after saving a model

### ISSUE THREAD

**Issue by raonischal** [usc-isi-i2/Web-Karma#181]
After building my source model, I saved it. When I started Karma again, it takes a lot of time to load the page (it feels as if the screen froze). I get the following errors in the console:

```
...
ERROR [2015-03-19 03:20:05,224] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,224] (GraphBuilder->addLink->486): The link source http://schema.org/Painting1 does not exist in the graph
ERROR [2015-03-19 03:20:05,225] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,225] (GraphBuilder->addLink->486): The link source http://schema.org/AppendAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,225] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,226] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,226] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,226] (GraphBuilder->addLink->486): The link source http://schema.org/WPFooter1 does not exist in the graph
ERROR [2015-03-19 03:20:05,226] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,227] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,227] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,227] (GraphBuilder->addLink->486): The link source http://schema.org/DislikeAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,227] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,228] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the graph
ERROR [2015-03-19 03:20:05,228] (GraphBuilder->addLink->486): The link source http://schema.org/BookmarkAction1 does not exist in the
...
```
It again starts working if I delete the `karma` folder in my home directory
```
Operating System: Windows 8.1
```

**Comment by dkapoor** [comment]
Could you attach or send your Karma home folder, the dataset and model to dipsy@isi.edu
Thanks/

**Comment by dkapoor** [comment]
Also, are the ontologies that you are using in the karma home\preloaded-ontologies folder or are you importing them from Karma UI? It would help if they are in the karma home\preloaded-ontologies folder.

**Comment by raonischal** [comment]
It's fast when I have the ontologies in the preloaded-ontologies folder.

**Comment by taheriyan** [comment]
What is slowing down Karma in this case is loading a large Alignment Graph (34.6MB) from karma/alignment-graph/graph.json when Karma main page is loading/restarting. When the ontology is loaded into Karma (manually or by putting it in the preloaded-ontologies folder), it takes around 5 sec in my machine to load the graph. However, when the ontology is not loaded, Karma generates a lot of error logs when trying to add the nodes and links of the alignment graph (e.g., the resource does not exist in the ontology). These log messages make loading the alignment graph (and consequently loading Karma) very slow (25 sec in my machine). 
I changed the log level of these specific messages from ERROR to DEBUG, which reduced the running time from 25 sec to 2 sec when the ontologies are not loaded into Karma. 
The other thing that users can do is to disable the flag "learner.enabled" in the config file: karma/config/modeling.properties. If users are not going to use automatic modeling of sources, they can set this flag to false, then, Karma does not load the Alignment Graph at load/restart time.
