### ISSUE TITLE
Data goes missing on applying model

### ISSUE THREAD

**Issue by raonischal** [usc-isi-i2/Web-Karma#182]
When I apply a saved model to the data I had exported earlier, some of the data values goes missing.
Please see the attached screenshot for details.
![before](https://cloud.githubusercontent.com/assets/11553687/6746434/624e50ec-ce85-11e4-907d-f39d16d33221.png)
![after](https://cloud.githubusercontent.com/assets/11553687/6746435/6528c176-ce85-11e4-9515-6c76dcf8b1ba.png)

**Comment by dkapoor** [comment]
Are the values still there when you export RDF/JSON?

**Comment by raonischal** [comment]
Hi,

When I export the data again, the values are blank.

I had sent you the original dataset and the home folder in an email for the issues #180 and #181. I also sent you a new email with the dataset that was exported from Karma.

Also, the columns whose values are empty were created in Karma using pytransform. Here's the list of actions I had taken:
1. Import the original dataset.
2. Add new column
3. Using pytransform, ( return values.split(" => ")[1]) populate values in the new column.
4. Do source modeling.
5. Publish model, json etc.
6. Return to Karma
7. Load the saved dataset
8. Load the model

Thanks.

**Comment by dkapoor** [comment]
Hi,

I am trying to reproduce your problem in Windows 8.1, but cannot reproduce it.
I copied schema.xml to the preloaded-ontologies and then started karma. I imported the file and then applied the model. The model got applied and I do get the Publication URIs

![screen shot 2015-03-22 at 8 23 47 pm](https://cloud.githubusercontent.com/assets/1852707/6773671/b251a00a-d0d1-11e4-8555-9bb612faa40c.png)

Can you try again, or if it is consistent, can you see if you are getting some error in the console.

**Comment by raonischal** [comment]
It is happening consistently. I sent you an email with the log file.

**Comment by raonischal** [comment]
I think I understand what is happening. I was uploading the JSON data exported from karma (which includes the newly added columns using pytransform) instead of the original dataset. Karma is trying to again add a new column by executing the pytransform to split on " => ". But since the column now does not contain " => " it returns an empty column.

I tried uploading the original dataset and applied the model and it works fine.

I am closing this issue.
