### ISSUE TITLE
Print model does not print the entire model

### ISSUE THREAD

**Issue by raonischal** [usc-isi-i2/Web-Karma#183]
When I click on Print Model, it does not print the entire model (screenshot attached). There are 31 columns of data.
![div svgdiv_ws1](https://cloud.githubusercontent.com/assets/11553687/6746545/4d057e52-ce87-11e4-942e-db750cbf0de3.png)

**Comment by dkapoor** [comment]
Tracked as: https://webkarma.atlassian.net/browse/WK-435
