### ISSUE TITLE
java heap space

### ISSUE THREAD

**Issue by milantracy** [usc-isi-i2/Web-Karma#184]
I have a data file with 300+ records and 3000+ objects, and I import the lastest ontology file from schema.org, however I still can't push a model. Publishing JSON and report are fine, but publishing rdf will cause a over time error.
I have set my jetty configure in pom.xml to
                      -XX:MaxPermSize=1024M -Xms2g -Xmx4g
but I still get java.lang.OutOfMemoryError: Java heap space when I publish a model in karma, how can I solve this problem?

I run the Karma on a Macbook with 8GB memory.

**Comment by milantracy** [comment]
I have updated karma to  v2.035 which is the lastest version, but I still get the same question

**Comment by ukby1234** [comment]
Can you try* export MAVEN_OPTS*="-Xms2g -Xmx4g -XX:PermSize=1024m" in the
terminal first? If it works, then put into the bash profile(if using bash).

**Comment by milantracy** [comment]
After run the command you mention, the problem is still the same, and there is a error message in browser, which is GenerateR2RMLModelCommanderror.

**Comment by ukby1234** [comment]
Can I have the karma home zipped, with the data set, so that I can test?
My email is ukby.1234@gmail.com
