### ISSUE TITLE
Karma expects to be root webapp?

### ISSUE THREAD

**Issue by ajs6f** [usc-isi-i2/Web-Karma#185]
I am trying to deploy Karma to a Tomcat 6 container (I am without choice in the matter). When I deploy Karma (under the name karma-web), along with its external web-app dependencies, I have no trouble importing data files, but I cannot successfully import models. When I try (out of curiosity) to add models via Karma's collection service, I see exceptions like:

`java.io.FileNotFoundException: http://MY-SERVER-NAME:8080/R2RMLMapping/local`

which seems to imply that Karma is not finding its own servlets because they are mounted under a web-app name, and not as the root web-app. Could this be the problem? I would like to turn up the logging to see what is going wrong, but I cannot find any logging configuration, although I see log4j and slf-log4j in the classpath. Are we expected to introduce our own logging configuration?

Thanks for any help with this. I look forward to exploring a really intriguing project.

**Comment by ukby1234** [comment]
Yes, it won't work if it's not a root webapp.

**Comment by ajs6f** [comment]
Is there not some scheme to fix this problem? It seems rather limiting... I would be happy to help do some recoding if that would be useful. It seems like it should just be a matter of using the proper relative URLs.

**Comment by ajs6f** [comment]
I find in:
`/karma-web/src/main/webapp/js/model.js`
at line 44:
`$('#txtGraph_URL_Save', dialog).val(window.location.protocol + "//" + window.location.host + "/R2RMLMapping/local");`

That seems to be at least one of the places where any web-app name is being dropped.

**Comment by ajs6f** [comment]
Also in:
`edu.isi.karma.controller.command.worksheet`
which is in:
`karma-commands`
at line 24 there is:
`private String baseUrl = "http://localhost:8080/R2RMLMapping/local/repository/";`

which seems to be a dangerous assumption.

**Comment by ajs6f** [comment]
Is Karma open to receiving a pull request that begins to correct some of these problems?

**Comment by ukby1234** [comment]
Yes, it accepts a pull request.

**Comment by ajs6f** [comment]
I've begun tinkering with this problem, and already I have some questions. I've altered code in the first place mentioned above, and gotten a little further than I was getting. However, I am now running into the problem that when saving a R2ML mapping into the Sesame repository, openrdf-sesame expects a `context` parameter that is an absolute URI, and Karma is trying to use the URI `/karma/R2RMLMapping/local` which is clearly not absolute. I need some advice on how that value is chosen and how I might influence it. Is there an IRC room where Karma development goes on or an open call or the like, or is this Github issue the best place to get advice on developing Karma?

**Comment by ukby1234** [comment]
We don't have an IRC room for this. We can probably discuss through Github issue or Google hangout, if that works for you. Meanwhile, I will also take a look on this issue.

**Comment by ukby1234** [comment]
I have pushed a fix onto the development branch. Please test if that works.

**Comment by ajs6f** [comment]
Thank you, I will do so today. To be clear, you mean the branch that is actually called "development"?

**Comment by ajs6f** [comment]
Hooray! This seems to have worked for my saving models bug. Thank you very much. I made a correction similar to the one in your fix, but for some reason I ran into other problems as detailed above. Oh, well. I have Karma deployed into Tomcat now, as desired.
