### ISSUE TITLE
"Mark as key for the class" disappeared

### ISSUE THREAD

**Issue by ffagnoni** [usc-isi-i2/Web-Karma#186]
hello,
I've recently discovered Karma and I think that it is gorgeous!

From your wiky seems that createing an uri using the command "Mark as key for the class" is pretty straightforward:
![mark-as-key](https://cloud.githubusercontent.com/assets/12052597/7255317/b55b9402-e848-11e4-8861-8fa7a2e42137.png)

However seems to me that this useful function is no longer available (or at least I can't find it).
I can mark a parameter as URI, but then I can't find how to assign that propriety at the same time also to a property of class:
![cattura](https://cloud.githubusercontent.com/assets/12052597/7255475/d88d8196-e849-11e4-93c9-c226ae1862bf.PNG)

I honestly believe that those features have changed position in one of the lastes updates, could you please update the wiky?

Regards,
Francesco

EDIT:

I've just noticed that someone have already pointed out the same issue, and  the szeke's response was:

    We removed "mark as key" as most users want to customize the URIs for their classes. The "workaround" for this is to define a PyTransform on the column you want to use as the "key", and then you have the opportunity to customize it. Then map the new column as the "uri of class"
    
    Apologies if this caused you inconveniences. When we upgraded the code to be more compliant with R2RML we removed this feature, which is not directly supported in R2RML.

I understand that most of the users what to customize the URIs of their classes, but then you have to add a new column to your input file filled in some fancy way......  seems to me that in this way you lose the possibility to use Karma to directly process 3 star data an transform them in 4 or 5 star. Maybe I'm loosing something ...

**Comment by dkapoor** [comment]
Karma allows you to create the new columns using its UI, so you still use Karma to transform your data.
You can click on the column, and then from the dropdown, click on PyTransform. A dialog opens up. There you can define your python function to customize the uri (or leave as it to create a copy of the column), enter a new Column name and then save. Now you can model this as a URI of a class.
