### ISSUE TITLE
Want to ignore lower-level columns

### ISSUE THREAD

**Issue by ErikLeeNV** [usc-isi-i2/Web-Karma#187]
Hi there!  I wasn't sure where I should go with this question, so please tell me if I'm in the wrong place.

I'm trying to figure out how to get Karma to ignore lower-level hierarchical information in order for me to work on higher-level information.  I'm attaching an image of part of a structured document.
![data hierarchy exp](https://cloud.githubusercontent.com/assets/11524828/7264085/84136034-e83c-11e4-8b84-0b78ddf2fa20.png)

I want to set semantics for the acqinfo column, but I don't get a Set Semantic Type option for that column.  I only get the Set Semantic Type for the lower-level elements (id, p, and head).  I tried making the lower-level columns invisible in the Organize Columns option for the document, but that also made the acqinfo column invisible.

Is there a way I can get Karma to ignore the lower-level columns so I can work with the acqinfo column?

Thanks!
-Erik

**Comment by szeke** [comment]
Only the lowest level columns have data, so Karma can only map the lowest level columns.

Can you give more details on why you are trying to model the intermediate columns?

**Comment by ErikLeeNV** [comment]
Hi there, Pedro!

I'm actually working on a translation of some records that are in the EAD
metadata scheme to the Europeana Data Model.  What I'm doing now is taking
the tags in EAD and figuring out some mappings.  So I'm not really
interested in the data itself for this specific record, what I want to do
is model the actual structure suing this record as a guide so I can apply
it to other records.

I hope that makes sense.  Let me know if you have any questions!

-Erik

**Comment by ErikLeeNV** [comment]
UPDATE: After doing some more work with it, I would love the ability to
rename the classes in Karma to match the tags/field names being used in the
EAD scheme I'm using.  I think that would solve the problem I'm having
where I want to keep the tag names, which Karma uses as the names of
columns.

For instance, there is a wrapper tag in EAD titled "EAD."  It is used to
denote a finding aid, which is a provided CHO in EDM.  So if I could say
that ProvidedCHO1 is named "EAD," then that would allow me to keep the tags
I need while building the model.  Does that make sense?

**Comment by szeke** [comment]
Sounds like you would like to redefine the URIs for the classes in
properties in the ontology to match the names you want. Correct?

This would mean defining a new ontology. If you create the new ontology
before you use Karma you would get what you want. I understand this is not
a good solution, and this would be weird in the RdF world, where you are
supposed to use the existing ontologies.

If you are generating JSON-LD, you can rename the classes and properties in
the context file. If you click in a class in Karma and do export JSON, you
will be prompted to generate a context from the model. Say yes, and then
edit the context to contain the names you want. Next time you generate JSON
you can use the custom context file and get what you want.

Pedro
