### ISSUE TITLE
 language tag

### ISSUE THREAD

**Issue by ffagnoni** [usc-isi-i2/Web-Karma#189]
I can't find how to set a language tag (eg: @en, @it ...) in a karma transformation. Is that possible?

**Comment by szeke** [comment]
Unfortunately there is no way to do it in the current system. We can probably do it very soon if it is the same language tag for every row.

**Comment by stewolff** [comment]
What about this feature? It would be very helpful.

**Comment by dkapoor** [comment]
@ffagnoni: We have added language tag handling for RDF generation. You can select the language when setting the Semantic Types and adding Literals. 
This feature is available in the development branch that you could checkout and let us know your feedback or any issues you find.
We will soon add them to JSON-LD output as well.
Thank you.
