### ISSUE TITLE
Confused about your release process

### ISSUE THREAD

**Issue by Jimflip** [usc-isi-i2/Web-Karma#193]
In twitter you say your on  v2.037 in github  v2.030.4
I'm guessing your versioning is out of sync, I see a lot of commits on development branch.

So can you confirm how I should check out the latest stable version please.

**Comment by dkapoor** [comment]
v2.037 is the latest version. The master branch is the stable release branch and you should use  that.

**Comment by Jimflip** [comment]
Hi

Not sure this really answers my question.
It would be very useful if you did releases, or even just tags.
Pointing to master isn't useful, while we could take the hash of the current master it kinda defats the point of using version numbers.

Thanks.

**Comment by dkapoor** [comment]
Thats a good point. We will tag or do releases for our future versions.

Thanks
Dipsy
