### ISSUE TITLE
karma start fail - cannot find pom at http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/

### ISSUE THREAD

**Issue by haiqingli** [usc-isi-i2/Web-Karma#194]
follow the vivo-vagrant instruction to install and start karma. Karma cannot start because two poms cannot be found on http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/
I checked http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/, there is no karma-common and commands-include

Here is the log.

Thanks

vagrant@precise64:~/provision$ ./karma.sh start
Starting Karma
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building karma-web 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> jetty-maven-plugin:9.0.5.v20130815:run (default-cli) @ karma-web >>>
Downloading: http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom
Downloading: http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/edu/isi/commands-include/0.0.1-SNAPSHOT/commands-include-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.237s
[INFO] Finished at: Tue Jun 23 02:03:56 EDT 2015
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project karma-web: Could not resolve dependencies for project edu.isi:karma-web:war:0.0.1-SNAPSHOT: Failed to collect dependencies for [org.apache.commons:commons-lang3:jar:3.1 (compile), de.micromata.jak:JavaAPIforKml:jar:2.2.0 (compile), edu.isi:karma-common:jar:0.0.1-SNAPSHOT (compile), edu.isi:commands-include:pom:0.0.1-SNAPSHOT (compile), org.eclipse.jetty:jetty-server:jar:9.0.5.v20130815 (compile), javax.servlet:javax.servlet-api:jar:3.0.1 (provided), org.powermock:powermock-module-junit4:jar:1.5.2 (test), org.powermock:powermock-api-mockito:jar:1.5.2 (test), junit:junit:jar:4.11 (test)]: Failed to read artifact descriptor for edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Could not transfer artifact edu.isi:karma-common:pom:0.0.1-SNAPSHOT from/to colo-vm41 (http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/): Failed to transfer file: http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local//edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom. Return code is: 409 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jasonslepicka** [comment]
I tried following the instructions https://github.com/lawlesst/vivo-vagrant and I wasn't able to recreate the problem.  It looks like Karma didn't get installed into your local maven repository though. Can you try running mvn clean install from /home/vagrant/karma  and then running karma.sh start (as the vagrant user, not root (don't use sudo))?
