### ISSUE TITLE
Add Inverse Properties to the R2RML model

### ISSUE THREAD

**Issue by Nadzy** [usc-isi-i2/Web-Karma#198]
Hi!
I would like to know if it is possible to create a R2RML model that create Inverse properties.
Usually I generate R2RML model with Karma 2.0.24 and then I use them with Karma Offline to genertate triples.

thank you for your availability. :)

**Comment by szeke** [comment]
You can add the inverse properties in the model and karma will output the triples. There is currently no way to automatically generate the inverse properties.

**Comment by Nadzy** [comment]
I tried...but unfortunately the screen remains gray with the load icon and nothing happens!

**Comment by dkapoor** [comment]
That could be a UI bug. Can you try again with the latest Karma version. If it still happens, can you send your karma home folder and a sample of your data.
