### ISSUE TITLE
[Help] Link discovery and datafusion

### ISSUE THREAD

**Issue by tgoprince** [usc-isi-i2/Web-Karma#200]
Does Web Karma provides support for link discovery and data fusion? 

On the published papers I have seen some screenshots (as in the following picture), but I could not access the functionality through the tool. 

<img width="488" alt="screen shot 2015-09-14 at 09 43 49" src="https://cloud.githubusercontent.com/assets/2519935/9849919/945cfad0-5ac5-11e5-8592-21c7700dafcd.png">

Thanks in advance.

**Comment by caknoblock** [comment]
We are working on this, but we do not have a general tool that we have released yet.  The screen shot is based on a specific interface that we built for the Smithsonian.  I expect we will have something we can release within 6 months to a year.
Craig
