### ISSUE TITLE
problems appying existing model created with a different version of Karma

### ISSUE THREAD

**Issue by Nadzy** [usc-isi-i2/Web-Karma#203]
HI,
I'm trying to apply models created with a more old version of Karma to the same DB table on which they have been created (i don't remember the Karma version used to create that model), but sometimes karma crashes and sometimes communicates a no-compatibility mistake.
i'm actually using Karma version v2.024.

there is any tools to fit models created with an old Karma version to one most recent?

Thank you.

**Comment by dkapoor** [comment]
Can you send us your karma home folder, the data and the model. We can try and see how best we can handle it.  Thanks.
