### ISSUE TITLE
OfflineRDFGenerator - Batch mode on Windows

### ISSUE THREAD

**Issue by johnguerson** [usc-isi-i2/Web-Karma#204]
Hey guys,

I crossed against an issue when I tried to generate an RDF automatically using batch mode on windows. I have both csv file and r2rml model (*.ttl) working fine through the web interface. Here is the the command I am running. 

C:\Karma\karma-offline>
mvn exec:java -Dexec.mainClass="edu.isi.karma.rdf.OfflineRdfGenerator" -Dexec.args="-sourcetype CSV -filepath \"person.csv\" -delimiter SEMICOLON -textqualifier '\\\"' -headerindex 1 -dataindex 2 -modelfilepath \"person.csv-model.ttl\" -sourcename person -outputfile person-rdf.n3" -Dexec.classpathScope=compile

I checked and the csv rows have the same number of columns as the header. I followed the example on the wiki page but still could not get it running (My csv file is separated by semicolons: ";" and I tested with only two rows). Am I missing something? I would send you the files but github don't let me...

By the way, congratulations for the awesome work you have been doing.

![image](https://cloud.githubusercontent.com/assets/8644397/10867168/436af0c8-803b-11e5-9c16-2c0bf6461be8.png)

**Comment by dkapoor** [comment]
You should set the delimter to be ; and not SEMICOLON.
``
mvn exec:java -Dexec.mainClass="edu.isi.karma.rdf.OfflineRdfGenerator" -Dexec.args="-sourcetype CSV -filepath \"person.csv\" -delimiter ; -textqualifier '\\"' -headerindex 1 -dataindex 2 -modelfilepath \"person.csv-model.ttl\" -sourcename person -outputfile person-rdf.n3" -Dexec.classpathScope=compile
'
``
