### ISSUE TITLE
Is possible invoke the creation of the R2RML from java api?

### ISSUE THREAD

**Issue by p4535992** [usc-isi-i2/Web-Karma#206]
Hi,i want to know if the construction of the mapping R2RML is only possible by graphical interface with the server or if you can get it from java api. 
I apologize if this part is described at some point in the tutorial, but I could not find it.

In this sense, I need to accomplish a function like this:
NOTE: this is a pseudo code.

``` javascript
ModelWebKarma r2rml = new ModelWebkarma(Connection connection,String nameOfTable);:
r2rml.setSemanticType(.....);
r2rml.workSheetProperties(......);
File turtleR2RML  = r2rml.getModel();
```

If this were not planned it, I would like to pull this request as an enchantement of the project.
Ty for this project.

**Comment by dkapoor** [comment]
See the Batch Mode for RDF, JSON-LD Generation on the wiki:https://github.com/usc-isi-i2/Web-Karma/wiki/Batch-Mode. We have a command line tool and a JAVA API Available: https://github.com/usc-isi-i2/Web-Karma/wiki/Batch-Mode-for-JSON-LD-Generation#genericrdfgenerator

**Comment by p4535992** [comment]
Hello sorry to bother you again, perhaps i have not explained myself well or I
did not understand your answer.
The documentation that you've linked to me, I had already consulted and
from that I have created the functions for generate triple from databases or
file, but from what I gather, the template file format turtle (.ttl) for
that specific file or table of the database it's already been previously
created and is used as input argument on the constructor of the object
'R2RMLMappingIdentifier'.

For now I create template files R2RML (ie files turtle in question), with the
graphic interface of Karma, through various operations such as the choice of
ontologies to be used and the setting of the semantic types for each object
json or column of the table in question.

All these operations of choice for the creation of the model file format
turtle, are feasible directly from Java code?

In the code that follows i have highlights the file in question, i want to
create from java code:







*GenericRDFGenerator rdfGenerator = new
GenericRDFGenerator("DEFAULT_TEST");         R2RMLMappingIdentifier
modelIdentifier = new R2RMLMappingIdentifier(
"people-model","/files/models/people-model.ttl");rdfGenerator.addModel(modelIdentifier);........................RDFGeneratorRequest
request = new
RDFGeneratorRequest("people-model","files/data/people.json");request.setInputFile(new
File(*


*"files/data/people.json".toURI()));.........................rdfGenerator.generateRDF(request);SystemLog.message("Generated
JSON-LD: " + sw.toString());*

2015-11-17 18:52 GMT+01:00 dkapoor <notifications@github.com>:

**Comment by dkapoor** [comment]
No, generation of the ttl file is not exposed as a Java API. It needs to be created using the Karma GUI.

**Comment by p4535992** [comment]
Ok then I try to create my own code for this purpose, however I would recommend as a possible additional function for the project.
Thanks again for the clarification.

**Comment by szeke** [comment]
This is in our wish list, but not something that we plan to do soon. Our plan is to provide something like a python binding to build models. There is a Web API, which the GUI uses, but it would be very inconvenient to use. 

What is the use case?

**Comment by p4535992** [comment]
Hello, then the use scenario is a bit strange, I have a zip file with a many csv file and a database with many tables, with different textures and patterns and i have to convert them to triples in format rdf or turtle, for a future storage in a sesame server.
I have already prepared the mechanism for the generation of the triples from the files or the connection to the database, for this karma helped me a lot.

The only thing is that the "customer" for each file and table requires a specific mix of ontologies and links between them, the point is use public ontologies for enable a integration with the 'customer' personal ontology , to make this karma is very accurate and simple to use by graphical interface.
Now the customer often changes his mind about his ontology, and I must retouch all the models turtle files i have already created, but if I create an automatic mechanism for them in theory, i should save a lot of time :).
I hope I have clarified the use scenario where I am. 
Thanks for asking, best regards.

**Comment by szeke** [comment]
This is a good use case, and it is a tough one. I would approach this with an API to edit the command histories in Karma, which are JSON files. For example, to change the class of a node one would need to find the command that defines the URI and change the class. Would you have time to work on this? We can help, but don't have time to write all the code and debug it.

Do you have concrete use cases about the kinds of edits that you want to do? If it is a small number, it may be doable.

BTW, one recent addition to Karma is an API to export and read just the command history, instead of the whole R2RML model, this would be the starting point.

**Comment by p4535992** [comment]
Hello, is not high on my priorities, but in fact I'm already working on a function that create / modify / read the WorkSheetHistory or directly from files turtle or jetty server.
But I must have missed the API that you mentioned, you can provide a link to the code?
As soon as I have something ready and not too repugnant, i let you know.

**Comment by dkapoor** [comment]
From the UI, you can click on "Commands" and then click on "Export". This
exports the Command History instead of the whole R2RML model. This can then
be applied using the Apply R2RML Model from the UI and then publishing it
generates the whole R2RML.

Comand to export: ExportOrDeleteHistoryCommand

**Comment by p4535992** [comment]
For anyone interested in helping me with this issue, I have started to deposit the code at this address https://github.com/p4535992/karma-modelSupport

**Comment by p4535992** [comment]
Hi, sorry to trouble you, i need a little help for the code i try to make:
**Question 1:** all the inital information of a R2RML file like these: 
```text
_:node19pn5vcthx1 a km-dev:R2RMLMapping ;
km-dev:sourceName "infodocument_2015_09_18" ;
km-dev:modelPublicationTime "1436370842550"^^xsd:long ;
km-dev:modelVersion "1.7" ;
km-dev:hasInputColumns "[[{\"columnName\":\"url\"}],[{\"columnName\":\"identifier\"}],[{\"columnName\":\"name_location\"}]]" ;
km-dev:hasOutputColumns "[[{\"columnName\":\"url\"}],[{\"columnName\":\"identifier\"}],[{\"columnName\":\"name_location\"}]]" ;
km-dev:hasModelLabel "infodocument_2015_09_18" ;
km-dev:hasBaseURI "http://purl.org/goodrelations/v1#" ;
```
I can get all the information from a KR2RMLMapping, but i wonder if i miss some class where all these information are already stored after i generate the KR2RMLMapping like a "kmdev" class.
** Question 2:**  The part of the code in Web-karma for generate the id of the blank node, used in the R2RML file e.g. "_:node19pn5vcthx1" where is created the "19pn5vcthx1"?
Same thing for publication time, where is the part of the code who generate the publication time e.g. "1436370842550"?
I know that these are pieces of code very easy to replicate, but I would like to use all the code i can from Web-Karma, the problem is simply that , I am not able to find them in the project XD.
Ty in advance.

**Comment by p4535992** [comment]
Sorry trouble you again, i have two new question on the code:
**Question 1**: if i set a new Json Array WorkSheetHistory on the KR2RMLMapping when i use the new mapping all the TriplesMap modified are generated in automatic or i need to update every TriplesMap on the KR2RMLMapping?
**Question 2**: I'm ready to try to write the KR2RMLMapping , but what is the right java class to use for this?
Ty in advance.
