### ISSUE TITLE
Cannot access Karma with vagrant

### ISSUE THREAD

**Issue by yayamamo** [usc-isi-i2/Web-Karma#211]
I took the steps described in [this page](https://github.com/usc-isi-i2/Web-Karma/wiki/Installation%3A-Virtual-Box), and confirmed that the message like "default: Running: /var/folders/..." has been shown in the terminal.
However, I cannot access Karma via web browsers such as Safari, Firefox, Edge, and Chrome.
I tested on Mac OS X 10.10.5 and Windows 10.

**Comment by saggu** [comment]
Hi, a fix to this issue has been pushed, please get the latest code and try again.
Thanks
