### ISSUE TITLE
reconciliation

### ISSUE THREAD

**Issue by frdo** [usc-isi-i2/Web-Karma#214]
Hi, how can i use the data reconciliation in karma? Is there any tutorial?

**Comment by caknoblock** [comment]
We are still working on that capability and will hopefully be making something available as soon as possible.
Craig

**Comment by frdo** [comment]
Ok, thank you so much.

**Comment by lechatpito** [comment]
Hi Craig, is there any progress on reconciliation in Karma? I find it a common case where column values represent resources that should be looked up in a list of entities. Something simple like the ability to pass a Python dict that points to resources would be already quite useful.

**Comment by szeke** [comment]
The dict idea is possible to do today with a pytransform as long as the dict is less than a few thousand entries

**Comment by lechatpito** [comment]
OK, thank you for your answers.
