### ISSUE TITLE
colo-vm41 server down again?

### ISSUE THREAD

**Issue by michaele4321** [usc-isi-i2/Web-Karma#216]
When I try and start karma-web for the first time I am getting warnings 

`[WARNING] Could not transfer metadata edu.isi:import-xml:0.0.1-SNAPSHOT/maven-metadata.xml from/to colo-vm41 (http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/): Connection reset`

It appears that http://colo-vm41.isi.edu:8081/ is down?

After a lot of retry attempts, Jetty eventually starts but I'm not sure if there is anything important that should have loaded from colo-vm41

**Comment by dkapoor** [comment]
http://colo-vm41.isi.edu:8081/ is actually up. Can you run a mvn clean install again.
If it gives you the same error, it could be that you have a firewall setting that is prohibiting connecting to port 8081

**Comment by michaele4321** [comment]
My apologies. It is a corporate firewall problem with connecting on port 8081.

Sorry for the bad ticket.

**Comment by dkapoor** [comment]
We now also have our repository hosted on port 80. So you could get the latest code from development branch, and they now point to  http://colo-vm41.isi.edu/ instead of  http://colo-vm41.isi.edu:8081/
