### ISSUE TITLE
display rdfs:label in property & class list

### ISSUE THREAD

**Issue by wdduncan** [usc-isi-i2/Web-Karma#217]
This is just a suggestion:
It would be helpful if Karma provided the option of view the rdfs:labels of the classes or properties when constructing the models. I happen to work with a number of ontologies in which the URIs are numbers. Being able to see the labels in Karma would make finding the classes and labels easier.

Thanks,
Bill

**Comment by szeke** [comment]
Good suggestion, we've seen this problem before with biomedical ontologies.

Would it work if there is a toggle to show either label or property name as the main display with tooltip showing the other?

**Comment by wdduncan** [comment]
Such a toggle feature would very useful. Most of the time I can just use
the label for a term, but sometimes I need to check the URIs (e.g., when
two terms have different URIs but the same label).

Bill

**Comment by ddooley** [comment]
This would be great.  OBOFoundry ontologies are all encouraged to use their numeric codes for ids, and language variants for labels (esp. @en, @fr etc. to achieve multilingual naming) often the name for a concept is debated initially.  I think this is a wise approach for ontologies generally.
  
 Regards,
  
 Damion Dooley
 (Scientific Programmer for BC Centre for Disease Control)
  
  
  

----------------------------------------

**Comment by dkapoor** [comment]
Karma now renders rdfs:label in addition to the URIs. From Settings `->` Display rdfs:label, you can change what gets displayed first, the URI or the label
