### ISSUE TITLE
use annotation propert to relate individual to class

### ISSUE THREAD

**Issue by wdduncan** [usc-isi-i2/Web-Karma#218]
I have a situation in which I need to relate an individual to a class. This particular situation involves relating a monoclonal antibody offering to the vendor that sells it. For example, the offering "AB_10001472" is sold by the company Novus. If you're curious, information about this offering can be seen here: http://antibodyregistry.org/search?q=AB_10001472

In a non-biological context, the situation is analogous to that between a particular automobile manufacturer and class/model of automobiles it manufactures, e.g.: Ford manufactures Mustang
You have a particular entity and a class of things that the particular entity sells/manufactures.

I have chosen to represent this by using an annotation property ("sells") to relate the vendor to the monoclonal antibody offering. In functional syntax, the OWL looks like so:

AnnotationPropertyAssertion(:sells :Novus :AB_10001472)

I have a large spreadsheet of data containing the vendors and their offerings, e.g.:

Vender Offering
--------- ----------
Novus  AB_10001472
Novus AB_10001578
...

Using Karma, is it possible to model the "Vendor" and "Offering" columns in the manner described above? I haven't been able to figure out how to ...

Thanks,
Bill

**Comment by dkapoor** [comment]
You could do the above with Karma.
Set the Semantic Type of Vendor as "uri of Organization" and the Semantic Type of Offering and "uri of Product". Then add an Outgoing link from Organization to Vendor and select the property as "sells"

It outputs the following triples:
```
<http://antibodyregistry.org/schema/Novus> <http://schema.org/sells> <http://antibodyregistry.org/schema/AB_10001472> .
<http://antibodyregistry.org/schema/Novus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Organization> .
<http://antibodyregistry.org/schema/AB_10001472> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Product> .

<http://antibodyregistry.org/schema/Novus> <http://schema.org/sells> <http://antibodyregistry.org/schema/AB_10001578> .
<http://antibodyregistry.org/schema/Novus> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Organization> .
<http://antibodyregistry.org/schema/AB_10001578> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Product> .
```

**Comment by wdduncan** [comment]
No. The output is not correct. Offerings are not a rdf:type of Product.
Offerings are a type (or class). The appropriate relationship between
Product and Offering is rdfs:subCalssOf. The rdf:type relation holds
between particulars and classes.

Think of the automobile manufacturer example. Mustang is a type (or class)
of automobile that Ford produces. Similarly, an offering is a type of
monoclonal antibody product.

Bill

**Comment by szeke** [comment]
I think this is possible. You need to include the rdf.rdf ontology in the preloaded ontologgies so that the rdf:Class is available as a class. Please add the desired turtle or ntriples in the discussion board and we will test that this can be done.

**Comment by wdduncan** [comment]
Hi Pedro,
  Sorry, I'm not sure what you mean by "rdf ontology". The ontology is save
in rdf/xml syntax. However, neither rdfs:Class nor owl:Class is not
provided as a class to choose from. Can you please clarify?

Thanks,
Bill

**Comment by szeke** [comment]
Attached is an example of a preloaded-ontologies that includes rdf-schema.ttl, which defines rdfs:Class and friends. 
[preloaded-ontologies.zip](https://github.com/usc-isi-i2/Web-Karma/files/182676/preloaded-ontologies.zip)

You can build models such as the following:
![2016-03-21_09-15-34](https://cloud.githubusercontent.com/assets/1074599/13925691/87ca4cee-ef46-11e5-8204-829b5bbf2dcb.png)

One caveat, you have to build it using the "Set Semantic Type" command from the menu. There is a bug in the "Suggest" feature when changing something to be a URI. I will file a separate issue for it.

It produces JSON such as
```
<http://localhost:8080/source/October2_1964> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> .
<http://localhost:8080/source/October2_1964> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://localhost:8080/source/Yesterday> .
<http://localhost:8080/source/Yesterday> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> .
```

**Comment by wdduncan** [comment]
Hi Pedro,
  Thanks for the example. Did you build rdf-shema.ttl in a text editor? The
reason I ask is that you have the following lines in your file:

rdfs:Resource a rdfs:Class ;
rdfs:isDefinedBy <http://www.w3.org/2000/01/rdf-schema#> ;
rdfs:label "Resource" ;
rdfs:comment "The class resource, everything." .

rdfs:Class a rdfs:Class ;
rdfs:isDefinedBy <http://www.w3.org/2000/01/rdf-schema#> ;
rdfs:label "Class" ;
rdfs:comment "The class of classes." ;
rdfs:subClassOf rdfs:Resource .

When I build a file in Protege and save using Turtle syntax those lines
don't appear. Rather, a class is defined as an instance of owl:class. E.g.:

<http://vivo.roswellpark.org/research-areas/research-area_0000001> rdf:type
owl:Class

When I loaded this ontology (attached), I was not presented with rdfs:class
as an option (which makes sense). I do most of my ontology editing in
Protege, and I typically save the ontology in rdf/xml syntax. Do you happen
to know how to get Protege to save an ontology with the rdfs:Class type? Or
do I need to add it manually to the ontology?

Thanks,
Bill

**Comment by szeke** [comment]
I downloaded the XML version of rdf-schema from the web, and used an rdf
converter to convert it to turtle. Many such services on the web, google
"ref converter"

p

**Comment by wdduncan** [comment]
Hi Pedro,

Thanks for responding. My usual workflow involves using Protege to build
the classes and axioms. So, I prefer not to have to go through the process
of using an rdf converter.

For those who (like me) work mainly in Protege, I found another work
around. In the Protege class editor, add the class "
http://www.w3.org/2002/07/owl#Class" as a subclass of owl:Thing. This
allows you to select the semantic type "owl:Class" for a column in the
spreadsheet. You can then connect to this column using an outgoing link
with the appropriate annotation.

I realize the use case I presented is not one that is likely to present
itself very often. However, is it possible to have owl:Class as one default
options for the semantic type?

Thanks,
Bill

**Comment by szeke** [comment]
Using Protege is fine. Regarding owl:Class appearing in the semantic type dialog, the properties that appear in the semantic type dialog are the data properties, and regular rdf:Property, object properties do not appear in the semantic type dialog. If you have the URIs or properties in cells in the worksheet, you will need to model them as URI of rdf:Property, and then use the advanced options to specialize rdf:Property.
