### ISSUE TITLE
data/object properties showing up as annotations

### ISSUE THREAD

**Issue by wdduncan** [usc-isi-i2/Web-Karma#219]
I am modeling some patient data from a spreadsheet with following columns:

patient id birth date   
------------ ---------------
 10001     1980-01-01
 10002      1975-12-31
...

I the ontology I have defined a data property "birth date" that has a xsd:dateTime as its range. 
To model this in Karma, I set the semantic type for patient id as the uri for my patient class, and choose "Property of Class" for the birth date column. I then choose my data property "birth date" for property, and the class to be the patient class. I then publish the RDF.

However, when I load the turtle file in to Protege the birth date data property is being changed into an annotation property. Is this a bug of Protege? Or Karma?

Thanks,
Bill

**Comment by dkapoor** [comment]
It seems this is a bug in Protege. http://stackoverflow.com/questions/15988321/owl-objectproperty-loading-as-annotation-in-prot%C3%A9g%C3%A9
You can try the solution mentioned in the post.
