### ISSUE TITLE
class information in cloumns

### ISSUE THREAD

**Issue by wdduncan** [usc-isi-i2/Web-Karma#220]
I often have to model information in which class information is present as column data. The best way to explain this by example. Suppose I have a spreadsheet of dental patients who have filling that is structured like this:

patient tooth number
-------- ------------------
10001  1
10001  2
10002  1
10002  5
10002  2
....

In this spreadsheet, tooth number denotes the type of tooth. Tooth 1 is an upper right third molar (a wisdom tooth). Tooth 2 is an upper right second molar. Tooth 5 is an upper right canine. And so on ...

Typically what I do in this situation is I create an uri for each tooth, set that uri to be an instance of the type of tooth associated with the tooth number, and relate the instance of the tooth to the patient. Using pseudo code, the triples for the above table look something like this:

# declare individual patients
:patient_10001 rdf:type :Patient_Class
:patient_10002 rdf:type :Patient_Class

# declare individual teeth
:patient_10001/tooth_1 rdf:type :Tooth_1_Class
:patient_10001/tooth_2 rdf:type :Tooth_2_Class
:patient_10002/tooth_1 rdf:type :Tooth_1_Class
:patient_10002/tooth_2 rdf:type :Tooth_2_Class
:patient_10002/tooth_5 rdf:type :Tooth_5_Class

# relate tooth instances to patient instances
:patient_10001/tooth_1 :part_of :patient_10001
:patient_10001/tooth_2 :part_of :patient_10001
:patient_10002/tooth_1 :part_of :patient_10002
:patient_10002/tooth_2 :part_of :patient_10002
:patient_10002/tooth_5 :part_of :patient_10001

In Karma, I can form the individual tooth uris by creating a pyTransformation. However, each particular tooth uri need to be an instance (rdf;type) of the type of tooth indicated in the column. How can I do this in Karma?

Bill

**Comment by taheriyan** [comment]
You can do this using the "Advanced Options" in the Set Semantic Type menu. You can use pyTransformation to create URIs for both tooth instances and their type. Suppose that you have two new columns after the transformation:

:patient_10001/tooth_1          :Tooth_1_Class
:patient_10001/tooth_2          :Tooth_2_Class

You first assign the semantic type :Tooth to the first column (uri of :Tooth) to say that the values in the first column are :Tooth instances. Now, you can set the semantic type for the second column. In the menu, click on the Advanced Options and select "specific class for node" and select "Tooth1", which has already been assigned to the first column. Publish RDF and take a look to the generated RDF, it will look like:

:patient_10001/tooth_1 rdf:type :Tooth
:patient_10001/tooth_1 rdf:type :Tooth_1_Class
:patient_10001/tooth_2 rdf:type :Tooth
:patient_10001/tooth_2 rdf:type :Tooth_2_Class

**Comment by wdduncan** [comment]
Thanks! Your explanations was very helpful.

Bill
