### ISSUE TITLE
automating the modeling part

### ISSUE THREAD

**Issue by omarrana** [usc-isi-i2/Web-Karma#221]
Hi,

So karma provides an option to suggest the model based on current ontology or using generated ontology.
For my data both of them fails due to unknown reason. My goal is to automize this process of modeling or create a general R2RML file which can work for all of my data.

if I create an R2RML file based on one data. 
Then there is another data file which has all the previous data for which I created R2RML  but also contains new extended data as well. R2RML based on previous data works well on it, and I just need only to create modeling for the additional data. 

However, if I have an R2RML file for a bigger data and the new file doesn't contain all of the data then Karma uses empty values for that which I don't want in my final RDF.

So my goal is to automize this process. Currently, I can think of two ways:

1- Look in the code of suggesting model based on current ontology 
2- look in the code and make karma to skip empty values if its not present.

i want suggesstion which apporach should i use or can you suggest better apporach for this?

It will be really helpful if i want to go with approach number 2-  which file i need to change. 

Thankyou so much for a great tool.

**Comment by dkapoor** [comment]
You could go with option 2.
The code that you would need to change is `edu.isi.karma.controller.history.WorksheetCommandHistoryExecutor`. The last parameter of `normalizeCommandHistoryJsonInput` controls if the empty columns should be added. Change the `executeCommand` function to pass `false` instead of the current value - `true`.
