### ISSUE TITLE
Karma Offline - Ressource not found - Error

### ISSUE THREAD

**Issue by GuenterEngelhardt** [usc-isi-i2/Web-Karma#222]
Hey folks,

I'm trying to generate some rdf with karma-offline with a postgres database. Unfortunately I get an error that the resource is not found in model. My first idea was, that I have a typo in the r2rml file, but actually everything is fine and the schema name, table name and column name is correct.

Any suggestions?

`mvn exec:java -Dexec.mainClass="edu.isi.karma.rdf.OfflineRdfGenerator" -Dexec.args=" --sourcetype DB --dbtype PostGIS --hostname 100.100.100.10 --username user --password 'pass' --portnumber 5432 --dbname postgres --tablename COMMON.PERSONS --modelfilepath /home/guenter/mappings/r2rml.ttl --outputfile /home/guenter/mappings/mapping.n3" -Dexec.classpathScope=compile`

`INFO [2016-03-21 08:48:46,853] (ServletContextParameterMap->setup->99): Karma home: /home/guenter/karma/
INFO [2016-03-21 08:48:46,858] (KarmaUserMetadata->createDirectoryForMetadata->31): Set parameter: USER_PREFERENCES_DIRECTORY -> /home/guenter/karma/user-preferences/
INFO [2016-03-21 08:48:46,862] (KarmaUserMetadata->createDirectoryForMetadata->31): Set parameter: USER_CONFIG_DIRECTORY -> /home/guenter/karma/config/
INFO [2016-03-21 08:48:46,863] (KarmaUserMetadata->createDirectoryForMetadata->31): Set parameter: USER_PYTHON_SCRIPTS_DIRECTORY -> /home/guenter/karma/python/
init: Bootstrapping class not in Py.BOOTSTRAP_TYPES[class=class org.python.core.PyStringMap]
^[ODINFO [2016-03-21 08:48:57,256] (ModelingConfiguration->loadParams->300): Load modeling.properties: /home/guenter/karma/config/modeling.properties:true
ERROR [2016-03-21 08:48:57,302] (OfflineRdfGenerator->main->156): Error occured while generating RDF!
edu.isi.karma.webserver.KarmaException: Resource not found in model for the source: COMMON.PERSONS
 at edu.isi.karma.kr2rml.mapping.WorksheetR2RMLJenaModelParser.parse(WorksheetR2RMLJenaModelParser.java:129)
        at edu.isi.karma.rdf.DatabaseTableRDFGenerator.generateRDF(DatabaseTableRDFGenerator.java:143)
        at edu.isi.karma.rdf.DatabaseTableRDFGenerator.generateRDFFromTable(DatabaseTableRDFGenerator.java:115)
        at edu.isi.karma.rdf.OfflineRdfGenerator.generateRdfFromDatabaseTable(OfflineRdfGenerator.java:418)
        at edu.isi.karma.rdf.OfflineRdfGenerator.generateRDF(OfflineRdfGenerator.java:178)
        at edu.isi.karma.rdf.OfflineRdfGenerator.generate(OfflineRdfGenerator.java:164)
        at edu.isi.karma.rdf.OfflineRdfGenerator.main(OfflineRdfGenerator.java:150)`

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://example.com/vocab#> .

<#PersonMap>
	rr:logicalTable [ rr:tableName "COMMON.PERSONS" ];
	rr:subjectMap [
		rr:template "http://example.com/data/Persons/{ID}";
		rr:class ex:MachineClass;
	];
	rr:predicateObjectMap [
		rr:predicate ex:personId;
		rr:objectMap [ 
			rr:column "ID"; 
			rr:datatype xsd:integer;
		];
	];
	rr:predicateObjectMap [
		rr:predicate ex:name;
		rr:objectMap [ 
			rr:column "NAME";
			rr:datatype xsd:string;
		];
	].
```

**Comment by dkapoor** [comment]
Can you set the dbname parameter as PostGIS and try. Thanks.

**Comment by GuenterEngelhardt** [comment]
I tried `--dbname PostGIS` but I still have exactly the same error.

**Comment by dkapoor** [comment]
Can you try applying the model `/home/guenter/mappings/r2rml.ttl` from the UI. If it works, can you send us the model.

**Comment by GuenterEngelhardt** [comment]
If I understood correctly... I used Web Karma.. Imported the database table and tried to "Apply R2RML Model -> From file". It didn't work -> "Error occured while applying history!". The R2RML file I tried to apply worked fine with other mappers.

**Comment by dkapoor** [comment]
The R2RML model file needs to be generated using the Karma UI for now to get able to run Karma in the batch mode.  We currently do not support R2RML files generated from other software.

**Comment by tholiebig** [comment]
Is there any progress in this respect? We also got stuck in trying to run the Karma mapping offline with a manual created R2RML file.
