### ISSUE TITLE
getTestResource

### ISSUE THREAD

**Issue by omarrana** [usc-isi-i2/Web-Karma#223]
hi ,
Sorry for a very basic question :
RDFGeneratorRequest request = new RDFGeneratorRequest("events-model", filename);
			request.setInputFile(new File(getTestResource(filename).toURI()));

i am getting error at getTestResource() // says function not defined. 
in which file is this function created?

Thanks

**Comment by dkapoor** [comment]
It is defined in  edu.isi.karma.rdf.TestJSONRDFGenerator. You could give the full path to your file and then you dont need to use the getTestResource method.
