### ISSUE TITLE
Change Link to "uri of Class" doesn't generate correct RDF

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/Web-Karma#224]
When I create a model using "Suggest" the semantic type is by default "name of X". I can click on name and change it to "uri of Class". Karma accepts it and creates a model that looks like this, which looks correct:
![2016-03-21_09-15-34](https://cloud.githubusercontent.com/assets/1074599/13926044/d626cf10-ef47-11e5-9def-20a1b11f147e.png)
However, the generated JSON-LD is missing the URIs, it has the "a", but not "uri":
```
{
    "a": "http://www.w3.org/2000/01/rdf-schema#Class",
    "@context": "http://localhost:8080/publish/JSON/WSP1WS3024-www_1919a4_com_extractions_test_filtered_jl-context.json",
    "subClassOf": {"a": "http://www.w3.org/2000/01/rdf-schema#Class"}
}
```

When I create the same model using the "Set Semantic Type" command, the model looks the same, and the JSON-LD is correct:
```
{
    "a": "http://www.w3.org/2000/01/rdf-schema#Class",
    "uri": "http://localhost:8080/source/October2_1964",
    "@context": "http://localhost:8080/publish/JSON/WSP1WS5-www_1919a4_com_extractions_test_filtered_jl-context.json",
    "subClassOf": {
        "a": "http://www.w3.org/2000/01/rdf-schema#Class",
        "uri": "http://localhost:8080/source/Yesterday"
    }
}
```

**Comment by dkapoor** [comment]
Have fixed this issue. We were calling SetSemanticType instead of the SetMetaProperty Command. The function used to check that the label is "uri". However we have the new UI show it as "Uri of Class" which is why it didnt work. Have fixed it to check on uri being classLink instead of label being uri
