### ISSUE TITLE
Suggest Semantic Type doesn't allow creation of duplicate classes

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/Web-Karma#227]
For example, I cannot create the following model with the suggest feature:
![2016-03-21_10-07-22](https://cloud.githubusercontent.com/assets/1074599/13927233/2b1a0f50-ef4d-11e5-8d2a-3213ef908f58.png)

After I add the first name of Offer1, I click suggest on the 3rd column. When I click the third class, I get the following menu, which has `schema:Offer1 (add)` instead of `schema:Offer2 (add)`
![2016-03-21_10-09-14](https://cloud.githubusercontent.com/assets/1074599/13927319/8930d564-ef4e-11e5-871e-1e5f5f86ea3c.png)

**Comment by dkapoor** [comment]
Have fixed this issue. We were caching the classes in the "All" tab and that was causing this issue. We now reload them after a semantic update.
