### ISSUE TITLE
timeout from http://colo-vm41.isi.edu  => source code installation error

### ISSUE THREAD

**Issue by preinh** [usc-isi-i2/Web-Karma#228]
I'm sorry guys for report it but today I was installing from source (as I did sometimes) and I found this dependency error due timeout from that server.

```
Failed to execute goal on project karma-typer: 

Could not resolve dependencies for project edu.isi:karma-typer:jar:0.0.1-SNAPSHOT: 
Failed to collect dependencies for 

[edu.isi:karma-util:jar:0.0.1-SNAPSHOT (compile), 
log4j:log4j:jar:1.2.13 (compile), 
org.slf4j:slf4j-api:jar:1.6.0 (compile), 
org.slf4j:slf4j-log4j12:jar:1.6.0 (compile), 
com.googlecode.json-simple:json-simple:jar:1.1.1 (compile), 
org.apache.commons:commons-math3:jar:3.4-modified (compile), 
org.apache.lucene:lucene-core:jar:4.8.0 (compile), 
org.apache.lucene:lucene-queryparser:jar:4.8.0 (compile),
org.apache.lucene:lucene-analyzers-common:jar:4.8.0 (compile),
com.google.code.gson:gson:jar:2.2.2 (compile)]: 

Failed to read artifact descriptor for org.apache.commons:commons-math3:jar:3.4-modified: 
Could not transfer artifact org.apache.commons:commons-math3:pom:3.4-modified 
from/to colo-vm41 (http://colo-vm41.isi.edu/artifactory/simple/libs-release-local/): 

Connection to http://colo-vm41.isi.edu refused: Connection timed out -> [Help 1]
```

**Comment by preinh** [comment]
update:

Following issues #148 and #150 and doing a quick check to 
http://colo-vm41.isi.edu:8081/artifactory/simple/libs-release-local/ instead just to canonical 80 port, seems like the service is running. I'm not sure at the moment in which port is expected the connection. 

Due firewall constraints in many places, my suggestion is to enable the 80 port as well.

I'm not sure how is the correct approach from now with this minor inconsistency since the download trial was not made to the 8081 but to the 80 port.

**Comment by Lbookman** [comment]
@preinh I just ran into this problem. Should I change the port in the Vagrantfile?

**Comment by dkapoor** [comment]
We apologize, the service was down. We have it up again. It will be available at port 80.

**Comment by Lbookman** [comment]
@dkapoor  it's still not available

**Comment by dkapoor** [comment]
Can you try again. We just restarted it as we had another user complain he wasnt able to access it.

**Comment by Lbookman** [comment]
still not able to connect

**Comment by dkapoor** [comment]
Can you change the url in Web-Karma/pom.xml and Web-Karma/karma-mr/pom.xml for `colo-vm41` to `http://colo-vm41.isi.edu/artifactory/libs-release-local` and try. If this works, I can roll out a release with this new url.

**Comment by Lbookman** [comment]
made the changes and still get the errors below @dkapoor 

==> default: [ERROR] Failed to execute goal on project karma-typer: Could not resolve dependencies for project edu.isi:karma-typer:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.apache.commons:commons-math3:jar:3.4-modified: Failed to read artifact descriptor for org.apache.commons:commons-math3:jar:3.4-modified: Could not transfer artifact org.apache.commons:commons-math3:pom:3.4-modified from/to colo-vm41 (http://colo-vm41.isi.edu/artifactory/simple/libs-release-local/): Connect to colo-vm41.isi.edu:80 [colo-vm41.isi.edu/128.9.144.168] failed: Connection timed out -> [Help 1]
==> default: [ERROR]
==> default: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
==> default: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
==> default: [ERROR]
==> default: [ERROR] For more information about the errors and possible solutions, please read the following articles:
==> default: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
==> default: [ERROR]
==> default: [ERROR] After correcting the problems, you can resume the build with the command
==> default: [ERROR]   mvn <goals> -rf :karma-typer

**Comment by dkapoor** [comment]
Your log shows the previous url with /simple, so your pom file did not get saved correctly. Can you make sure it points to `http://colo-vm41.isi.edu/artifactory/libs-release-local`. This one does not have a `/simple` after `artifactory`

**Comment by dkapoor** [comment]
We just made a commit to master for this updated url. You can just pull and try again.

**Comment by Lbookman** [comment]
I pulled the new master and I am still getting the same errors @dkapoor

**Comment by preinh** [comment]
Sorry guys, my time zone is a bit shifted. Anyway, I just had tested again and for me seems like the service is not running again @dkapoor. As @Lbookman mentioned, I confirmed that the download is trying to be made at the new direction (without ```simple```) and at the port 80.

The error is consistent with telnet timeout at port 80 and connection refused at 8081.

I didn't find a way to re-open the issue.

**Comment by dkapoor** [comment]
@preinh: I have reopened the issue.
I am able to reproduce the problem and will resolve it soon. Sorry about all the trouble.

**Comment by dkapoor** [comment]
@preinh, @Lbookman: We have resolved the issue with the repository. Can you pull in the latest version of Karma and try again.
Thanks for your patience.

**Comment by preinh** [comment]
I just finished an install process for testing and seems that is everything ok now. Only a warning was shown (bellow) but the service could run smoothly.
```
[WARNING] The POM for org.apache.commons:commons-math3:jar:3.4-modified is missing, no dependency information available
```
Thank you so much @dkapoor .
