### ISSUE TITLE
Rdf offline generator ,

### ISSUE THREAD

**Issue by omarrana** [usc-isi-i2/Web-Karma#230]
(KR2RMLMappingColumnNameHNodeTranslator->translateColumnNameToHNodeId->146): Error retrieving column: ExternalURI , 

hi, I got this error while compiling from the api,  however the same model works in Karma GUI.
but it generated the RDF.

However, the small problem is that the URI is missing at start for e.g i got this

`<maxTransportationWeight>  
 <http://schema.org/name>  
 "maxTransportationWeight" .
`
it should be 

`<http://example.org:maxTransportationWeight>
  <http://schema.org/name>
 "maxTransportationWeight" .
`

Even though this is not high priority problem , as i can code the uri. but

Do I need to load my ontology as well to show the URI? 

My main concern is for same R2RML model , i get different RDF from KARMA GUI, and lesser RDF values from offline RDF generator by calling the API through code.

I will be really thankful if this issue could be solved,

This is my simple code :

`

               GenericRDFGenerator rdfGenerator = new                                                                                           GenericRDFGenerator(SuperSelectionManager.DEFAULT_SELECTION_TEST_NAME);

		R2RMLMappingIdentifier 	modelIdentifier = new R2RMLMappingIdentifier(
			                "my-model", new File("c://model.ttl").toURI().toURL());
		rdfGenerator.addModel(modelIdentifier);
		
		FileWriter output=new FileWriter("c://output.rdf");
		String filename = "c://Example.xml";
		StringWriter sw = new StringWriter();
		PrintWriter pw = new PrintWriter(sw);
		List<KR2RMLRDFWriter> writers = this.createBasicWriter(pw);
		RDFGeneratorRequest request = new RDFGeneratorRequest("csv", filename);
		request.setInputFile(new File(filename));
		request.setAddProvenance(false);
		request.setDataType(InputType.XML);
		request.addWriters(writers);
                rdfGenerator.generateRDF(request);
                output.write(sw.toString());
		output.close();

`

**Comment by dkapoor** [comment]
You do not need the ontology. However,  does the model generate the column using a python transformation, that uses a function that is in the `python` directory of your Karma Home folder? If it does, then you also need to initialize your karma home directory. See the `setupKarmaMetadata` method in `OfflineRdfGenerator` on how to do that.
