### ISSUE TITLE
Karma does not raise error when data rows are not matching the format expected by the r2rml mapping

### ISSUE THREAD

**Issue by bnouvel-wio** [usc-isi-i2/Web-Karma#249]
When karma is not able to read data it apparently simply silently ignore the row that are concerned and no error is returned to the user, this does not help users to identify that there data does not match the expected format it would be good if format errors could be returned to the users.

Eventually, karma reaction( ignore-silently, log, fail,.. )  to invalid data should be selectable by the user.

**Comment by rutujarane** [comment]
Old issue.
Please reopen this issue if you are still facing this problem.
Closing.
