### ISSUE TITLE
Base URI not preserved when loading model

### ISSUE THREAD

**Issue by rhao** [usc-isi-i2/Web-Karma#251]
When I load a dataset and apply R2RML Model from file, it doesn't load the correct Base URI from the model file. Instead, it has the default http://localhost:8080/source/ as the base URI.

I am working off the karma development branch from April 9th. An example of how to recreate this issue is to apply the model to the data in the american-art NPGConstituents folder: https://github.com/american-art/npg/tree/master/NPGConstituents

**Comment by dkapoor** [comment]
Rebecca,

The model file does not have the base uri set. This is what is there in
your model:

km-dev:hasBaseURI "" ;

Can you use karma to set the base uri and republish the model and then try
again.
When you set it, the model will gave something like:

km-dev:hasBaseURI "http://karma.isi.edu/kmdev" ;

Thanks
Dipsy
