### ISSUE TITLE
Alert needed when go back

### ISSUE THREAD

**Issue by YuhaoZhu** [usc-isi-i2/Web-Karma#254]
When working on files with large columns, if you scroll too fast to the left, browser will have a great change go back to previous webpage and lose all your work. Better have alert when leave the karma web page.

**Comment by dkapoor** [comment]
This is a default mouse gesture for the trackpad/mouse. You could disable it. See here: http://apple.stackexchange.com/questions/21236/how-do-i-disable-chromes-two-finger-back-forward-navigation

If you do have it enabled, and you scroll past to prev page, you still do have all your work saved in your `karma home folder/models-autosave` folder. All commands are automatically saved in the background as a model in this folder that can be retrieved and then applied as an R2RML model.
