### ISSUE TITLE
Adding Literal URI

### ISSUE THREAD

**Issue by GeoffGr** [usc-isi-i2/Web-Karma#260]
When trying to add a literal URI to a second layer node (e.g., to Agent1 below):
![image](https://cloud.githubusercontent.com/assets/4147638/15591702/9d3e640c-236c-11e6-8294-fe69af70835d.png)

I receive an "error: null" message:
![image](https://cloud.githubusercontent.com/assets/4147638/15591718/b3335f60-236c-11e6-8b68-cd77acf7e262.png)

If I add other semantic types to the model, the URI literal nodes appear floating as shown here:
![image](https://cloud.githubusercontent.com/assets/4147638/15591751/dcc82e00-236c-11e6-9eaa-e2ff49f3bcaf.png)

Is this the intended use of the "Is URI?" checkbox? (Note the same behavior happens when defining a literal value with the "Is URI?" option left unchecked.) I have the current "development" branch deployed via Vagrant.

**Comment by dkapoor** [comment]
The error occurred because in the first dialog where you are entering the literal, you are also required to select the outgoing property that will point to the Literal. The client validation was broken and was letting you continue without selecting the property. We have fixed that now, but the fix is still in the development branch.
You can avoid the issue by making sure you select the property. Thanks.

**Comment by GeoffGr** [comment]
What about the case I would like to explicitly specify the URI of the model node labeled "Agent1" in the above example (i.e., the specified URI would have "contributor" relations to each of the "Content1" instances). In this case I would not want to have this outgoing literal linked via a property but would be similar to the "uri" link which can be tied to individual data rows.

Is this not the recommended method for explicit URI specification?

**Comment by szeke** [comment]
Great question. The answer depends on what you want.

Case 1: there is one different agent for each row, i.e., the agent for content 1 is a_1, the agent for content 2 was a_2, etc. If this is the case, then define a new column using PyTrasform, call it agent_uri. In some applications you already have a column of data that contains an agent identifier. If that is not the case, then generate a unique uuid for each agent URI, using `return prefix + str(uuid.uuid1())`

Case 2: there is a single agent for all the contents. In this case, you need to do a workaround. You need to add a new column using the "Add Column" command (see below) and the model that column as the URI of your agent using the semantic type dialog.

![add-column](https://cloud.githubusercontent.com/assets/1074599/16104209/09f70460-3334-11e6-8eb9-24ba829fc1f6.png)

The thing to understand is that during RDF generation Karma uses the rows to determine how many instances of a class you want. When a node is connected to a column using a semantic type, Karma knows to make one instance for each row. When rows have the same URI, the instance will be the same.

If a class is not connected to a column using a semantic type, then Karma will make ONE instance of the class, and make it a blank node.
