### ISSUE TITLE
split characters that don't have a delimiter

### ISSUE THREAD

**Issue by wdduncan** [usc-isi-i2/Web-Karma#261]
I am needing to split a string of characters that do not have a delimiter between each character. Here is the context:

In a dental record, the surfaces of a tooth are often represented as a string of characters. For example, if a filling is placed in the mesial and occlusal surfaces on a tooth, this is often simply represented as "mo". 

I need to be able to split the string "mo" into the characters "m" and "o", so that I can assign the appropriate URIs: "m" is a type of mesial surface; "o" is a type of occlusal surface. The Karma split function does not allow me to split strings that do not have a delimiter. I can (perhaps) write some python code to do this, but I wondering if there was a way to get the built in split functionality of Karma to perform this.

Thanks,
Bill

**Comment by dkapoor** [comment]
We have extended the Split functionality and now you say `character` to split by every character.
You can checkout the development branch to use this feature for now.
