### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by GeoffGr** [usc-isi-i2/Web-Karma#262]
Should Karma be compatible with Firefox? While some features seem to work, the popup box which is expected when clicking nodes do not seem to appear. For example, when clicking title below nothing pops up:

![image](https://cloud.githubusercontent.com/assets/4147638/15865720/d1517ffe-2ca9-11e6-8130-ad9baabb281d.png)

This has been recognized on Firefox 46.0.1 with no add-ons enabled.

**Comment by dkapoor** [comment]
Karma should be compatible with Firefox, but the UI was broken in Firefox, sorry about that. We have fixed it and you can pull the latest version to get the changes. Thanks.

**Comment by GeoffGr** [comment]
I have tested this and it seems to be working now. Thanks.
