### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by gigialmo88** [usc-isi-i2/Web-Karma#263]
I am trying to run Karma per the installation instructions and after running mvn jetty:run I get the following output:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.438 s
[INFO] Finished at: 2016-06-07T19:53:47-06:00
[INFO] Final Memory: 11M/154M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project karma-web: Could not resolve dependencies for project edu.isi:karma-web:war:0.
0.1-SNAPSHOT: Failed to collect dependencies at edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Failed to read artifact descrip
tor for edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Could not transfer artifact edu.isi:karma-common:pom:0.0.1-SNAPSHOT fro
m/to KarmaRepo (http://repo.karma.isi.edu/artifactory/libs-release-local): Failed to transfer file: http://repo.karma.is
i.edu/artifactory/libs-release-local/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom. Return code is
: 409 , ReasonPhrase:Conflict. -> [Help 1]

**Comment by dkapoor** [comment]
Could you make sure that you are in the root Web-Karma folder and NOT karma-web and then run `mvn clean install` again.
If it still happens, can you paste the complete build log, run `mvn --version` and let us know the output.
Thanks.

**Comment by gigialmo88** [comment]
Yes that worked. Thank you!
