### ISSUE TITLE
Label Rendering

### ISSUE THREAD

**Issue by GeoffGr** [usc-isi-i2/Web-Karma#264]
Is there any setting in Karma to adjust how labels for classes and predicates are rendered? When using alphanumeric URIs it would be preferable to have some display precedence logic to show prefLabels, namespace prefixed prefLabels, etc., similar to how they are rendered in Protege.

**Comment by szeke** [comment]
We will be working on this issue next. It will take a few weeks due to
vacations of team members.

P

**Comment by GeoffGr** [comment]
Thanks for considering this feature. I think this will be helpful particularly for projects with an evolving ontology where human readable labels are not stable and URIs are instead alphanumeric.

One recommendation is that this change would both be rendered as node labels in the model and also available when searching for properties or classes when adding links in the model.

**Comment by GeoffGr** [comment]
Hi,

Is there any update on the status of this feature?

Thanks.

**Comment by szeke** [comment]
We are working on it right now, should be done in a couple of days

p

**Comment by dkapoor** [comment]
Karma now renders rdfs:label in addition to the URIs. From Settings `->` Display rdfs:label, you can change what gets displayed first, the URI or the label
