### ISSUE TITLE
Loading Turtle-formatted ontologies from Protege does not work

### ISSUE THREAD

**Issue by GullyAPCBurns** [usc-isi-i2/Web-Karma#267]
When we save a file from Protege in their 'Turtle format', it generates an error in the Karma project.

The error shows up on the console as this message:

ERROR [2016-06-28 11:22:26,790] (RDFDefaultErrorHandler->fatalError->44): (line 2 column 1): Content is not allowed in prolog.

If we save the same file as RDF/XML, the load procedure works perfectly (so this is not a high-priority problem, just FYI).

**Comment by szeke** [comment]
please attach the offending turtle file

**Comment by GullyAPCBurns** [comment]
Here it is.

G

**Comment by szeke** [comment]
no attachment

**Comment by GullyAPCBurns** [comment]
OK. Here it is as a zip file. 

G
[neuDIGs.ttl.zip](https://github.com/usc-isi-i2/Web-Karma/files/339737/neuDIGs.ttl.zip)

**Comment by szeke** [comment]
False alarm, the TTL ontology loads properly.
