### ISSUE TITLE
Generate RDF from Database

### ISSUE THREAD

**Issue by gigialmo88** [usc-isi-i2/Web-Karma#270]
After executing the arguments I receive this error:

[INFO]
[INFO] --- exec-maven-plugin:1.1:java (default-cli) @ karma-offline ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.110 s
[INFO] Finished at: 2016-07-21T10:21:32-06:00
[INFO] Final Memory: 13M/125M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1:java (def                         ault-cli) on project karma-offline: args contains not properly formatted string -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Any suggestions on how I can resolve this?
Thanks!

**Comment by dkapoor** [comment]
Can you try by putting everything is a single line on your console
`mvn exec:java -Dexec.mainClass="edu.isi.karma.rdf.OfflineRdfGenerator" -Dexec.args="--sourcetype <sourcetype> --filepath <filepath> --modelfilepath <modelfilepath> --sourcename <sourcename> --outputfile <outputfile>" -Dexec.classpathScope=compile`

**Comment by gigialmo88** [comment]
I put these arguments into a single line: mvn exec:java -Dexec.mainClass="edu.isi.karma.rdf.OfflineRdfGenerator" -Dexec.args=" --sourcetype DB --dbtype MySQL --hostname <> --username root --password <> --portnumber 3306 --dbname new_schema --tablename City --modelfilepath \"/Users/<>/Desktop/TriplesMap_City.ttl\" --outputfile db-rdf.n3 --jsonoutputfile db-rdf.json" -Dexec.classpathScope=compile

It now says build successful, but I am not able to locate the outputfile db-rdf.n3 or the jsonoutputfile db-rdf.json. I suspected it would be in the karma-offline folder, but it appears not to be. Any suggestions?

Thanks!

**Comment by dkapoor** [comment]
Yes, the output files should be in karma-offline folder. Can you try copying ur ttl file too into karma-offline and then issue the command without the quotes
`mvn exec:java -Dexec.mainClass="edu.isi.karma.rdf.OfflineRdfGenerator" -Dexec.args="--sourcetype DB --dbtype MySQL --hostname <> --username root --password <> --portnumber 3306 --dbname new_schema --tablename City --modelfilepath TriplesMap_City.tt --outputfile db-rdf.n3 --jsonoutputfile db-rdf.json" -Dexec.classpathScope=compile`
It could be some issue with the quoting that is messing things up.

**Comment by gigialmo88** [comment]
After making the changes as you mentioned, I get this Error:

ERROR [2016-07-26 09:45:45,517] (OfflineRdfGenerator->main->156): Error occured while generating RDF!
edu.isi.karma.webserver.KarmaException: Resource not found in model for the source: City

I believe the reason for this error is because of the links that are within my ttl files are broken, hence it can't find the resource. Is there a way to use Karma Web to generate the ttl files so that I can use the offline rdf generator? I was reading the documentation and I wasn't sure if an ontology is required to import in order to make the mappings. Essentially, my goal is to generate an rdf based on our current data in MySQL. We don't have an ontology to map to, so I wasn't sure if it's possible to use Karma with or without an ontology? 

Thanks!

**Comment by dkapoor** [comment]
Karma is used to map data to an existing ontology. So, you would have to start with an ontology. Then you can use the web interface of karma to map data to the ontology and publish the model. This generates the ttl file that you can subsequently in the OfflineRDFGenerator.
You can have a look at the wiki on how to model the data - https://github.com/usc-isi-i2/Web-Karma/wiki/Modeling-Data and then to generate the ttl file, you just click on the worksheet title and select publish -> R2RML Model. You can also see how to publish the data as RDF here - https://github.com/usc-isi-i2/Web-Karma/wiki/Publishing-Data
