### ISSUE TITLE
columnSubClassOfLink resolves to a string

### ISSUE THREAD

**Issue by wdduncan** [usc-isi-i2/Web-Karma#272]
I am using the columnSubClassOfLink to specify that a particular column specifies that a specific uri is of that columns type. Here is the set up:

1. I have a column named "gender_uri" that specifies the specific instance of a gender role that characterizes a patient.
2. I have a column named "gender_type" that specifies particular subclass of gender a patient is depending on the value in the gender column; "M" for male, "F" for female.
3. I created a columnSubClassOfLink so that the gender uris would be matched to the appropriate subclass.

See the screen shot for the setup.

When I publish the RDF, the gender type is represented as a string. For example:

<http://purl.obolibrary.org/gender-role/10001/M> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "http://purl.regenstrief.org/dental-ontology/RIDO_0000072" .

"http://purl.regenstrief.org/dental-ontology/RIDO_0000072" should be <http://purl.regenstrief.org/dental-ontology/RIDO_0000072>, that is:

<http://purl.obolibrary.org/gender-role/10001/M> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.regenstrief.org/dental-ontology/RIDO_0000072> .

I've attached RDF and screen shot
<img width="691" alt="ri-demo" src="https://cloud.githubusercontent.com/assets/3186638/17486283/40eb2fc4-5d5e-11e6-8f06-115e20c76346.png">

[RI-demo.ttl.txt](https://github.com/usc-isi-i2/Web-Karma/files/407180/RI-demo.ttl.txt)

.

**Comment by dkapoor** [comment]
We have fixed this issue. It is still not available in the master branch, but you could checkout the development branch to get it.
```
git checkout development
mvn clean install
cd karma-web
mvn jetty:run
```
