### ISSUE TITLE
columnSubClassOfLink problem within json-ld generation

### ISSUE THREAD

**Issue by rebecabarros** [usc-isi-i2/Web-Karma#273]
I created a mapping using columnSubClassOfLink to specify a particular
subclass depending on the value of a column. I was able to get
the results in the way that I needeed. From karma modelling everything works fine.

Now I have started working in Batch Mode and I'm facing a problem. I'm using a CSV file as input and json-ld as output and I'm using a context file too. The part related to "columnSubClassOfLink " works randomly, sometimes returns the correct uri, and sometimes returns the uri from the general node.

I used karma-service and karma-offline and got the same result. 

Note: the problem itself it is not in the size of my csv file but when I call repeatedly the service.

**Comment by dkapoor** [comment]
Could you send us you model and the CSV file so we can reproduce this at our end. Thanks.

**Comment by rebecabarros** [comment]
Yes, for sure. The files are attached.
Thanks.
[karma.zip](https://github.com/usc-isi-i2/Web-Karma/files/439249/karma.zip)

**Comment by dkapoor** [comment]
Thanks for the files. The problem occurs only in JSON-LD and not in RDF as for RDF we are outputting all the uris, but for JSON-LD we were picking only 1 of the two in this case. The one that it picks was random which caused this issue.

To fix this we have made the "a" or the "@type" as an array and now output both the uris. This fix is available in the branch `jsonld-@type-as-array`. You can give it a try.
