### ISSUE TITLE
Running the Karma in offline mode as a jar

### ISSUE THREAD

**Issue by felixneto** [usc-isi-i2/Web-Karma#274]
Hello I am new using Karma and tried to compile the Karma offline and put it inside my library package.

I used the model I created in Karma web modeling tool. But it returns an error during the python transformation.

Do I need to set any key for python ?

I am using windows and compiling it in eclipse.

The error is in attachment.

If it is needed I can attach the model file too. 

Thank you in advance and sorry.
[karmaPythonError.txt](https://github.com/usc-isi-i2/Web-Karma/files/420633/karmaPythonError.txt)

**Comment by dkapoor** [comment]
Can you send the model file, sample data file and zip of your karma home folder to dipsy@isi.edu and I can have a look. Thanks.
