### ISSUE TITLE
can't specify a semantic type of a column in karma

### ISSUE THREAD

**Issue by rabiam04** [usc-isi-i2/Web-Karma#278]
I can't specify a semantic type of a column in karma, please help
In semantic type, I am not able to set property name or class name. What should I do?

**Comment by szeke** [comment]
We need more details to be able to help you.

**Comment by rabiam04** [comment]
Thanks for your quick response. I import the data-set file in karma and set semantic type. But I couldn't assign property and class as told in tutorials. I am attaching screenshot, this might help what i want to ask about
![1](https://cloud.githubusercontent.com/assets/22327197/18700412/8d301a0c-7ff0-11e6-8ebd-1908c60d2cc7.png)
![2](https://cloud.githubusercontent.com/assets/22327197/18700413/8d322a0e-7ff0-11e6-90cc-d360d0b2013d.png)

**Comment by Jimflip** [comment]
Have you imported an ontology?

**Comment by rabiam04** [comment]
It's solved already
