### ISSUE TITLE
Extra red dots after suggest function?

### ISSUE THREAD

**Issue by rhao** [usc-isi-i2/Web-Karma#280]
When I click suggest, sometimes the suggestion allows me to drag a red dot to the class I want to connect to. Sometimes, after doing this, I see a floating red dot surrounded by gray - you can see two of these on the right side of the attached picture. What is that? Is there a way to remove it, or is it supposed to be there?

![karma](https://cloud.githubusercontent.com/assets/3289438/18685792/56ec1cb0-7f2e-11e6-98d0-2b5c7f96ba80.png)

**Comment by dkapoor** [comment]
That is a bug and the dots should not be there. We will try to reproduce and fix this.

**Comment by rutujarane** [comment]
Old issue.
Please reopen this issue if you are still facing this problem.
Closing.
