### ISSUE TITLE
can't open RDF file after published

### ISSUE THREAD

**Issue by jinjin304616** [usc-isi-i2/Web-Karma#286]
![image](https://cloud.githubusercontent.com/assets/13896872/19029673/f2411d2c-897a-11e6-8f22-0dc36cab697c.png)
Any idea how to downlaod published RDF file?

**Comment by dkapoor** [comment]
Can you check if you still have Karma running on http://localhost:8080 by repening it in a new window?
Also, could you have a look at the Karma console and see if there is some exception there. Can you attach the trace? Thanks

**Comment by jinjin304616** [comment]
Frustrated! Now comes another problem
![image](https://cloud.githubusercontent.com/assets/13896872/19059967/9d18c3e4-8a16-11e6-9913-060ae3dfac6d.png)

Here is the trace:
![image](https://cloud.githubusercontent.com/assets/13896872/19059984/b09b8802-8a16-11e6-925d-000743d705da.png)

**Comment by jinjin304616** [comment]
![image](https://cloud.githubusercontent.com/assets/13896872/19060693/e7cf411e-8a1c-11e6-87cc-61bf0e319239.png)

still can't open RDF

**Comment by dkapoor** [comment]
That is a problem seen on Windows machine. 
You can follow the instructions here on the Troubleshooting page to fix this: https://github.com/usc-isi-i2/Web-Karma/wiki/Troubleshooting#in-windows-when-i-re-publish-my-model-or-json-or-any-other-file-it-gives-me-an-error-and-is-not-able-to-perform-the-operation
