### ISSUE TITLE
Response without uri in Karma RDF Generation Service

### ISSUE THREAD

**Issue by kojinanjo** [usc-isi-i2/Web-Karma#291]
Dear karma team

I was testing this services but I had a issue with the uri, the response doesn't have the uri that I set in the model.

the response here:

<1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#FacultyMember> .
<uniaca56> <http://vivoweb.org/ontology/core#relatedBy> <pos1> .
<pos1> <http://vivoweb.org/ontology/core#hrJobTitle> "Acad\u00E9mico" .

I used the same model that I used for karma-offline, in karma offline works well.

what can it be?

**Comment by kojinanjo** [comment]
Any news about this?
thanks

**Comment by dkapoor** [comment]
So, are you trying to run Karma as a Service on the same machine on which you ran karma-offline and while it worked in karma-offline, it is not working when you run Karma as a service?

If so, can you attach a zip of your karma home folder, your karma model and a small example dataset.
Thanks and sorry about the late response.

**Comment by kojinanjo** [comment]
Hi
We have 2 karmas in different machine, I attached the folder and examples of the dataset
thanks :)

[karma.zip](https://github.com/usc-isi-i2/Web-Karma/files/594813/karma.zip)

**Comment by dkapoor** [comment]
We had not exposed the BaseUri parameter in Karma Web Service and that is the reason it was being defaulted to blank and the URIs that were getting generated were without any base.
We have fixed this and you can pull in the latest version of Karma. You would need to pass an additional `BaseUri` parameter and set it to `http://xxxxxxxxxxxxxx/vivo/individual/`. That would fix the issue.

**Comment by kojinanjo** [comment]
Hi dkapoor 
the BaseUri is not right. Is BaseURI with uppercase, this works for me, could you please fix this in the documentation?
Thanks and greeting from Chile
