### ISSUE TITLE
Exception occurred when trying to publish R2RML model

### ISSUE THREAD

**Issue by raviraju** [usc-isi-i2/Web-Karma#292]
NOTE : Used Karma.exe on windows.

[karma.zip](https://github.com/usc-isi-i2/Web-Karma/files/584293/karma.zip)
![screenshot 2016-11-10 11 36 24](https://cloud.githubusercontent.com/assets/1003517/20191802/f46fe680-a73b-11e6-84de-1012e98f768c.png)

NOTE : Since github restricts from uploading .ttl and .xml files, the following file txt file equivalent have been uploaded

[WSP1WS16645-WAM_XMLExport_AAC_Geography.xml-auto-model_ttl.txt](https://github.com/usc-isi-i2/Web-Karma/files/584299/WSP1WS16645-WAM_XMLExport_AAC_Geography.xml-auto-model_ttl.txt)

[WAM_XMLExport_AAC_Geography_xml.txt](https://github.com/usc-isi-i2/Web-Karma/files/584301/WAM_XMLExport_AAC_Geography_xml.txt)

**Comment by dkapoor** [comment]
I downloaded ur karma.zip, set it as my home folder, then loaded the xml(all rows) and applied the R2RML model. When I publish, I do not get any errors, it works fine.

Could you try the above steps and let me know. Thanks
