### ISSUE TITLE
@vocab in json-ld @context is ignored

### ISSUE THREAD

**Issue by Jimflip** [usc-isi-i2/Web-Karma#294]
Hi

I am uploading a JSON-LD context when I am exporting JSON-LD, but the @vocab keyword doesn't seem to work. 

I would expect to see the uri to be removed from the output json; but it is not (same data in json-ld playground works as expected).

**Comment by rutujarane** [comment]
Old issue.
Please reopen this issue if you are still facing this problem.
Closing.
