### ISSUE TITLE
Report published doesnt capture all the transformations of current model

### ISSUE THREAD

**Issue by raviraju** [usc-isi-i2/Web-Karma#295]
It was observed that report exported is invalid. While working on modelling AAC_Titles, neither all field transformations of AAC_Titles are captured in report and Field Names of some other models like AAC_Geography and AAC_Exhibition are exported

NOTE : 
No multiple worksheets were used simultaneously, i.e when moving from modelling one source to another, browser was refreshed.
I was able to reproduce this issue after refreshing browser and re-loading the data and model file

Restart of Karma was also tried, though export Json works fine, export of report doesnt

#### _ObjectURI_
From column: _Root / ObjRecord / ObjectURI_
``` python
return "id/object/" + getValue("ObjectID")
```

#### _TitleVal_
From column: _Root / ObjRecord / Titles / Title / TitleVal_
``` python
return getValue("Title")
```

#### _ObjectLabel_
From column: _Root / ObjRecord / ObjectLabel_
``` python
return getValue("ObjectID")
```

### Semantic Types
| Column | Property | Class |
|  ----- | -------- | ----- |
| _ExhBeginISODate_ | `crm:P82a_begin_of_the_begin` | `crm:E52_Time-Span1`|
| _ExhEndISODate_ | `crm:P82b_end_of_the_end` | `crm:E52_Time-Span1`|
| _ExhTitle_ | `rdfs:label` | `crm:E41_Appellation1`|
| _ExhTitle_ | `rdf:value` | `crm:E41_Appellation1`|
| _ExhVenueURI_ | `uri` | `crm:E93_Presence1`|
| _ExhibCitation_ | `crm:P3_has_note` | `crm:E33_Linguistic_Object1`|
| _ExhibCitationURI_ | `uri` | `crm:E33_Linguistic_Object1`|
| _ExhibitionTimeSpanURI_ | `uri` | `crm:E52_Time-Span1`|
| _ExhibitionTitleURI_ | `uri` | `crm:E41_Appellation1`|
| _ExhibitionURI_ | `uri` | `crm:E5_Event1`|
| _ExhibitionURI_ | `uri` | `crm:E7_Activity1`|
| _GeographyID_ | `rdfs:label` | `crm:E42_Identifier2`|
| _GeographyTerm_ | `rdfs:label` | `crm:E48_Place_Name1`|
| _ObjectID_ | `rdfs:label` | `crm:E42_Identifier1`|
| _ObjectID_ | `rdf:value` | `crm:E42_Identifier2`|
| _ObjectID_ | `rdf:value` | `crm:E42_Identifier2`|
| _ObjectID_GeographyID_ | `uri` | `crm:E11_Modification1`|
| _ObjectLabel_ | `rdfs:label` | `crm:E42_Identifier2`|
| _ObjectURI_ | `uri` | `crm:E22_Man-Made_Object1`|
| _ObjectURI_ | `uri` | `crm:E22_Man-Made_Object1`|
| _ObjectURI_ | `uri` | `crm:E42_Identifier1`|
| _PlaceURI_ | `uri` | `crm:E53_Place1`|
| _PrimaryTitleType_ | `crm:P2_has_type` | `crm:E35_Title1`|
| _PrimaryTitleType_ | `crm:P2_has_type` | `crm:E42_Identifier2`|
| _SpatialCoOrdinates_ | `rdfs:label` | `crm:E47_Spatial_Coordinates1`|
| _TGNTermID_ | `rdfs:label` | `crm:E42_Identifier3`|
| _TGNTermIDURI_ | `uri` | `crm:E42_Identifier3`|
| _Title_ | `rdfs:label` | `crm:E22_Man-Made_Object1`|
| _Title_ | `rdf:value` | `crm:E35_Title1`|
| _Title_ | `rdf:value` | `crm:E35_Title1`|
| _Title_ | `rdfs:label` | `crm:E35_Title1`|
| _TitleID_ | `rdf:value` | `crm:E42_Identifier1`|
| _TitleID_ | `rdf:value` | `crm:E42_Identifier1`|
| _TitleType_ | `rdfs:label` | `crm:E55_Type1`|
| _TitleType_ | `skos:prefLabel` | `crm:E55_Type1`|
| _TitleTypeURI_ | `uri` | `crm:E55_Type1`|
| _TitleURI_ | `uri` | `crm:E35_Title1`|
| _TitleURI_ | `uri` | `crm:E35_Title1`|
| _TitleVal_ | `rdfs:label` | `crm:E22_Man-Made_Object1`|
| _Type_PreferredTerm_ | `crm:P2_has_type` | `crm:E35_Title1`|
| _Type_PreferredTerm_ | `skos:broadMatch` | `crm:E55_Type1`|
| _Type_Repositry_ | `crm:P2_has_type` | `crm:E42_Identifier2`|
| _Type_UniqueId_ | `crm:P2_has_type` | `crm:E42_Identifier1`|
| _Type_UniqueId_ | `crm:P2_has_type` | `crm:E42_Identifier1`|
| _VenueBegDate_ | `crm:P82a_begin_of_the_begin` | `crm:E52_Time-Span2`|
| _VenueDisplayName_ | `rdfs:label` | `crm:E93_Presence1`|
| _VenueEndDate_ | `crm:P82b_end_of_the_end` | `crm:E52_Time-Span2`|

### Links
| From | Property | To |
|  --- | -------- | ---|
| `crm:E22_Man-Made_Object1` | `crm:P102_has_title` | `crm:E35_Title1`|
| `crm:E22_Man-Made_Object1` | `crm:P1_is_identified_by` | `crm:E42_Identifier2`|
| `crm:E35_Title1` | `crm:P1_is_identified_by` | `crm:E42_Identifier1`|
[karma.zip](https://github.com/usc-isi-i2/Web-Karma/files/598690/karma.zip)

**Comment by dkapoor** [comment]
Could you also attach/point to your model and sample data file?

**Comment by dkapoor** [comment]
There was a bug in the way we were getting the columns that caused the issue with the extra rows in Semantic types. We have fixed that. Also we have added more commands to the report - Add Column, Add Node, Add Literal Node and Selections.
You can check out and build the development branch to get the fix. Attached is the report generated by the fixed code (Have added .txt to the filename so I could upload it)

[WAM_AAC_Titles.xml.md.txt](https://github.com/usc-isi-i2/Web-Karma/files/628086/WAM_AAC_Titles.xml.md.txt)
