### ISSUE TITLE
Some values in json exported isnt in valid format

### ISSUE THREAD

**Issue by raviraju** [usc-isi-i2/Web-Karma#296]
In the following we observe "_:crm_E42_Identifier2_91af3aff455c5a6d2d273f4b654b40871dd0b52d_N6147_91af3aff455c5a6d2d273f4b654b40871dd0b52d_N6147_e21833746a240a64e10b4cbfd896105931efbe2b_N6465"

E42_Identifier has properties : rdf:value, P2_has_type and rdfs:label, which isnt exported in json
Try WAM_AAC_Titles.xml and its respective model file WAM_AAC_Titles-model.ttl in user-uploaded-files directory of attached zip file

[karma.zip](https://github.com/usc-isi-i2/Web-Karma/files/598729/karma.zip)

{
    "a": ["E22_Man-Made_Object"],
    "P1_is_identified_by": "_:crm_E42_Identifier2_91af3aff455c5a6d2d273f4b654b40871dd0b52d_N6147_91af3aff455c5a6d2d273f4b654b40871dd0b52d_N6147_e21833746a240a64e10b4cbfd896105931efbe2b_N6465",
    "label": "Carrie and the Cats",
    "uri": "http://localhost:8080/source/id/object/16337",
    "P102_has_title": {
        "a": ["E35_Title"],
        "P1_is_identified_by": {
            "a": ["E42_Identifier"],
            "P2_has_type": "http://vocab.getty.edu/aat/300404012",
            "value": "47825"
        },
        "P2_has_type": "http://vocab.getty.edu/aat/300404670",
        "value": "Carrie and the Cats"
    },
    "@context": "http://localhost:8080/publish/JSON/WSP1WS5-WAM_AAC_Titles_xml-context.json"
}

**Comment by dkapoor** [comment]
Could you also attach the model and the sample data file. Thanks.

**Comment by raviraju** [comment]
We can refer to latest files of the following directories in attached karma.zip file
user-uploaded-files/AAC_Titles.xml 
models-autosave/AAC_Titles.xml-automodel.ttl

**Comment by dkapoor** [comment]
I exported the JSON-LD and the output looks right to me
```
{
    "@context": "http://localhost:8080/publish/JSON/WSP29WS5-WAM_AAC_Titles_xml-context.json",
    "a": ["E22_Man-Made_Object"],
    "uri": "http://localhost:8080/source/id/object/12122",
    "P1_is_identified_by": {
        "a": ["E42_Identifier"],
        "value": "12122",
        "P2_has_type": "http://vocab.getty.edu/aat/300404621",
        "label": "12122"
    }
},
{
    "@context": "http://localhost:8080/publish/JSON/WSP29WS5-WAM_AAC_Titles_xml-context.json",
    "P102_has_title": {
        "a": ["E35_Title"],
        "value": "The Lady Apothecary",
        "P2_has_type": "http://vocab.getty.edu/aat/300404670",
        "P1_is_identified_by": {
            "a": ["E42_Identifier"],
            "value": "47882",
            "P2_has_type": "http://vocab.getty.edu/aat/300404012"
        }
    },
    "a": ["E22_Man-Made_Object"],
    "label": "The Lady Apothecary",
    "uri": "http://localhost:8080/source/id/object/11514",
    "P1_is_identified_by": {
        "a": ["E42_Identifier"],
        "value": "11514",
        "P2_has_type": "http://vocab.getty.edu/aat/300404621",
        "label": "11514"
    }
}
```
You have 2 `E42_Identifier` defined in the model. The one linked to the `E35_Title` does not have the `rdfs:label` property. The one directly linked to `E22_Man-Made_Object1` does.

The screenshot of the model is attached

![screen shot 2016-12-02 at 12 18 37 pm](https://cloud.githubusercontent.com/assets/1852707/20849007/8abead48-b889-11e6-9dd9-eb6a6b832729.png)
