### ISSUE TITLE
mvn install fails in Vagrant

### ISSUE THREAD

**Issue by sennierer** [usc-isi-i2/Web-Karma#298]
Hi,

I tried to use the vagrant box, but the build fails. I slightly modified the vagrantfile as maven 3.3.3 is no longer accessible (switched to 3.3.9):

`==> default: [INFO] karma-mr ........................................... FAILURE [02:08 min]
==> default: [INFO] karma-storm ........................................ SKIPPED
==> default: [INFO] karma-web-services ................................. SKIPPED
==> default: [INFO] web-services-rdf ................................... SKIPPED
==> default: [INFO] web-services-publish-es ............................ SKIPPED
==> default: [INFO] karma-spark ........................................ SKIPPED
==> default: [INFO] ------------------------------------------------------------------------
==> default: [INFO] BUILD FAILURE
==> default: [INFO] ------------------------------------------------------------------------
==> default: [INFO] Total time: 05:19 min
==> default: [INFO] Finished at: 2016-11-21T10:29:41+00:00
==> default: [INFO] Final Memory: 90M/336M
==> default: [INFO] ------------------------------------------------------------------------
==> default: [ERROR] Failed to execute goal on project karma-mr: Could not resolve dependencies for project edu.isi:karma-mr:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.apache.hive:hive-exec:jar:1.1.0-cdh5.5.0 -> org.apache.calcite:calcite-core:jar:1.0.0-incubating -> org.apache.calcite:calcite-avatica:jar:1.0.0-incubating -> eigenbase:eigenbase-properties:jar:1.1.4: Failed to read artifact descriptor for eigenbase:eigenbase-properties:jar:1.1.4: Could not transfer artifact eigenbase:eigenbase-properties:pom:1.1.4 from/to cdh.snapshots.repo (https://repository.cloudera.com/content/repositories/snapshots): Failed to transfer file: https://repository.cloudera.com/content/repositories/snapshots/eigenbase/eigenbase-properties/1.1.4/eigenbase-properties-1.1.4.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]
==> default: [ERROR]
==> default: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
==> default: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
==> default:
==> default: [ERROR]
==> default: [ERROR] For more information about the errors and possible solutions, please read the following articles:
==> default: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
==> default: [ERROR]
==> default: [ERROR] After correcting the problems, you can resume the build with the command
==> default: [ERROR]   mvn <goals> -rf :karma-mr`

Thanks very much for the help!

**Comment by dkapoor** [comment]
We have a new one click installer available for karma - https://github.com/usc-isi-i2/Web-Karma/wiki/Installation%3A-One-Click-Install
We will be removing the vagrant installer in our future releases. Can you use the new installer since we do not support the vagrant one anymore. Thanks.
