### ISSUE TITLE
Modeling Data (using source code)

### ISSUE THREAD

**Issue by gigialmo88** [usc-isi-i2/Web-Karma#301]
Hi,
I've imported data from MySQL database, and I have also loaded an ontology into the Karma Data Integration. It says ontology was successfully imported, but I am unclear as how I need to model the data. If I loaded the ontology, is it still supposed to start with an empty model? Or does this mean that the ontology I loaded isn't working? I am trying to publish the data so that I can either generate the rdf, ttl, or r2rml file. Any help is appreciated. Thanks!

**Comment by dkapoor** [comment]
After you import your ontology (or you can copy your ontology files to `{karma home folder}/preloaded-ontologies` and you dont have to do that every time), you have to model your data. Please see here on how to model you data - https://github.com/usc-isi-i2/Web-Karma/wiki/Modeling-Data. After modeling, you can publish your data as RDF. The wiki contains instructions for transforming data, modeling and publishing it.

**Comment by gigialmo88** [comment]
If I already have the r2rml mappings in a .ttl file, can I use that to model the data in the web karma? When I try to apply r2rml model to one of the imported tables, it says "error occurred while applying history".

**Comment by dkapoor** [comment]
Karma only works with a R2RML mapping file that is generated using Karma. So if the ttl file is generated using a different application, it will not work. You will in that case have to do the modeling using the Karma UI.

**Comment by szeke** [comment]
@gigialmo88 can you share with us the R2RML mappings you are trying to execute? We'd like to see what parts don't work as we are interested in supporting externally created R2RML. We would need URLs to the ontologies as well.

**Comment by gigialmo88** [comment]
Yes, I will be glad to share those with you. Is there an email you would like me to send them to?

Also, I have modeled the data and when I try to publish --> R2RML model it says "error: null".
I tried also using publish --> RDF and it asks for a URI, I'm unsure what URI I'm suppose to provide it with.

Thanks!
