### ISSUE TITLE
Order of pytransformations has an effect on model

### ISSUE THREAD

**Issue by raviraju** [usc-isi-i2/Web-Karma#305]
Suppose a new column 'A' is created with pytransform with value set 'a'.
Another column 'B' is created which inturn uses getValue('A') to set its value to 'a/b'
We know that, if we change value of column 'A' to "A", column 'B' doesnt update unless we perform a column refresh in UI.
If we export such a model and apply model on data, we still see values  '/b' in column B,if pytransform of column B gets applied first 

[WAM_AAC_Dimensions.zip](https://github.com/usc-isi-i2/Web-Karma/files/662154/WAM_AAC_Dimensions.zip)

**Comment by kaushalv274** [comment]
Hi  Ravi,

This issue has been fixed and verified. Please let us know if you are still facing the same problem.
