### ISSUE TITLE
Issue with generating n3 triples using batch mode

### ISSUE THREAD

**Issue by raviraju** [usc-isi-i2/Web-Karma#306]
An inconsistency was observed between triples that are generated in batch mode aganist rdf triples generated by importing all data in web-karma and publishing rdf
It seems the selection filter was not applied in batch mode.

[karma_spark_issue.zip](https://github.com/usc-isi-i2/Web-Karma/files/686327/karma_spark_issue.zip)

**Comment by dkapoor** [comment]
Have fixed the issue. The selections should now work in Offline mode and spark. 

* For offline mode,you need to specify `--selection DEFAULT_TEST`
* For spark, you need to add a additional parameter to the `run_karma` call: `additional_settings={"rdf.generation.selection":"DEFAULT_TEST"}`
