### ISSUE TITLE
PyTransform doesnt produce desired outcome when publishing rdf triples

### ISSUE THREAD

**Issue by raviraju** [usc-isi-i2/Web-Karma#307]
The following are 2 scenarios

**Observed:**
<http://data.thewalters.org/object/id/3064/production/individual/2112/death_location> <http://www.cidoc-crm.org/cidoc-crm/P7_took_place_at> <http://data.thewalters.org/7011781/7011781> .

_return getValue("DeathURI") + "/" + getValue("ConGeoTGNSourceTermID")_

**Expected:**
<http://data.thewalters.org/object/id/334/production/individual/2112/death_location> <http://www.cidoc-crm.org/cidoc-crm/P7_took_place_at> <http://data.thewalters.org/object/id/334/production/individual/2112/death_location/7011781> .
##############################################################################
**Observed:**
[issue_data.zip](https://github.com/usc-isi-i2/Web-Karma/files/689041/issue_data.zip)

<http://data.americanartcollaborative.org/puam/object/14284/primary_title> <http://www.cidoc-crm.org/cidoc-crm/P1_is_identified_by> <http://data.americanartcollaborative.org/puam/62631/id/62631> .

_return getValue("TitleURI") + "/id/" + getValue("TitleID")_

**Expected:**
<http://data.americanartcollaborative.org/puam/object/14284/primary_title> <http://www.cidoc-crm.org/cidoc-crm/P1_is_identified_by> <http://data.americanartcollaborative.org/puam/object/14284/primary_title/id/62631> .

**Comment by dkapoor** [comment]
This was because of a bug in selection which I just fixed. It gives the expected outputs now. You can pull in latest development to get the changes. Thanks.

**Comment by raviraju** [comment]
Verified
