### ISSUE TITLE
Unable to Organize Columns after applying  model

### ISSUE THREAD

**Issue by sjayakum** [usc-isi-i2/Web-Karma#308]
If 1/more columns that are part of model is made hidden using the Organize Columns feature (BEFORE applying the model), then AFTER applying the model these columns can't be added back using Organize Columns feature.

<img width="1680" alt="screen shot 2017-01-12 at 11 03 47 am" src="https://cloud.githubusercontent.com/assets/12380569/21904092/52fb9666-d8b7-11e6-84f9-b1ac9ed5589e.png">

**Comment by dkapoor** [comment]
Have fixed this issue. When you click on Organize Columns now,  you can un-hide the columns. Fix is in development branch.
