### ISSUE TITLE
Error publishing model

### ISSUE THREAD

**Issue by bsnikhila** [usc-isi-i2/Web-Karma#311]
I just pulled the files for the museum GM. And I made a few changes for the Objects model [here](https://github.com/american-art/GM/tree/master/Objects). When I try publishing the model, I get this error:
Error executing command SetSemanticTypeCommand from history
And more errors: 
ObjectID does not exist, using empty values
Object Number does not exist, using empty values etc
These are columns that are in the original data file, not ones that I have created.

**Comment by dkapoor** [comment]
There was an error when we try to publish edited models whose data source was CSV. We have fixed this. You can checkout the latest development branch for the fix.
