### ISSUE TITLE
One click Installer on Mac doesn't work properly

### ISSUE THREAD

**Issue by ahmad88me** [usc-isi-i2/Web-Karma#312]
Hi, I downloaded the latest version v2.052. When I open the app, and click on any of the buttons "Restart Karma" or "Open New Window" or the dropdown nothing happen.

Thank you,

![screen shot 2017-02-08 at 2 01 54 pm](https://cloud.githubusercontent.com/assets/6922709/22738374/7ee3cc20-ee07-11e6-9d2d-68396756a09e.png)

**Comment by kaushalv274** [comment]
Hi,

We are looking into this issue. 

Thanks
Kaushal

**Comment by dkapoor** [comment]
Which version of OS X do you have? Also do you have Java installed? Can you let us know your Java version?

**Comment by ahmad88me** [comment]
@dkapoor I'm running Sierra, Java version is:
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

**Comment by valentinedwv** [comment]
I had to remove spaces from the path. The default expands to 'Karma-Mac 2' changes to Karma-mac

>Show Package Contents
Open macOS folder
open karma, terminal window will open. In there I saw that tomcat was not starting. Path not enclosed.

**Comment by Kisehi** [comment]
Same problem for me. Java 1.8.0_144; Mac OS Sierra 10.12.6. Cheers

**Comment by kaushalv274** [comment]
Hi, 

Can you please share exception/error details ?

**Comment by Kisehi** [comment]
Hi there,

Thanks for the quick response. I just open Karma and the interface appears but nothing happens. I have JAVA 1.8.0_144  running in a MacOS 10.12.6.

Cheers,

JMM

**Comment by kaushalv274** [comment]
Hi @Kisehi ,@ahmad88me  Can you please use latest version of Karma. (v2.053) on mac and try using it?

Thanks
Kaushal
