### ISSUE TITLE
"Choose Table" not working

### ISSUE THREAD

**Issue by martin-voigt** [usc-isi-i2/Web-Karma#316]
Hi,

I'm currently started testing the capabilities of Karma and I'm impressed. By importing data from and SQL DB it shows me the list of tables, however, the search field "Choose Table" doesn't do anything.

**Comment by kaushalv274** [comment]
Hi Martin,

Which version of Karma you are using?
We will look into this and reply as soon as possible.

Thanks
Kaushal

**Comment by martin-voigt** [comment]
Hi,

thx. I checked out the master branch and built with Maven. In the UI it shows v2.052.

Martin

**Comment by kaushalv274** [comment]
Hi Martin,

We have fixed this issue. You can pull latest development branch to get the fix.

Thanks
Kaushal
