### ISSUE TITLE
Specifying domain on SQL Server connections

### ISSUE THREAD

**Issue by marijane** [usc-isi-i2/Web-Karma#317]
I am trying to connect Karma to a MS SQL Server database that requires me to specify a domain.  Is there some way for me to specify this in the Import Database Table form?

**Comment by kaushalv274** [comment]
Hi,

Can you please try adding your domain to add with your username ?

Username would be "domain\user_name"

Thanks
Kaushal

**Comment by marijane** [comment]
This doesn't appear to work.  Karma tells me "Login failed for 'domainuser_name'"  (the error message strips the backslash.)

**Comment by parker20121** [comment]
Try adding it to the database url like the following example.

![image](https://user-images.githubusercontent.com/351878/29500503-1b6771d0-85ef-11e7-8908-8098a4db3170.png)

https://confluence.atlassian.com/confkb/cannot-connect-confluence-to-ms-sql-server-using-a-domain-account-600867138.html

**Comment by parker20121** [comment]
Some more complete docs:

https://kb.sos-berlin.com/display/PKB/How+to+connect+to+an+SQL+Server+with+a+domain+account

**Comment by rutujarane** [comment]
Old issue.
Please reopen this issue if you are still facing this problem.
Closing.
