### ISSUE TITLE
Literals are being freed

### ISSUE THREAD

**Issue by bsnikhila** [usc-isi-i2/Web-Karma#318]
The literals in my model are losing their links and being freed when I try to publish the model. And the code for this linkage seems to be missing in the new model files.

Example model:
https://github.com/american-art/nmwa/tree/master/Data

**Comment by dkapoor** [comment]
Nikhila, the model is already messed up. The links are not being added to the correct ids. I manually fixed the links and it all works now. Here is the updated model. 
[NMWA_Data-model.ttl.txt](https://github.com/usc-isi-i2/Web-Karma/files/842163/NMWA_Data-model.ttl.txt)

I will try to see if there I can find how you ended up with this messed up model.
Can you update your code and rebuild again too. Thanks.

**Comment by dkapoor** [comment]
There was an issue when the Literal Nodes were edited. We are now compacting the Literal Edits and they were not being created with the same ids and for that reason, the links were not being added. We have fixed that and now you can pull from development, rebuild karma and it should work.

**Comment by bsnikhila** [comment]
Checked. This model is working.
