### ISSUE TITLE
Karma RDF export, not retaining correct encoding causing special character to show up wrongly

### ISSUE THREAD

**Issue by mit2nil** [usc-isi-i2/Web-Karma#322]
Hi Karma Devs,

We have identified an issue while using RDF export functionality of Karma-UI as well as Karma-spark. Below is the example:
Data, model is available at below repo:
https://github.com/american-art/GM/tree/master/Constituents_people
Data File: Constituents.csv
Model File: Constituents_people-model.ttl

Below is the data sample in raw data for which we noticed the issue. 
11595,"Gutiérrez, Francisco",Francisco Gutiérrez,Francisco,,Gutiérrez,,,,,1642,1657,active 1642-1657,Spanish,http://www.getty.edu/vow/ULANFullDisplay?find=Cabello&role=&nation=&prev_page=1&subjectid=500035706,1,500035706,male,Artist

We load the csv file with default options and then apply the specified model and then use export as RDF option and resulting RDF is printing with "Guti\u00E9rrez, Francisco" instead of "Gutiérrez, Francisco" which in turn when loaded in triple store can't decode the the character. 
http://data.americanartcollaborative.org/page/GM/constituent/francisco_guti_rrez

Nilay

**Comment by dkapoor** [comment]
We were using Apache StringEscapeUtils to escape the values so newlines etc get written correctly. But that also converted utf-8 to unicode escape sequences. I have fixed that and now the RDF contains correct data:
```
<http://localhost:8080/source/constituent/francisco_guti_rrez/display_name> <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "Francisco Gutiérrez" .
```
You can pull code from development branch to get the fix. Thanks.

**Comment by bitno** [comment]
Dear Karma team,
I'm still seeing this issue in the current version 2.053. Is that correct? If the fix has not been merged yet, which dev version could I use safely?
Many thanks

**Comment by kaushalv274** [comment]
Hi, 

2.053 is the latest Karma version. Are you using One click installer or Source code installation ?

Thanks
Kaushal

**Comment by bitno** [comment]
I'm using the one click installer on a mac.

**Comment by kaushalv274** [comment]
Hi, 

Please send me your data, model and Karma home folder.

Thanks

**Comment by bitno** [comment]
Dear @kaushalv274 

Many thanks for your help. I've included a new test file, mapping, rdf export as well as the home folder to this ticket. Let me know, if I can be of further help.

Many thanks and lots of greetings,
Leo
[example.zip](https://github.com/usc-isi-i2/Web-Karma/files/1667167/example.zip)
[karma.zip](https://github.com/usc-isi-i2/Web-Karma/files/1667168/karma.zip)
