### ISSUE TITLE
PDF not being generated

### ISSUE THREAD

**Issue by bsnikhila** [usc-isi-i2/Web-Karma#329]
When I try to publish the model from Web Karma, the dot, json, md and ttl files get updated. The pdf is not being generated/updated.

**Comment by dkapoor** [comment]
The machine hosting the service that converts graphviz files to pdf is down. We will try and bring it back up soon. Sorry about this.

**Comment by dkapoor** [comment]
We have installed the service now on a new server. You can pull in the latest development code and that contains the link to the correct service.
Thanks.
