### ISSUE TITLE
Problems publishing modified R2RML

### ISSUE THREAD

**Issue by marijane** [usc-isi-i2/Web-Karma#330]
**Problem:** 
Sometimes you might want to modify an existing model mapping, rather than recreating it from scratch.  Karma usually has trouble publishing the modified model when you do this.

**Environment:**
OS X 10.11.6 (15G1421)
Google Chrome Version 57.0.2987.133 (64-bit)
Karma version 2.052

**Steps to Reproduce:**
1. Load a dataset that has already been mapped to a model that has been saved to a file.
2. Apply the saved R2RML model.
3. Make some changes to the model, such as adding additional PyTransformed columns.
4. Assign semantic types to the new columns.
5. Publish the model.

**Result:**
The operation does not complete as expected. 

- A R2RML model is produced, but it is incomplete.  It might have some of the new columns.  It has none of the new semantic type mappings.  
- Karma does not publish the Markdown report file in this situation.
- The worksheet gets deleted, so you can't publish any RDF if you didn't publish it before attempting to publish the model.  
- User has to start over from scratch if a different model is desired, which is quite error-prone if the mapping is complex.  

**Expected Result:**
Karma should publish the model and the report without issue
Karma should not delete the worksheet

**Comment by rutujarane** [comment]
Old issue.
Please reopen this issue if you are still facing this problem.
Closing.
