### ISSUE TITLE
Cannot publish models for data sets with "chained" PyTransforms

### ISSUE THREAD

**Issue by marijane** [usc-isi-i2/Web-Karma#332]
**Problem:** 
Karma has problems publishing models where PyTransforms are performed on other PyTransformed columns.

**Environment:**
OS X 10.11.6 (15G1421)
Google Chrome Version 57.0.2987.133 (64-bit)
Karma version 2.052

**Steps to Reproduce:**
1. Load a dataset
2. Pick a column and PyTransform it.  For example, if a column is formatted like "street address, city state zip", split it on the comma into one column for the street address and another for the city/state/zip.
2. Pick the transformed city/state/zip column and transform it again-- split it on spaces to separate the values into separate city, state, and zip columns
3. Publish the model

**Result:**
Karma fails to correctly publish models that have PyTransforms of PyTransforms.
(Please forgive the lack of detail, I am writing this issue from memory at the moment.  If I hit it again I will return and add details.)

**Expected Result:**
I should be able to transform any column, or Karma should prevent me from implementing transforms it cannot publish.

**Workaround:**
Do all transforms on the original column from the dataset, repeating transformation code as needed.

**Comment by rutujarane** [comment]
Old issue.
Please reopen this issue if you are still facing this problem.
Closing.
