### ISSUE TITLE
Issue printing models after hiding columns in data sets with lots of columns

### ISSUE THREAD

**Issue by marijane** [usc-isi-i2/Web-Karma#333]
**Problem:**
Hiding (and possibly reordering) columns interferes with Karma's ability to correctly print models.

**Environment:**
OS X 10.11.6 (15G1421)
Google Chrome Version 57.0.2987.133 (64-bit)
Karma version 2.052

**Steps to Reproduce:**
1. Load a dataset with enough columns to scroll off the right side of the screen
2. Transform and map the data
3. In the Organize Columns UI, hide some unmapped columns
4. Print Model

**Result:**
"Floating" nodes for columns off the right side of the screen in the mapping visualization do not "snap" to their columns when printed, which defeats the purpose of printing it.

**Expected result:**
"Floating" nodes should "snap" to their columns just like they do when you print a model that does not have hidden columns.

**Notes:**
Rearranging columns in the Organize Columns UI may also trigger this bug.  More investigation is needed.

**Comment by rutujarane** [comment]
Please reopen this issue if you are still facing this problem.
Closing.
