### ISSUE TITLE
Bulk refresh of columns?

### ISSUE THREAD

**Issue by turbomam** [usc-isi-i2/Web-Karma#340]
I am building most of my URIs with UUIDs.  The UUIDs are created in a new PyTransform column
    import uuid
    return uuid.uuid4().urn[9:]

And then pasting the UUID into other URI columns with another PyTransform
    return 'heightDatum/' + getValue("row_uuid")

When instantiating a new source data table, I I refresh the UUID column with the circular arrow icon, but then I have to click the refresh icon for all (20+) columns that use the UUID.  Is there a way to do that as a bulk operation?

**Comment by dkapoor** [comment]
You can click "Publish Model" at any point and that will re-run the model if there are any edits to existing transforms, thereby refreshing all the columns.
