### ISSUE TITLE
repo.karma.isi.edu - target server failed to respond

### ISSUE THREAD

**Issue by geraldhiebel** [usc-isi-i2/Web-Karma#342]
Hi,
Since a few days I have a problem when I try to run Karma getting the message: target server failed to respond.
I tried a 'mvn clean install' in the Web-Karma-master dir but got the following message:

[ERROR] Failed to execute goal on project commands-worksheet: Could not resolve dependencies for project edu.isi:commands-worksheet:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for [javax.servlet:javax.servlet-api:jar:3.0.1 (compile), edu.isi:commands-common:jar:0.0.1-SNAPSHOT (compile), edu.isi:commands-update:jar:0.0.1-SNAPSHOT (compile), edu.isi:karma-util:jar:0.0.1-SNAPSHOT (compile), edu.isi:karma-common:jar:0.0.1-SNAPSHOT (compile), edu.isi.karma.services:entityExtraction:jar:0.0.1 (compile)]: Failed to read artifact descriptor for edu.isi.karma.services:entityExtraction:jar:0.0.1: Could not transfer artifact edu.isi.karma.services:entityExtraction:pom:0.0.1 from/to KarmaRepo (http://repo.karma.isi.edu/artifactory/libs-release-local): The target server failed to respond -> [Help 1]
Any help appreciated,
Thanks,
Gerald

**Comment by dkapoor** [comment]
We apologize, our service was down. We have brought it back up and it should work now.

**Comment by geraldhiebel** [comment]
Thank you very much for your quick response and solving the issue. All works fine now and I can use the new version.
Hope You are all well,
Best from Austria,
Gerald
