### ISSUE TITLE
Index Data to Support Joins -> Bloom filter error

### ISSUE THREAD

**Issue by turbomam** [usc-isi-i2/Web-Karma#343]
I am using v 2.053, built with mvn on Ubuntu 16.04.

I asked to publish some RDF with "Index Data to Support Joins" enabled and got this error:

> Error occured while generating RDF: Bloom filter writing support not enabled. Please recompile with -Pbloom

PS...  what is the join-supporting index good for anyway?  I panned on teaching myself by just generating the triples with or without the index and comparing by eye

**Comment by rutujarane** [comment]
Please reopen this issue if you are still facing this problem.
Closing.
