### ISSUE TITLE
Not able to generate own ontology

### ISSUE THREAD

**Issue by priya2621** [usc-isi-i2/Web-Karma#344]
I tired to "generate new ontology"  and publish it as "RDF" for the attached sample data(comma separated file) and getting the **"Failed to store RDF to the triple store"**. Attached the request and response for the reference.
**Version:** v2.053
**Sample Used:**[address.txt](https://github.com/usc-isi-i2/Web-Karma/files/1158131/address.txt)
**Request Header:**[req-header.txt](https://github.com/usc-isi-i2/Web-Karma/files/1158139/req-header.txt)
**Request Body:**[req-body.txt](https://github.com/usc-isi-i2/Web-Karma/files/1158138/req-body.txt)
**Response:**[response.txt](https://github.com/usc-isi-i2/Web-Karma/files/1158140/response.txt)

**Comment by rutujarane** [comment]
Please reopen this issue if you are still facing this problem.
Closing.
