### ISSUE TITLE
Paper about karma Evaluation

### ISSUE THREAD

**Issue by felixneto** [usc-isi-i2/Web-Karma#345]
I am sorry to open an issue for that, but I am a student and I am evaluating the availability of use the karma in project. I am trying to find but I did not find a paper about web-Karma evaluation. The main evaluation I want to know how long karma takes to map or to translate a source with the map file into an ontology data ? I am interested in use the web-karma-services but I need some calculus.

Thank you.

**Comment by szeke** [comment]
http://www-scf.usc.edu/~taheriya/papers/taheriyan14-icsc-paper.pdf
http://www-scf.usc.edu/~taheriya/papers/taheriyan13-iswc-paper.pdf

**Comment by szeke** [comment]
We don't have a comprehensive evaluation of efficiency
