### ISSUE TITLE
Saving RDF to triple store status 204

### ISSUE THREAD

**Issue by deeMaj** [usc-isi-i2/Web-Karma#346]
I was following the karma-tcdl-tutorial and I keep getting the error No Content and when I click on R2RML Model  I get an HTTP 404 error. My Maven and Java environments are installed as instructed, cannot understand what the problem is. Can someone help me out with this 
![tomcat](https://user-images.githubusercontent.com/24408529/29207015-c564a47c-7e84-11e7-8814-975a0b460603.JPG)

**Comment by dkapoor** [comment]
Are you running Karma on a Windows machine?
If you are, can you try the settings mentioned in here: https://github.com/usc-isi-i2/Web-Karma/wiki/Troubleshooting for Question 5: `In Windows, when I re-publish my model or JSON or any other file, it gives me an Error and is not able to perform the operation `

Thanks.

**Comment by deeMaj** [comment]
Hi, Thanks a lot for responding, we were trying to install Karma with the one click option and getting the errors,  finally we decided to use the Source Code installation and that has worked out perfectly. This error was appearing in a Windows machine, but there was some error with the one click install option even on a Mac. But the Source Code Installations solved both problems.
Thanks.
