### ISSUE TITLE
Could not load RDF data into VIVO from Karma RDF file

### ISSUE THREAD

**Issue by mgcarrel50** [usc-isi-i2/Web-Karma#348]
I created a model from a one-
[one-people.zip](https://github.com/usc-isi-i2/Web-Karma/files/1256997/one-people.zip)

person spreadsheet for import into VIVO.  Karma creates a file named WSP2WS5.ttl (see attached) when I do an RDF export. When I try to import it into VIVO it gives the error message:
Could not load from file: edu.cornell.mannlib.vitro.webapp.rdfservice.RDFServiceException: org.apache.jena.riot.RiotException: Element or attribute do not match QName production: QName::=(NCName':')?NCName.

Does anybody know what this error message means?
Thanks,
Mike
[WSP2WS5-ttl-Copy.txt](https://github.com/usc-isi-i2/Web-Karma/files/1256990/WSP2WS5-ttl-Copy.txt)

**Comment by marijane** [comment]
Hi Mike, I'm a Karma user, a member of the OpenRIF community that maintains the VIVO ontology, and a member of the VIVO community.  What version of the VIVO software are you using, and do you know what version of the VIVO ontology you are using?

**Comment by mgcarrel50** [comment]
Hi Marijane, We have moved on to another solution for our project.
Thank you for responding.
Regards,
Mike
