### ISSUE TITLE
FAILED TO GET RFD

### ISSUE THREAD

**Issue by PedroMoreo** [usc-isi-i2/Web-Karma#352]
hello,

I am new in Karma, I am just trying to do some samples, and when I try to publish the RDF model, and click over the link in the worksheet,  I just obtain:

Estado HTTP 404 - /publish/RDF/WSP1WS338.ttl

I don't know what could be the error.

**Comment by kaushalv274** [comment]
Hi Perdro,

Can you please attach zip of your karma home folder and exact steps (commands executed) you followed before publishing RDF model. 

Thanks
Kaushal

**Comment by dkapoor** [comment]
Also, are you running Karma on Windows using the installer? If so, it could be that the folder in which you installed has space in the folder name which has caused problems before. Can you check and reinstall if that is the case in a folder path with no spaces.

Thanks.

**Comment by rutujarane** [comment]
Please reopen this issue if you are still facing this problem.
Closing.
