### ISSUE TITLE
Literal type is not getting fetched from ontology

### ISSUE THREAD

**Issue by kapiljadhav** [usc-isi-i2/Web-Karma#355]
I have to manually select the literal type from the drop down on set semantictypes dialogue while mapping a column to model.

Why this is not automatically populated based on the type specified in ontology?

Following is the sample from model I am using.

 <rdf:Description rdf:about="http://example.com/ontologies/Person/age">
    <rdfs:domain rdf:resource="http://example.com/ontologies/Person"/>
    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#DatatypeProperty"/>
    <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#int"/>
  </rdf:Description>

**Comment by dkapoor** [comment]
Right now the Literal type list is a static list of XML schema types. We do not auto-load it from the Ontology or auto-set it in the Semantic type dialog.

Will mark this as a feature that we could add.
