### ISSUE TITLE
Error with one click installation

### ISSUE THREAD

**Issue by prachiagrawalusc** [usc-isi-i2/Web-Karma#358]
I am getting this error even after installing jdk multiple times.
![error](https://user-images.githubusercontent.com/32467361/31359124-80d38646-acfd-11e7-90c9-baddc4eea0cb.PNG)

**Comment by dkapoor** [comment]
It seems like you are using JDK 9. Karma does not support that as yet. Can you install JDK 8 and try again. Thanks.

**Comment by kaushalv274** [comment]
@prachiagrawalusc, are you still facing this issue ??

Thanks

**Comment by prachiagrawalusc** [comment]
No, Thanks.
