### ISSUE TITLE
Problem with publishing RDF/model

### ISSUE THREAD

**Issue by bradziko** [usc-isi-i2/Web-Karma#360]
Hello,
Issue was raised by Pedro Moreo yet he didn't provide any specific informations. I am using one click install Karma. After I loaded some csv file, ontologies, I set semantic types following some yt tutorial, I clicked publish RDF and then after i wanted to view my triples got 404 error: HTTP Status 404 - /publish/RDF/WSP1WS5.ttl    same with json and model. Maybe this is somewhat involved with OpenRDF workbench I don't know I'm not an expert. 
Is there any way of generating it to local folder?
I'm uploading karma folder as requested in the other thread
[karma.zip](https://github.com/usc-isi-i2/Web-Karma/files/1429027/karma.zip)

Thanks,
Bartek

**Comment by dkapoor** [comment]
Hi Bartek,

When Karma starts, it shows what is is using an Catalina home. 
![screen shot 2017-10-31 at 1 39 46 pm](https://user-images.githubusercontent.com/1852707/32248013-872ca63a-be41-11e7-8447-cd9f5da7203a.png)

For example in this screenshot it says `-Dcatalina.home=/Applications/Karma.app/Contents/Resources/app/tomcat`.

Can you check if you have the folder `webapps/ROOT/publish` under your catalina home? It will have subfolders AVRO, CSV, JSON, R2RML, RDF etc.
For this case it will be 
`/Applications/Karma.app/Contents/Resources/app/tomcat/webapps/ROOT/publish`

Can you let me know what your Catalina home is and if you have the publish folder and its sub-folders?

Thanks
Dipsy

**Comment by Cheng-Lin-Li** [comment]
Hi Bartek & Dipsy:

I have the same issue on windows 10 platform.
Based on Dipsy's suggestion, I found the ROOT folder was not established.
For me, the ROOT folder is not exists under c:\Karma-Windows\resources\app\tomcat\webapps\
There is a ROOT.war file and I think it did not deploy into the folder.

I manually change the ROOT.war to ROOT.zip, extract the zip file under the folder of webapps, restart Karma to resolve this issue.

By the way, except to review the deployment script on windows, you may also need to review those folder under ROOT/publish/*. A lot of historical files are located in each folder and you may want to remove them.

Thanks,
Cheng-Lin Li

**Comment by dkapoor** [comment]
Thanks Cheng-Lin, we have removed the extra files from the new installers, and now have a fix for windows installer for ROOT.war.
