### ISSUE TITLE
Ontology Incompatible with Karma

### ISSUE THREAD

**Issue by AustinTapp** [usc-isi-i2/Web-Karma#361]
Hi Karma Team,

I am having some trouble setting semantic types for my ontology.  When I upload the ontology, I am told the import is successful. Then I upload the .csv file, which populates into Karma exactly how I would like. However, when I go to set semantic types, I am only given the option "owl:Thing1 (add)" (screenshots attached).  I do not seem to have this problem when using other published ontologies and I follow this same process.  What am I missing from my ontology that is not allowing me to edit my data in Karma?

I am unable to attach my .csv and my OWL files because github does not support this file type.  Please advise on how/if you would like to view these files.

Thanks for your help.

Best,
Austin

<img width="1680" alt="screen shot 2017-11-01 at 2 42 58 pm" src="https://user-images.githubusercontent.com/29557420/32291436-6bc99b5a-bf13-11e7-9382-c2e536fb46ad.png">
<img width="1680" alt="screen shot 2017-11-01 at 2 43 09 pm" src="https://user-images.githubusercontent.com/29557420/32291437-6bdb01ce-bf13-11e7-9c93-85018ccdc67e.png">

**Comment by dkapoor** [comment]
Can you zip your ontology file and then attach it.

Thanks
