### ISSUE TITLE
connect to Postgresql/PostGis

### ISSUE THREAD

**Issue by csae8092** [usc-isi-i2/Web-Karma#362]
Not sure if this wasn't already mentioned in issue #133 but when I try to import a Database Table from a postgresql db (with postgis extension installed) I get the error message 

> The driver for PostGIS was not found. Please add the driver to the path and try again

Could you maybe point out which Driver is needed, where I can get it from and where to put it. 
I am using Karma 2.053 on windows (10) but we are also running Karma on Linux (CentOS)

Thank you very much!

**Comment by dariok** [comment]
Assuming you used the 'One click install' and extracted it somewhere. Navigate to that folder and further to resources, app where you will find jre1.x... and a folder 'lib' within. Copy the whole path to the lib folder.

Download the current PostgreSQL JDBC driver from https://jdbc.postgresql.org/download.html and put it into the lib folder.

In the main Karma window, navigate to "File", "Set Java Home". Paste the path you just copied, click okay and restart Karma. You should now be able to open a DB connection.

**Comment by csae8092** [comment]
Thank you!! That was it.
