### ISSUE TITLE
Ontology missing imported terms

### ISSUE THREAD

**Issue by megankatsumi** [usc-isi-i2/Web-Karma#364]
Hello,
I am running into a bit of an issue when I try to model my data. The ontology that I would like to use is comprised of a number of other ontologies that are imported, however it doesn't seem that I'm able to reference any of the terms from the imported ontologies. Have I done something wrong in the import? Is there some way to enable this in Karma?

Thank you,
Megan

**Comment by marijane** [comment]
Hi Megan, I am a Karma user and I might be able to answer your question.

IIRC, I too had this problem when I started using Karma. I believe you can get around it by either importing all of the imported ontologies into Karma manually, or you can use a tool like the [OBO Foundry's ROBOT tool](http://robot.obolibrary.org/) to make a merged ontology file to import.
