### ISSUE TITLE
Preloaded ontologies

### ISSUE THREAD

**Issue by hlong35** [usc-isi-i2/Web-Karma#365]
I placed my ontologies in C:\Users\username\karma\preloaded-ontologies. However, the ontologies are not displaying in the left column. I'm new to Karma-- Can someone suggest what is going wrong? (I installed the one-click installation on Windows). Thanks in advance.

**Comment by kaushalv274** [comment]
Hi, 

Sorry for the late reply. 

Ontologies are not showed in karma window. You should be able to all available semantic types when you model your data.
