### ISSUE TITLE
How to use karma-spark to generate RDF?

### ISSUE THREAD

**Issue by lettrung99** [usc-isi-i2/Web-Karma#366]
Hello,

I am new to Karma, and I am not sure if there is a forum to ask questions.  Please let me know if there is one.

One of the wikis claims that we can use the published  "R2RML" model to generate RDF using spark cluster.

Could someone help me with some more details on this?

Thanks.

**Comment by kaushalv274** [comment]
Hi, 

You can ask questions here on github. 

First you need to install Karma, model your data and generate R2RML (model) files. After that you can apply model files on your data. (on spark cluster). 

For modeling and installation, you can follow https://github.com/usc-isi-i2/Web-Karma/wiki 
and for second part you should follow https://github.com/usc-isi-i2/Web-Karma/wiki/Working-with-Karma-using-Map-Reduce. 

Thanks
