### ISSUE TITLE
Dockerizing Karma; Can't resolve dependencies. 

### ISSUE THREAD

**Issue by mlinsky** [usc-isi-i2/Web-Karma#367]
```
FROM maven:3-jdk-7
MAINTAINER Antonio De Marinis <demarinis@eea.europa.eu>

LABEL Description="This image is used to start a Web-Karma server see http://usc-isi-i2.github.io/karma/" \
      eu.eea.europa.is-beta=true

# confirm git is installed
RUN apt-get install -y git

RUN git clone https://github.com/usc-isi-i2/Web-Karma.git

RUN cd Web-Karma \
    && mvn clean install

ENV MAVEN_HOME /usr/share/maven

EXPOSE 8080
WORKDIR /Web-Karma/karma-web

CMD ["mvn","jetty:run", "-X"]

```

I am able to run the program locally but it fails when i try to run it in the docker conatiner. I was trying to use this Dockerfile someone used, which I posted above, and it keep error-ing out because of dependencies. I will post the error in a comment because it is quite long. The error does give an underlining 409 because it cannot find `http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom`. I was looking around on the site and saw that at the point of `http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi` in the directory the only option after was karma not karma-web. The exact process I do is written below.

```
#while in the direcory of the Dockerfile
docker build -t web-karma .
docker run -t web-karma
```

**Comment by amalic** [comment]
Hi I had a different issue (some version conflict). Tried to compile it with jdk-8 --> SUCCESS

### Dockerfile
```Dockerfile
FROM maven:3-jdk-8

LABEL maintainer <alexander.malic [at] maastrichtuniversity.nl>

WORKDIR /app
RUN git clone https://github.com/usc-isi-i2/Web-Karma.git && \
  cd Web-Karma && \
  mvn clean install

WORKDIR /app/Web-Karma/karma-web
RUN mvn install

EXPOSE 8080

ENTRYPOINT ["mvn", "jetty:run"]
```

### Build
`$ docker build -t .`

### Run
`$ docker run -d --rm -p 8080:8080 karma`

**Comment by rutujarane** [comment]
Please reopen this issue if you are still facing this problem.
Closing.
