### ISSUE TITLE
Error with One-Click Install - Karma Release v2.052 - MacOSX

### ISSUE THREAD

**Issue by kateblanch** [usc-isi-i2/Web-Karma#368]
Hello! I'm not sure the best place to seek help for an error, but hoping you can help. After installing Karma via the one-click installer package, and starting it from the applications folder, I get this error. 
Any ideas?
Thanks!

HTTP Status 500 - javax.servlet.ServletException: java.lang.UnsupportedClassVersionError: edu/isi/karma/config/UIConfigurationRegistry : Unsupported major.minor version 51.0 (unable to load class edu.isi.karma.config.UIConfigurationRegistry)

type Exception report

message javax.servlet.ServletException: java.lang.UnsupportedClassVersionError: edu/isi/karma/config/UIConfigurationRegistry : Unsupported major.minor version 51.0 (unable to load class edu.isi.karma.config.UIConfigurationRegistry)

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: javax.servlet.ServletException: java.lang.UnsupportedClassVersionError: edu/isi/karma/config/UIConfigurationRegistry : Unsupported major.minor version 51.0 (unable to load class edu.isi.karma.config.UIConfigurationRegistry)
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:561)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:462)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
root cause

javax.servlet.ServletException: java.lang.UnsupportedClassVersionError: edu/isi/karma/config/UIConfigurationRegistry : Unsupported major.minor version 51.0 (unable to load class edu.isi.karma.config.UIConfigurationRegistry)
	org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:916)
	org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:845)
	org.apache.jsp.index_jsp._jspService(index_jsp.java:847)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
root cause

java.lang.UnsupportedClassVersionError: edu/isi/karma/config/UIConfigurationRegistry : Unsupported major.minor version 51.0 (unable to load class edu.isi.karma.config.UIConfigurationRegistry)
	org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:3200)
	org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:1373)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1861)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:126)
	org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:63)
	org.apache.jsp.index_jsp._jspService(index_jsp.java:201)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.72 logs.

Apache Tomcat/7.0.72

**Comment by dkapoor** [comment]
Can you type `java -version` on a console window and let us know what version of Java you have?

Thanks.

**Comment by kateblanch** [comment]
Thanks for the fast reply!! 

java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
ifat-dfc-2837:~ kblanch$

**Comment by kateblanch** [comment]
I see from the user guide I need Java 1.7 or higher...let me troubleshoot that.

**Comment by kateblanch** [comment]
Ok, updated Java. Terminal java -version returns this: 
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
ifat-dfc-2837:~ kblanch$ 

When I restart Karma, I get this error.
HTTP Status 500 - javax.servlet.ServletException: java.lang.UnsupportedClassVersionError: edu/isi/karma/config/UIConfigurationRegistry

type Exception report

message javax.servlet.ServletException: java.lang.UnsupportedClassVersionError: edu/isi/karma/config/UIConfigurationRegistry

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: javax.servlet.ServletException: java.lang.UnsupportedClassVersionError: edu/isi/karma/config/UIConfigurationRegistry
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:561)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:462)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
root cause

javax.servlet.ServletException: java.lang.UnsupportedClassVersionError: edu/isi/karma/config/UIConfigurationRegistry
	org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:916)
	org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:845)
	org.apache.jsp.index_jsp._jspService(index_jsp.java:847)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
root cause

java.lang.UnsupportedClassVersionError: edu/isi/karma/config/UIConfigurationRegistry
	org.apache.jsp.index_jsp._jspService(index_jsp.java:201)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.72 logs.

Apache Tomcat/7.0.72

**Comment by kateblanch** [comment]
Greetings! I have tried to sort out Java versioning. Still stuck. On a whim, tagging @caknoblock to see if he can help me untangle this or direct me to someone who could help. Disclaimer: I'm primarily a Windows admin, so this is a new OS for me. 

When I try to Set Java Home from the Karma menu, I get an "invalid path for java" message. 
Here is my path:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

Here is the error that Karma now throws:
Starting Karma...
-Djava.endorsed.dirs=/Applications/Karma.app/Contents/Resources/app/tomcat/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Launching Karma. Go to http://localhost:8080 if it doesn't launch.

**Comment by dkapoor** [comment]
Can you type
```
/usr/libexec/java_home -v 1.9
```
on your console. This would give you the location of your 1.9 JVM. Can you copy that and set that as the Java Home in the Karma Menu and try again.

The correct Java home would look like: `/Library/Java/JavaVirtualMachines/<jre/jdk version>/Contents/Home`

**Comment by dkapoor** [comment]
Can you first try to set the Java Home in Karma as `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home` instead and then restart Karma and see if that works.

If that doesnt, maybe we need to downgrade to JDK 1.8 and try.
For that, could you install JDK 8 - http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html 

And then type
```
/usr/libexec/java_home -v 1.8
```
on your console. This would give you the location of your 1.8 JVM. Can you copy that and set that as the Java Home in the Karma Menu and try again.

The correct Java home would look like: `/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home`

**Comment by kateblanch** [comment]
Hi Dipsy, thanks so much for the reply. This totally worked -- set the Java Home in Karma as /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home instead and then restart Karma. 
I am up and running on Mac OS -- thanks so much and happy holidays :)!
