### ISSUE TITLE
not all properties available

### ISSUE THREAD

**Issue by bitno** [usc-isi-i2/Web-Karma#369]
Dear Karma team,
I can't choose rdf:value in properties. I've tried several versions of Karma and was never successful in making it available under properties. I can take any other property and then edit it to rdf:value and after a few uses it gets recommended, but it won't work in the normal process. Any ideas?

Btw I love your tool, many thanks!

Kind regards, 
Leo
![rdf_not_available](https://user-images.githubusercontent.com/15378927/35287545-dc3bc2e2-0062-11e8-9697-c1533f449c56.png)

**Comment by dkapoor** [comment]
Hi Leo,
This was a bug in Karma as it was considering rdf:value as only an Object Property, and so not showing it initially in the Set Semantic Type dialog.
We have fixed this and now it will be considered an Object and Data Property and show up in the dialog.
The fix however is right now in our development branch and will be available in One-Click installer when we make a release. If however you want to get the fix, you would need to Build karma from [source](https://github.com/usc-isi-i2/Web-Karma/wiki/Installation%3A-Source-Code) .
After Step 2 of the install, before running `mvn clean install`, you would need to switch to the development branch
```
git checkout development
git pull
```
and then continue with the rest of the steps:
```
mvn clean install
cd karma-web
mvn jetty:run
```

**Comment by bitno** [comment]
Dear @dkapoor 
Working on dev worked, rdf:value is available. 
Many thanks!
