### ISSUE TITLE
PyTransform and special characters

### ISSUE THREAD

**Issue by bitno** [usc-isi-i2/Web-Karma#370]
Dear Karma team,

Is there a way on how I could enable special characters in PyTransform?
I'm using the replace function, but can't make german umlauts like äöü work within it.

Many thanks for your help and kind regards,
Leo
![umlaut_issue_pytransform](https://user-images.githubusercontent.com/15378927/35384218-e99e51da-01c4-11e8-8554-b9422252ed88.png)

**Comment by kaushalv274** [comment]
Hi, 

Please append 'u' before the string which contains german characters. 

For example if you want to replace with "äöABC" then you should write u"äöABC". (character u should be out of quotes.)

Thanks
Kaushal

**Comment by bitno** [comment]
Dear @kaushalv274 

Many thanks, this worked! Your help is really appreciated. 

Regarding issue #322 : Do you have any idea why special characters don't get exported correctly?
Again many many thanks
