### ISSUE TITLE
ERROR when running karma-web

### ISSUE THREAD

**Issue by iliecristian** [usc-isi-i2/Web-Karma#373]
I am using Ubuntu 16.04 LTS and with 4-5 weeks ago I installed successfully Karma. It was running with no problem. Now if I run **mvn jetty:run** command (even with sudo) I receive the following error:

`[ERROR] Failed to execute goal on project karma-web: Could not resolve dependencies for project edu.isi:karma-web:war:0.0.1-SNAPSHOT: Failed to collect dependencies at edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Failed to read artifact descriptor for edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Could not transfer artifact edu.isi:karma-common:pom:0.0.1-SNAPSHOT from/to KarmaRepo (http://repo.karma.isi.edu/artifactory/libs-release-local): Failed to transfer file: http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]`

**Comment by dkapoor** [comment]
It seems that the required dependencies were not built successfully. 
Can you switch back to the main `Web-Karma` folder, and run `mvn clean install` there. If that is successful, then do:
```
cd karma-web
mvn jetty:run
```
If any stage fails again, Please copy paste the log and also the output of your `mvn --version` command here.
Thank you.

**Comment by iliecristian** [comment]
I have the same problem after I run `mvn clean install`
Here is the log:
`ilie@ilie-X550JK:~/workspace/maven/WebKarma-master/karma-web$ mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building karma-web 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.1/exec-maven-plugin-1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.1/exec-maven-plugin-1.1.pom (4 KB at 9.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo/17/mojo-17.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo/17/mojo-17.pom (17 KB at 157.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.1/exec-maven-plugin-1.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.1/exec-maven-plugin-1.1.jar (27 KB at 309.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (4 KB at 51.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom (13 KB at 161.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom (26 KB at 321.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom (15 KB at 180.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar (25 KB at 289.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom (8 KB at 67.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom (9 KB at 119.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom (30 KB at 354.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom (15 KB at 183.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar (29 KB at 369.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom (10 KB at 129.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom (11 KB at 137.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/23/maven-parent-23.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/23/maven-parent-23.pom (32 KB at 388.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/13/apache-13.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/13/apache-13.pom (14 KB at 184.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.jar (42 KB at 505.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.17/maven-surefire-plugin-2.17.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.17/maven-surefire-plugin-2.17.pom (5 KB at 64.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.17/surefire-2.17.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.17/surefire-2.17.pom (17 KB at 216.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.17/maven-surefire-plugin-2.17.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.17/maven-surefire-plugin-2.17.jar (34 KB at 398.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.4/maven-war-plugin-2.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.4/maven-war-plugin-2.4.pom (10 KB at 120.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.4/maven-war-plugin-2.4.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.4/maven-war-plugin-2.4.jar (85 KB at 765.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.pom (7 KB at 84.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/25/maven-plugins-25.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/25/maven-plugins-25.pom (10 KB at 126.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/24/maven-parent-24.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/24/maven-parent-24.pom (37 KB at 444.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/14/apache-14.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/14/apache-14.pom (15 KB at 183.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.jar (33 KB at 276.4 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom (17 KB at 80.0 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/apache/commons/commons-parent/22/commons-parent-22.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/commons/commons-parent/22/commons-parent-22.pom (41 KB at 338.3 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/apache/apache/9/apache-9.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/apache/9/apache-9.pom (15 KB at 185.1 KB/sec)
Downloading: http://repo1.maven.org/maven2/de/micromata/jak/JavaAPIforKml/2.2.0/JavaAPIforKml-2.2.0.pom
Downloaded: http://repo1.maven.org/maven2/de/micromata/jak/JavaAPIforKml/2.2.0/JavaAPIforKml-2.2.0.pom (9 KB at 109.4 KB/sec)
Downloading: http://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2/jaxb-impl-2.2.pom
Downloaded: http://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2/jaxb-impl-2.2.pom (337 B at 4.3 KB/sec)
Downloading: http://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.2/jaxb-api-2.2.pom
Downloaded: http://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.2/jaxb-api-2.2.pom (486 B at 5.9 KB/sec)
Downloading: http://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.pom
Downloaded: http://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.pom (962 B at 12.2 KB/sec)
Downloading: http://repo1.maven.org/maven2/javax/activation/activation/1.1/activation-1.1.pom
Downloaded: http://repo1.maven.org/maven2/javax/activation/activation/1.1/activation-1.1.pom (2 KB at 13.4 KB/sec)
Downloading: http://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-xjc/2.2/jaxb-xjc-2.2.pom
Downloaded: http://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-xjc/2.2/jaxb-xjc-2.2.pom (339 B at 4.3 KB/sec)
Downloading: http://repo1.maven.org/maven2/xmlunit/xmlunit/1.2/xmlunit-1.2.pom
Downloaded: http://repo1.maven.org/maven2/xmlunit/xmlunit/1.2/xmlunit-1.2.pom (3 KB at 33.8 KB/sec)
Downloading: http://download.osgeo.org/webdav/geotools/edu/isi/karma-common/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://repository.cloudera.com/artifactory/cloudera-repos/edu/isi/karma-common/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo1.maven.org/maven2/edu/isi/karma-common/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo1.maven.org/maven2/edu/isi/karma-common/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/karma-common/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo1.maven.org/maven2/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom
Downloading: https://repository.cloudera.com/artifactory/cloudera-repos/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom
Downloading: http://download.osgeo.org/webdav/geotools/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom
Downloading: http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom
Downloading: http://repo1.maven.org/maven2/edu/isi/commands-include/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://repository.cloudera.com/artifactory/cloudera-repos/edu/isi/commands-include/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo1.maven.org/maven2/edu/isi/commands-include/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://download.osgeo.org/webdav/geotools/edu/isi/commands-include/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/commands-include/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repo1.maven.org/maven2/edu/isi/commands-include/0.0.1-SNAPSHOT/commands-include-0.0.1-SNAPSHOT.pom
Downloading: https://repository.cloudera.com/artifactory/cloudera-repos/edu/isi/commands-include/0.0.1-SNAPSHOT/commands-include-0.0.1-SNAPSHOT.pom
Downloading: http://download.osgeo.org/webdav/geotools/edu/isi/commands-include/0.0.1-SNAPSHOT/commands-include-0.0.1-SNAPSHOT.pom
Downloading: http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/commands-include/0.0.1-SNAPSHOT/commands-include-0.0.1-SNAPSHOT.pom
Downloading: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/9.0.5.v20130815/jetty-server-9.0.5.v20130815.pom
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/9.0.5.v20130815/jetty-server-9.0.5.v20130815.pom (4 KB at 35.8 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-project/9.0.5.v20130815/jetty-project-9.0.5.v20130815.pom
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-project/9.0.5.v20130815/jetty-project-9.0.5.v20130815.pom (27 KB at 217.8 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-parent/20/jetty-parent-20.pom
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-parent/20/jetty-parent-20.pom (21 KB at 255.6 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.pom
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.pom (732 B at 10.5 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/eclipse/jetty/orbit/jetty-orbit/1/jetty-orbit-1.pom
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jetty/orbit/jetty-orbit/1/jetty-orbit-1.pom (3 KB at 30.8 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-parent/18/jetty-parent-18.pom
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-parent/18/jetty-parent-18.pom (17 KB at 203.9 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/9.0.5.v20130815/jetty-http-9.0.5.v20130815.pom
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/9.0.5.v20130815/jetty-http-9.0.5.v20130815.pom (3 KB at 36.1 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/9.0.5.v20130815/jetty-util-9.0.5.v20130815.pom
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/9.0.5.v20130815/jetty-util-9.0.5.v20130815.pom (4 KB at 47.9 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/9.0.5.v20130815/jetty-io-9.0.5.v20130815.pom
Downloaded: http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/9.0.5.v20130815/jetty-io-9.0.5.v20130815.pom (3 KB at 31.9 KB/sec)
Downloading: http://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.pom
Downloaded: http://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.pom (13 KB at 173.8 KB/sec)
Downloading: http://repo1.maven.org/maven2/net/java/jvnet-parent/1/jvnet-parent-1.pom
Downloaded: http://repo1.maven.org/maven2/net/java/jvnet-parent/1/jvnet-parent-1.pom (5 KB at 67.7 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/powermock/powermock-module-junit4/1.5.2/powermock-module-junit4-1.5.2.pom
Downloaded: http://repo1.maven.org/maven2/org/powermock/powermock-module-junit4/1.5.2/powermock-module-junit4-1.5.2.pom (2 KB at 19.3 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/powermock/powermock-modules/1.5.2/powermock-modules-1.5.2.pom
Downloaded: http://repo1.maven.org/maven2/org/powermock/powermock-modules/1.5.2/powermock-modules-1.5.2.pom (798 B at 10.7 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/powermock/powermock/1.5.2/powermock-1.5.2.pom
Downloaded: http://repo1.maven.org/maven2/org/powermock/powermock/1.5.2/powermock-1.5.2.pom (10 KB at 136.0 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
Downloaded: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/5/oss-parent-5.pom (4 KB at 57.8 KB/sec)
Downloading: http://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.pom
Downloaded: http://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.pom (3 KB at 34.2 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
Downloaded: http://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom (766 B at 10.8 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
Downloaded: http://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom (2 KB at 27.1 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/powermock/powermock-module-junit4-common/1.5.2/powermock-module-junit4-common-1.5.2.pom
Downloaded: http://repo1.maven.org/maven2/org/powermock/powermock-module-junit4-common/1.5.2/powermock-module-junit4-common-1.5.2.pom (2 KB at 15.6 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/powermock/powermock-core/1.5.2/powermock-core-1.5.2.pom
Downloaded: http://repo1.maven.org/maven2/org/powermock/powermock-core/1.5.2/powermock-core-1.5.2.pom (2 KB at 26.4 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/powermock/powermock-reflect/1.5.2/powermock-reflect-1.5.2.pom
Downloaded: http://repo1.maven.org/maven2/org/powermock/powermock-reflect/1.5.2/powermock-reflect-1.5.2.pom (2 KB at 14.1 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/objenesis/objenesis/1.2/objenesis-1.2.pom
Downloaded: http://repo1.maven.org/maven2/org/objenesis/objenesis/1.2/objenesis-1.2.pom (3 KB at 42.6 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/objenesis/objenesis-parent/1.2/objenesis-parent-1.2.pom
Downloaded: http://repo1.maven.org/maven2/org/objenesis/objenesis-parent/1.2/objenesis-parent-1.2.pom (11 KB at 136.6 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/javassist/javassist/3.18.0-GA/javassist-3.18.0-GA.pom
Downloaded: http://repo1.maven.org/maven2/org/javassist/javassist/3.18.0-GA/javassist-3.18.0-GA.pom (9 KB at 121.1 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/powermock/powermock-api-mockito/1.5.2/powermock-api-mockito-1.5.2.pom
Downloaded: http://repo1.maven.org/maven2/org/powermock/powermock-api-mockito/1.5.2/powermock-api-mockito-1.5.2.pom (2 KB at 17.3 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/powermock/powermock-api/1.5.2/powermock-api-1.5.2.pom
Downloaded: http://repo1.maven.org/maven2/org/powermock/powermock-api/1.5.2/powermock-api-1.5.2.pom (805 B at 11.4 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.pom
Downloaded: http://repo1.maven.org/maven2/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.pom (2 KB at 14.9 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/powermock/powermock-api-support/1.5.2/powermock-api-support-1.5.2.pom
Downloaded: http://repo1.maven.org/maven2/org/powermock/powermock-api-support/1.5.2/powermock-api-support-1.5.2.pom (2 KB at 17.2 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.174 s
[INFO] Finished at: 2018-03-14T06:51:29+02:00
[INFO] Final Memory: 12M/191M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project karma-web: Could not resolve dependencies for project edu.isi:karma-web:war:0.0.1-SNAPSHOT: Failed to collect dependencies at edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Failed to read artifact descriptor for edu.isi:karma-common:jar:0.0.1-SNAPSHOT: Could not transfer artifact edu.isi:karma-common:pom:0.0.1-SNAPSHOT from/to KarmaRepo (http://repo.karma.isi.edu/artifactory/libs-release-local): Failed to transfer file: http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/karma-common/0.0.1-SNAPSHOT/karma-common-0.0.1-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

And that is maven version:
`ilie@ilie-X550JK:~/workspace/maven/WebKarma-master/karma-web$ mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-36-generic", arch: "amd64", family: "unix"
ilie@ilie-X550JK:~/workspace/maven/WebKarma-master/karma-web$`

**Comment by dkapoor** [comment]
I see the problem. As you can see you are running `mvn clean install` from the `karma-web` folder (Your `/workspace/maven/WebKarma-master/karma-web` folder). You need to run it from the main `Web-Karma` folder.
So please do:
```
cd ..
mvn clean install
cd karma-web
mvn jetty:run
```

**Comment by iliecristian** [comment]
My bad.
It works. Thanks for support.

**Comment by rajendraprasadyk** [comment]
Failed to execute goal on project karma-util: Could not resolve dependencies for project edu.isi:karma-util:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.json:json:jar:20131018: Failed to read artifact descriptor for org.json:json:jar:20131018: Could not transfer artifact org.json:json:pom:20131018 from/to central (http://repo1.maven.org/maven2/): Failed to transfer file: http://repo1.maven.org/maven2/org/json/json/20131018/json-20131018.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. ->
