### ISSUE TITLE
IRI as literal type

### ISSUE THREAD

**Issue by bitno** [usc-isi-i2/Web-Karma#374]
Dear Karma community,

I'm using skos:exactMatch to point to other available sources on the web. But these mappings get exported as strings and not IRIs. Any idea, where I could define the type of the content?
Or is there another way how to work with skos:exactMatch?

The output looks like:
<http://localhost:8080/source/actor/6adbcfca-35bf-4454-a046-68cc675a19a1> <http://www.w3.org/2004/02/skos/core#exactMatch> "https://www.wikidata.org/wiki/Q762" .

But should look like:
<http://localhost:8080/source/actor/6adbcfca-35bf-4454-a046-68cc675a19a1> <http://www.w3.org/2004/02/skos/core#exactMatch>  <https://www.wikidata.org/wiki/Q762> .

And another related question: When setting the semantic type, skos:exactMatch is not available to choose from. So I have to pick another one and then change it to skos:exactMatch. Do you have an idea, why it is not loaded same as other properties?

If included the raw data as xlsx as well as all possible exports from Karma. I'm working on the latest dev branch.

Many thanks and kind regards,
Leo
[data.zip](https://github.com/usc-isi-i2/Web-Karma/files/1789705/data.zip)
![test_20180307_print_model](https://user-images.githubusercontent.com/15378927/37101477-ffd91cc4-2225-11e8-9c93-4ca7ffd3ed83.png)

![bildschirmfoto 2018-03-07 um 16 25 33](https://user-images.githubusercontent.com/15378927/37101502-0aeb4286-2226-11e8-97d7-38c672f50c90.png)
[Test_20180307-model.txt](https://github.com/usc-isi-i2/Web-Karma/files/1789711/Test_20180307-model.txt)
[Test_20180307.xlsx](https://github.com/usc-isi-i2/Web-Karma/files/1789712/Test_20180307.xlsx)

**Comment by dkapoor** [comment]
Hi Leo,

To get the wikidata as IRIs, you will need to model them as "URI" is a Class in Karma.
Attached is the updated model that does that and produces the triples that you are looking for:

```
<http://localhost:8080/source/actor/1de48eca-6f20-450f-8c77-99a8102b6e9f> <http://www.w3.org/2008/05/skos#exactMatch> <https://www.wikidata.org/wiki/Q5593> .
```
![screen shot 2018-03-13 at 10 54 57 am](https://user-images.githubusercontent.com/1852707/37360348-303f7c10-26ad-11e8-9a6d-4f450094f3aa.png)

[Test_20180307_Tabelle1-model.ttl.txt](https://github.com/usc-isi-i2/Web-Karma/files/1808090/Test_20180307_Tabelle1-model.ttl.txt)

**Comment by bitno** [comment]
Dear @dkapoor 
Many many thanks, this works great. 
Kind regards,
Leo
