### ISSUE TITLE
v2.1: Unable to load the mojo 'run'

### ISSUE THREAD

**Issue by turbomam** [usc-isi-i2/Web-Karma#380]
I'm really excited to try Karma 2.1

I just compiled it in Windows' WSL/Ubuntu emulation layer, but can't run it.  I was able to run Karma 2.0.53 in WSL.

> Execution default-cli of goal org.eclipse.jetty:jetty-maven-plugin:9.4.8.v20171121:run failed: Unable to load the mojo 'run' in the plugin 'org.eclipse.jetty:jetty-maven-plugin:9.4.8.v20171121' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/eclipse/jetty/maven/plugin/JettyRunMojo : Unsupported major.minor version 52.0

the reading I've done so far makes me think that it has to do with a mismatch between the expected and installed jdk.

does Karma 2.1 *support* Java 1.9, or does it *require* 1.9?

mark@DESKTOP-LA54B7U:~/karma_2_1/Web-Karma/karma-web$ java -version
java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-2ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.151-b01, mixed mode)

----

(The native Windows version does work for me.)

**Comment by rutujarane** [comment]
Please reopen this issue if you are still facing this problem.
Closing.
