### ISSUE TITLE
Do not get the full interface

### ISSUE THREAD

**Issue by PaulZH** [usc-isi-i2/Web-Karma#383]
Version 2.1, one-click install on Mac.
Do not get the full interface and nothing seems to happen. Restart button doesn't react either.

![screen shot 2018-04-04 at 16 23 13](https://user-images.githubusercontent.com/437781/38313635-ca4eb2de-3824-11e8-892c-a5bbf67c60ec.png)

I must be overlooking something trivival.

**Comment by kaushalv274** [comment]
Hi, 

Can you please tell us following details ?

(1) OS version 
(2) JAVA version on your computer

Thanks

**Comment by PaulZH** [comment]
1) 
System Version:	macOS 10.13.4 (17E199)
Kernel Version:	Darwin 17.5.0

Same happens on
macOS 10.12.6 (16G1314), Darwin 16.7.0

2)
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by reganartinfo** [comment]
:wave: I'm having the same error as well with the one-click install for Mac.

![screen shot 2018-04-05 at 1 52 22 pm](https://user-images.githubusercontent.com/25367492/38382687-9a3014a8-38d8-11e8-8df2-a7775765f18d.png)

I'm using macOS High Sierra (version 10.13.3) and Java Version 8 Update 161 (build 1.80_161-b12).

**Comment by dkapoor** [comment]
Can you move/copy your Karma.app to your "Applications" folder and then run Karma from there or the Launchpad? We were able to reproduce this issue and running it from Applications makes it work correctly. We will update our documentation to say likewise.
Thanks.

**Comment by reganartinfo** [comment]
Can confirm that this works now after moving Karma.app from out of the Karma-Mac subfolder in my Applications folder, although I had to manually set the Java Home too (see issue https://github.com/usc-isi-i2/Web-Karma/issues/368).

**Comment by PaulZH** [comment]
Indeed. Works fine from within the Applications folder.
