### ISSUE TITLE
Error retrieving column:

### ISSUE THREAD

**Issue by Nasreddine** [usc-isi-i2/Web-Karma#384]
Hi,

Using Karma-Web app I've created a mapping model for data retrieved from a web service. 
I wanted to generate RDF using Karma-Service using following curl command:

`curl --request POST --data 'R2rmlURI=http://localhost:9999/publish/R2RML/Test-model.ttl&ContentType=JSON&DataURL=https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522,151.1957362&radius=500&type=restaurant&key=KEY' http://localhost:8080/rdf/r2rml/rdf/sparql`

Service always returns: ERROR [qtp91831175-140] (KR2RMLMappingColumnNameHNodeTranslator.java:146) - Error retrieving column: name
However, the column is mapped in the model.

**Comment by rutujarane** [comment]
Old issue.
Please reopen this issue if you are still facing this problem.
Closing.
