### ISSUE TITLE
Issue with saving the model.

### ISSUE THREAD

**Issue by Gautamshahi** [usc-isi-i2/Web-Karma#385]
Kindly help me to rectify the issue.

![image](https://user-images.githubusercontent.com/3966230/39041507-8255f378-44a6-11e8-8c22-72ca245338fc.png)

**Comment by kaushalv274** [comment]
Hi, 

Can you please share logs with us? (should be on console)
And also send zipped Karma-Home folder. 

Thanks

**Comment by dkapoor** [comment]
It seems from the screen that you have not modeled anything as yet. You can follow our wiki here on how you can model your dataset and then try to publish the model: https://github.com/usc-isi-i2/Web-Karma/wiki/Modeling-Data
