### ISSUE TITLE
Split Values based on Double-Quote Delimiter

### ISSUE THREAD

**Issue by kateblanch** [usc-isi-i2/Web-Karma#386]
Hello! I'm trying to use the split values command to split a column with values delimited by a double quote:

1134"902

Where 1134 and 902 are two values that need to be split. 

I've tried this --
 regex: "\""
and the split is not working. Any idea what the right regex syntax would be? Thanks!

**Comment by dkapoor** [comment]
This would work:
```
regex:\"
```
