### ISSUE TITLE
Sometimes model is broken due to incomplete columns in data

### ISSUE THREAD

**Issue by GreatYYX** [usc-isi-i2/Web-Karma#387]
If model contains more columns than the data and update the model, the model sometimes breaks.

files:
ts-measure-2-model: original model
bio_mass data: some columns are missing
sample data: has all the columns

reproducing:
1. apply model to sample data, columns are modeled correctly
2. apply model to bio_mass data and save the model, the model is broken: some columns are not modeled. apply this saved model to sample data is also not correct.

[Archive.zip](https://github.com/usc-isi-i2/Web-Karma/files/2055136/Archive.zip)
karma home: https://github.com/usc-isi-i2/elicit_alignment/tree/master/m5/karma

**Comment by rutujarane** [comment]
Old issue.
Please reopen this issue if you are still facing this problem.
Closing.
