### ISSUE TITLE
Using KR2RML Programatically

### ISSUE THREAD

**Issue by Maatary** [usc-isi-i2/Web-Karma#389]
Hi, 

hereby i am reaching out, to ask if Kr2RML, can be used programmatically. If so If you have any guide around that. More over is it easily amenable to parallelization ?

**Comment by rutujarane** [comment]
Hi,
You can download the source code: https://github.com/usc-isi-i2/Web-Karma/wiki/Installation%3A-Source-Code
You can make changes programmatically and then run the web-app or use Karma-offline mode.
MapReduce can also be used for parallelization: https://github.com/usc-isi-i2/Web-Karma/wiki/Working-with-Karma-using-Map-Reduce
