### ISSUE TITLE
Mapping or referencing values between rows?

### ISSUE THREAD

**Issue by megankatsumi** [usc-isi-i2/Web-Karma#399]
Hello, I am trying to determine whether Karma is capable of supporting the functionality to not only define relationships between the attributes, but between certain rows. 
For example, say that each row defines the properties of an activity, but I also want to indicate that each activity (row) occurs after the previous one. Is this definable in Karma?
I suspect one way would be to create a new column (e.g. "next_activity") with the value of the id from the next row - is it possible to make this kind of reference in the creation of a new row (e.g. using PyTransform)?

Thank you,
Megan

**Comment by szeke** [comment]
This is not possible to do. Karma is designed to process one record at a time, and assumes that all records are independent of each other, if you reorder the records the result is the same. This enables Karma to work on multi-process environments where datasets can be partitioned and given to different machines running Karma.

The "solution" is to add a sequencing field before sending the data to Karma.
