### ISSUE TITLE
Port 8005 already used by Windows 10

### ISSUE THREAD

**Issue by TheMarmottin** [usc-isi-i2/Web-Karma#405]
Hello, 

I ran into an issue while trying to install Karma : since Windows 10, port 8005 is used by a system service. While trying to start Karma, tomcat realises that it can't use it as its shutdown port and immediately crashes, along with the console, so fast that the error message isn't readable (unless you promptly print the screen during the split second the error appears). 

It is very quick and easy to fix, the only thing required is changing the 8005 port in the server file, in resources/app/tomcat/conf into almost anything else. 

You might want to put a small line mentioning it in the installation instructions for windows 10 users (which are probably very few in numbers, i'll admit).

Thank you very much, and congratulations on this fantastic tool.
Quentin Monod

**Comment by GreatYYX** [comment]
Hi Quentin, which version of Karma are you using, precompiled Karma app or compiled from source code? I don't even know Karma uses 8005 (isn't it 8080 by default?). Karma's web service is powered by Jetty, so something like `mvn -Djetty.port=<PORT> jetty:run` can be used to change port.

**Comment by TheMarmottin** [comment]
Hi ! I'm using the precompiled one. Karma indeed uses port 8080 as a default, but the tomcat server needs two other ports aswell, if i remember correctly it is 8009 (or something), and 8005. 8005 is apparently used as a "shutdown" port (don't ask me). If you search windows + port 8005 on google, you'll find quite a lot of issues relating to a windows service always listening on said port.

**Comment by GreatYYX** [comment]
Thanks for letting us know. It may take a while for us to release a new version. FYI, self-compiled Karma uses Jetty so no need to worry about tomcat's shutdown port.

**Comment by Bidisha010496** [comment]
Hi , we have a new version of Karma and this issue doesn't seem to be there any longer. Please let me know if you see this issue again.
