### ISSUE TITLE
Apply R2RML Model file to CSV file

### ISSUE THREAD

**Issue by husseinlight** [usc-isi-i2/Web-Karma#407]
Would it be possible to use the R2RML model file obtained from the transformation(s) on an input CSV to get a modified CSV? If yes, would this be possible outside the Web app context of Karma?

**Comment by rutujarane** [comment]
Hi,
You could use the Karma-offline mode for the same. It doesn't use the web app.
You can follow something similar to this: https://github.com/usc-isi-i2/Web-Karma/wiki/Batch-Mode-for-RDF-Generation
Thanks!
