### ISSUE TITLE
Install Windows .exe Karma error

### ISSUE THREAD

**Issue by rafaelramosb** [usc-isi-i2/Web-Karma#409]
Estado HTTP 500 - org.ofbiz.core.util.GeneralRuntimeException: Could not determine database type. (File input/output error: java.io.IOException: org.hsqldb.HsqlException: Unexpected token: )

**Comment by GreatYYX** [comment]
Can you provide more detailed info? Like which version are you using, what's the full error stack, etc. Thanks.
