### ISSUE TITLE
Creating Classes and Labels within Karma

### ISSUE THREAD

**Issue by mlpotter** [usc-isi-i2/Web-Karma#418]
Currently I have Web-Karma up and running, and uploaded a test .csv file of data.

Currently, it appears that when I try to set Semantic Type I cannot create a custom class or custom property of the class within the GUI. Am I only allowed to select from the available classes and properties defined in the uploaded ontology files?

**Comment by caknoblock** [comment]
Yes, the current system requires you to add new classes or properties directly to the ontology before you can access them from within Karma.  We plan to add the ability to add these on the fly, but I don’t know how soon we will get to that task.
