### ISSUE TITLE
How to get suggested sematic label

### ISSUE THREAD

**Issue by ambikaraina7** [usc-isi-i2/Web-Karma#423]
After importing the dataset and ontology on karma, how do we automatically get the suggestion of the semantic label when we click on a column name? When I do this for the first time, I just get two basic semantic types, as shown in the attached image. Please help!
[image](https://user-images.githubusercontent.com/18361165/61338580-21f16000-a7ef-11e9-8654-a1a084cb32e7.png)

**Comment by caknoblock** [comment]
The system has to be trained before it will make suggestions.  Once it has seen previous examples of a semantic type, then it will propose ones based on the ones you have defined in previous examples.

**Comment by briantdu777** [comment]
I am sure that you already figured it out, but, if not:

You have to place ontologies in the pre-loaded ontologies, the tutorial here provides some under the karma folder:
```https://github.com/szeke/karma-tcdl-tutorial```

You can just take the pre-loaded ontologies and put it into 

```
~/karma/preloaded-ontologies
```
Then restart Karma and some suggestions will show up

Hope this helps!
