### ISSUE TITLE
Karma artificatory repo moved ?

### ISSUE THREAD

**Issue by Maatary** [usc-isi-i2/Web-Karma#427]
Can't reach http://repo.karma.isi.edu/artifactory/libs-release-local/org/geotools/gt-referencing ?

Please could you let me know what has changed ?

where is geotools hosted today

**Comment by rutujarane** [comment]
Hi,

I apologize for the late response.This issue has been fixed. 

GeoTools is being referenced from OSGeo Release Repository. The link for this is: https://repo.osgeo.org/repository/release/
You can refer to this link for more information: https://docs.geotools.org/latest/userguide/welcome/upgrade.html
