### ISSUE TITLE
Provide default mapping for un-mapped data points

### ISSUE THREAD

**Issue by venkateshzifo** [usc-isi-i2/Web-Karma#428]
Hi,

Is there an option to map the data points to a default property automatically if mapping is not done in the Karma UI ? If not please share an idea on how can we do this ?

Example Use case : JSON file have ID, Name, Department and Address and we have done ontology mapping in Karma UI for the data points ID and Name. In that case Department and Address (Un-Mapped fields) should be mapped to default property automatically.

**Comment by rutujarane** [comment]
You can create an ontology mapping of your file in Karma UI and save it. When you get a new file with the same schema, you can directly apply this ontology to the new file and it will take the mappings from that file by default.
Note: The new file should have the same schema as the original one.
