### ISSUE TITLE
Editing duplicated pytransforms does not take into effect

### ISSUE THREAD

**Issue by huerdong** [usc-isi-i2/Web-Karma#429]
Based on feedback from an end user, it appears that if a user is editing an existing model with multiple pytransform commands on the same field, Karma will not apply any changes the user makes to that field in either the UI or in the published model. Deleting the previous commands seems to fix this issue, which implies the problem is the command applications are defaulting to the some old command while ignoring others. 

This is potentially related to issue #332

**Comment by Bidisha010496** [comment]
Old issue and multiple pytransform columns seems to be working now .
