### ISSUE TITLE
failed to install Karma

### ISSUE THREAD

**Issue by caotrinh** [usc-isi-i2/Web-Karma#430]
May I ask someone can install and use Karma recently, I got this error when I install Karma these days which I was very successfull some months ago.
The error is 
<img width="860" alt="Screen Shot 2020-02-07 at 3 04 58 pm" src="https://user-images.githubusercontent.com/41174043/74000172-42ffe500-49bb-11ea-8e73-2389677874b0.png">

**Comment by rutujarane** [comment]
Hi,
Thank you for reaching out.
Could you please answer the following questions, so I can help you resolve the issue:
1. What machine, operating system are you using?
2. What is the java version in your machine?
3. Did you use One Click Install or the Source Code to install Karma?

**Comment by caotrinh** [comment]
Hello,
1. I am using Mac Mojave 10.14.6 
2. I am using java 13.0.2, maven 3.6.3 then I changed to Java 1.8 and maven 3.6.3 still didnt work
3. I tried install from source code and one click as well and I the error when I install form source code was showed above.

**Comment by caotrinh** [comment]
This is my java and maven version
<img width="528" alt="Screen Shot 2020-02-10 at 2 04 47 pm" src="https://user-images.githubusercontent.com/41174043/74118245-b5b4ce80-4c0e-11ea-855f-a0ea89296a28.png">
This is the karma screen when I install one click 
<img width="1042" alt="Screen Shot 2020-02-10 at 2 04 56 pm" src="https://user-images.githubusercontent.com/41174043/74118577-28727980-4c10-11ea-9801-59edd488c0a8.png">

**Comment by marijane** [comment]
I've been trying to help @caotrinh with this problem today.  It seems important that when running the one-click app, the heap size selector is empty (see screenshot above).  Any thoughts from the Karma team on what might cause this problem, or how to debug it?  I am running the same version of Mac OS (10.14.6) and Java (openjdk 1.8.0_242) but I can't reproduce this problem on my machine.

**Comment by rutujarane** [comment]
I tried to replicate the environment @caotrinh mentioned. I could not replicate the issue though. I also tried to run the one-click version and it worked fine with the heap size selector not empty.

**Comment by rutujarane** [comment]
This issue has been fixed. It was related to updating the pom.xml file as effective January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS. You can visit this link for further reference:
https://support.sonatype.com/hc/en-us/articles/360041287334
The source code can be downloaded from the development branch for the latest update.
