### ISSUE TITLE
Dataset Column mappings

### ISSUE THREAD

**Issue by vagarwal77** [usc-isi-i2/Web-Karma#440]
**Describe the bug**
I have 2 large datasets each are having app. 45 tables each with app 20 columns each. 
I would like to map the columns from one dataset tables to another dataset tables either based upon column name matching or column descriptors or any other semantic way. 
Please suggest if Karma or any other Python library can perform this task? 

Any pointer would be of great help. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by rutujarane** [comment]
You can create an ontology mapping for one dataset. Then when you load a new dataset, Karma will recommend labels for the new data depending on column similarity. The column similarity is decided based on column names, data in the columns etc.
