### ISSUE TITLE
 Failed to execute goal on project import-spatial:

### ISSUE THREAD

**Issue by rajendraprasadyk** [usc-isi-i2/Web-Karma#445]
@dkapoor Please resolve the issue 
[INFO] ISI Karma Maven Webapp 0.0.1-SNAPSHOT .............. SUCCESS [  0.401 s]
[INFO] karma-util ......................................... SUCCESS [  2.075 s]
[INFO] karma-typer ........................................ SUCCESS [  0.660 s]
[INFO] karma-common ....................................... SUCCESS [  4.023 s]
[INFO] karma-commands ..................................... SUCCESS [  0.012 s]
[INFO] commands-common .................................... SUCCESS [  0.319 s]
[INFO] commands-update .................................... SUCCESS [  0.346 s]
[INFO] commands-worksheet ................................. SUCCESS [  0.639 s]
[INFO] commands-alignment ................................. SUCCESS [  0.553 s]
[INFO] commands-python .................................... SUCCESS [  0.510 s]
[INFO] commands-alignment-openrdf ......................... SUCCESS [  0.349 s]
[INFO] commands-publish ................................... SUCCESS [  0.272 s]
[INFO] karma-jdbc ......................................... SUCCESS [  0.201 s]
[INFO] commands-publish-jdbc .............................. SUCCESS [  0.053 s]
[INFO] commands-publish-alignment-openrdf ................. SUCCESS [  0.472 s]
[INFO] commands-update-jdbc ............................... SUCCESS [  0.159 s]
[INFO] commands-import .................................... SUCCESS [  0.027 s]
[INFO] import-common ...................................... SUCCESS [  0.146 s]
[INFO] import-csv ......................................... SUCCESS [  0.109 s]
[INFO] import-database .................................... SUCCESS [  0.231 s]
[INFO] import-excel ....................................... SUCCESS [  0.169 s]
[INFO] import-file ........................................ SUCCESS [  0.067 s]
[INFO] import-ontology .................................... SUCCESS [  0.247 s]
[INFO] import-json ........................................ SUCCESS [  0.240 s]
[INFO] import-service ..................................... SUCCESS [  0.207 s]
[INFO] import-spatial ..................................... FAILURE [  0.121 s]
[INFO] import-xml ......................................... SKIPPED
[INFO] import-avro ........................................ SKIPPED
[INFO] commands-include ................................... SKIPPED
[INFO] karma-web .......................................... SKIPPED
[INFO] karma-offline ...................................... SKIPPED
[INFO] commands-bloom ..................................... SKIPPED
[INFO] karma-jsonld ....................................... SKIPPED
[INFO] karma-mr ........................................... SKIPPED
[INFO] karma-web-services ................................. SKIPPED
[INFO] web-services-rdf ................................... SKIPPED
[INFO] web-services-publish-es ............................ SKIPPED
[INFO] karma-spark 0.0.1-SNAPSHOT ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.141 s
[INFO] Finished at: 2020-05-18T16:33:08+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project import-spatial: Could not resolve dependencies for project edu.isi:import-spatial:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.geotools:gt-referencing:jar:9.0-M0, org.geotools:gt-epsg-hsql:jar:9.0-M0, org.geotools:gt-epsg-extension:jar:9.0-M0, org.geotools:gt-shapefile:jar:9.0-M0: Failure to find org.geotools:gt-referencing:jar:9.0-M0 in https://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project import-spatial: Could not resolve dependencies for project edu.isi:import-spatial:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.geotools:gt-referencing:jar:9.0-M0, org.geotools:gt-epsg-hsql:jar:9.0-M0, org.geotools:gt-epsg-extension:jar:9.0-M0, org.geotools:gt-shapefile:jar:9.0-M0: Failure to find org.geotools:gt-referencing:jar:9.0-M0 in https://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

**Comment by rutujarane** [comment]
The issue has been resolved and the master and development branches are updated.
