### ISSUE TITLE
not able to load data from mysql

### ISSUE THREAD

**Issue by TimoFra** [usc-isi-i2/Web-Karma#458]
Hello,
I am currently writing on my bachelor thesis about RDB2RDF tools for that purpose I tried to connect MySQL with Karma but its not working. Is there something wrong with the input information to connect to the database?

Many thanks in advance,
Timo

![Bildschirmfoto 2020-07-08 um 00 01 56](https://user-images.githubusercontent.com/63670708/86848507-6b952380-c0ae-11ea-8a7b-06ae69121dd5.png)
![Bildschirmfoto 2020-07-07 um 23 54 31](https://user-images.githubusercontent.com/63670708/86848511-6df77d80-c0ae-11ea-9513-15c53cab6322.png)

**Comment by mnieuwland** [comment]
You need to get the appropriate .jar file for MySQL. Instructions are at the end of this [page](https://github.com/usc-isi-i2/Web-Karma). Maybe that's what you forgot?
