### ISSUE TITLE
Could not create a blank Node with two rdf:type classes

### ISSUE THREAD

**Issue by esidialy** [usc-isi-i2/Web-Karma#461]
Does Karma support the creation of a blank node with two rdf:type like in this example :          
![karma limitation](https://user-images.githubusercontent.com/33020449/92848450-9eb2a680-f3c0-11ea-98f8-aa4d6959a50e.JPG)
            <vcard:hasTelephone rdf:parseType="Resource">
          <vcard:hasValue rdf:resource="tel:+61755555555"/>
          <rdf:type rdf:resource="http://www.w3.org/2006/vcard/ns#Home"/>
          <rdf:type rdf:resource="http://www.w3.org/2006/vcard/ns#Voice"/>
        </vcard:hasTelephone>

**Comment by szeke** [comment]
You can assign multiple semantic types to column, so you can use the same property `hasTelephone` and two types.
