### ISSUE TITLE
 Error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by saclim** [usc-isi-i2/Web-Karma#470]
Hi, I have an issue when trying to run ./Karma on LInux. Error message which I got was  "error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory". Would you kindly advise how to solve the issue?

**Comment by Bidisha010496** [comment]
Hi we have made a new release for the Karma-App. Could you please check and confirm if you are still facing the same issue ?

**Comment by Bidisha010496** [comment]
There has been a new release of Karma, which should have resolved this build issue.
