### ISSUE TITLE
Ontology import failed

### ISSUE THREAD

**Issue by saclim** [usc-isi-i2/Web-Karma#471]
Hi. I am trying the case study "Mapping USC Faculty Data to VIVO" with Karma-web. The dataset is downloaded from the provided website, and I followed the steps in the youtube video.

When I tried to import the owl file, I got the error "Ontology import failed". I attached pictures showing the step I took to import the owl file.

Is it because the file is corrupted due to some reason?  It would be very helpful if someone could kindly advise me. Thank you in advance.

![Screenshot from 2020-12-30 17-59-13](https://user-images.githubusercontent.com/58430546/103368861-fa688300-4ac8-11eb-986d-48b958ccf4c1.png)
![Screenshot from 2020-12-30 17-59-29](https://user-images.githubusercontent.com/58430546/103368869-ffc5cd80-4ac8-11eb-88fa-cb0cf973bd0d.png)
![Screenshot from 2020-12-30 17-59-38](https://user-images.githubusercontent.com/58430546/103368879-03f1eb00-4ac9-11eb-83e0-640deeb420ba.png)
![Screenshot from 2020-12-30 17-59-45](https://user-images.githubusercontent.com/58430546/103368888-081e0880-4ac9-11eb-8396-0da0e2e6376e.png)

**Comment by federicaspinelli** [comment]
I also have the same problem, I have tried different ontologies in different formats. I always get the message "ontology import failed". Does anyone know if there is a way to solve this?

**Comment by logicalfarhad** [comment]
Try to clone and run the development branch instead of master branch. The problem was coming from fileUtil.java file which has been fixed in development version.

**Comment by xbc0112** [comment]
I have the same question, too. Every time I upload an OWL ontology, it comes to "ontology import failed", and the karma console shows 'file does not exist'. How can I solve this?
![image](https://user-images.githubusercontent.com/44865171/110233491-415a7500-7f5f-11eb-822e-6b3323a9ffbf.png)

**Comment by schlawiner** [comment]
I encountered the same problem and could circumvent it by placing the ontology file into the **"preloaded-ontologies"** folder (in the karma directory). When restarting karma, the file was auto-loaded successfully.

**Comment by KGxie** [comment]
I face the same problem too. But my opreating system is windows. I have successfully handled this problem.
You should find the configuration local folder, find the fold named user-uploaded-files. Then copy the owl file to this folder and refresh the folder,when you  import ontology,you should choose owl file by this path,then you can successfully import it.
I hope  my answer is helpful to you. The picture is as follow,i am not sure whether it can be seen clearly.
![PQ~SUIS9%(CP $FJK`8B2O](https://user-images.githubusercontent.com/82789002/115172700-6282b980-a0f8-11eb-8f99-48711c0a4b94.png)

**Comment by Bidisha010496** [comment]
Hi we have made a new release for the Karma-App. Could you please check and confirm if you are still facing the same issue ?
