### ISSUE TITLE
Unable to connect to SQLServer using instance Browsing

### ISSUE THREAD

**Issue by rkbrasse** [usc-isi-i2/Web-Karma#483]
**Describe the bug**
I need to be able also to set an instance variable for the JTDS driver to connect to my SQLServer DB.

**To Reproduce**
attempt to run karma offline using the following format 
     mvn -U -X -e exec:java -Dexec.mainClass="edu.isi.karma.rdf.OfflineRdfGenerator" -Dexec.args=" \
--sourcetype DB --dbtype SQLServer \
--hostname  XXXXXXXX --username XXXXXXX --password XXXXXX \
--tablename XXXXXXXX  --portnumber 1434 \
--modelfilepath $modelFile \
--outputfile $n3Filename" -Dexec.classpathScope=compile

The error is just a connection failure or a timeout.

**Expected behavior**
We are running SQLServers in browsing mode, so we have to pass an instance parameter from the command line back to the JTDS connection string. (i.e.  **--instance=instance name** to jdbc:jtds:sqlserver://hostname:port;databaseName=dbname;user=username;password=pwd;**instance=instance**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 89.0.4389.114

**Additional context**
Info on JTDS and this connection method
[JTDS Driver Info](http://jtds.sourceforge.net/faq.html)

You could also try the Microsoft drivers that allow adding the instance to the end of the hostname <hostname>\<instance>.
[M$ Driver](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-the-jdbc-driver?view=sql-server-ver15)

**Comment by Bidisha010496** [comment]
Hi we have made a new release for the Karma-App. Could you please check and confirm if you are still facing the same issue ?

**Comment by rkbrasse** [comment]
I will give it a whirl tomorrow.

**Comment by Bidisha010496** [comment]
Kindly re-open the issue if it still exists with the new release of the app.
