### ISSUE TITLE
Karma window not displaying anything, trouble connecting to server

### ISSUE THREAD

**Issue by MjhX** [usc-isi-i2/Web-Karma#484]
After running Karma as administrator, the Tomcat command window opened up (I can't really comprehend it, and I'd rather not post the name within right now), and the localhost:8080 followed.  I got an error message saying "Trouble connecting to server!", and nothing displayed on the page aside from the top and bottom bars.  I also attempted to import a .csv (and confirmed that it was CSV), but there was still nothing displayed.  Other buttons don't seem to work (aside from OpenRDF, leading into a Workbench which doesn't seem to be mentioned in the tutorials).  I might be completely misunderstanding how Karma is supposed to be used, but I don't have much of a frame of reference for this.

OS: Windows 10
Browser: Firefox v87.0

**Comment by Bidisha010496** [comment]
Hi we have made a new release for the Karma-App. Could you please check and confirm if you are still facing the same issue ?
