### ISSUE TITLE
Karma does not startup without any error

### ISSUE THREAD

**Issue by grobmo** [usc-isi-i2/Web-Karma#492]
When I just startup Karma after downloading the files nothing really happens (see Screenshot). 
![karmaStartup2](https://user-images.githubusercontent.com/56788591/120938553-913e0900-c713-11eb-8425-06e1aa3e0804.PNG) The behaviour is the same on chrome and ie. 

 - OS: Windows10
 - IE and Chrome 91

Is there any logfile or additional Information, where I can check cause?

**Comment by Bidisha010496** [comment]
Hi we have made a new release for the Karma-App. Could you please check and confirm if you are still facing the same issue ?
