### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by GULTENKARA** [usc-isi-i2/Web-Karma#495]
When I run mvn clean install in the Web-Karma-2.4 folder.  I get the following error messages and build failures.

![image](https://user-images.githubusercontent.com/76770265/123606127-40e33400-d805-11eb-8bab-6265a84b9e82.png)

 - OS: Windows
 - Browser chrome

**Comment by GULTENKARA** [comment]
C:\Users\KARTOGRAFYA ABD\Web-Karma>mvn --version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T22:49:05+03:00)
Maven home: E:\apache-maven-3.5.3\bin\..
Java version: 11.0.11, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk-11.0.11
Default locale: en_US, platform encoding: Cp1254
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by sean-b-k-w** [comment]
I'm getting the same error - failure at the "commands-worksheet" - when trying the same thing, although I've tried different JAVA versions (1.7. 1.8. and 11), all with similar problems. I've also removed and reinstalled JAVA and Maven and deleted and replaced Karma.

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Applications/apache-maven-3.8.1
Java version: 1.8.0_301, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

**Comment by caknoblock** [comment]
We are looking into this build failure.  In the meantime, try running one of the one-click installers to run Karma on your machine.  We have installers for Linux, Windows, and Mac.

**Comment by sean-b-k-w** [comment]
The Mac application (one-click installer) runs but is non-functional. The only button or menu items that appear to work are the menu items for opening a browser window and quitting the application. The browser window that opens then gives an error with Port 8080. Those problems led me to try to install using the source code.

**Comment by ChowRaj** [comment]
Hi, http://repo.karma.isi.edu/artifactory/libs-release-local is not working, I am getting connection refused error while building from maven.

Can you please help

**Comment by caknoblock** [comment]
The student that was supporting Karma graduated and we are in the process of hiring a new student to take on Karma support and debug the various problems that arise.  The semester starts in mid-August so I’m afraid this will have to wait until we get a new student in place to address this problem.

**Comment by Bidisha010496** [comment]
Hi , this build issue is addressed and fixed in the new release. Can you please check and confirm if you are still facing this issue ?

**Comment by jhercher** [comment]
Hi, the mentioned step above compiles for me, but fails on building karma-web: 
![karma-web](https://user-images.githubusercontent.com/941635/140102852-592ca118-3cbb-40d2-ba73-fae86f3814dd.png)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /usr/local/Cellar/maven/3.8.3/libexec
Java version: 17.0.1, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/17.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "11.6.1", arch: "x86_64", family: "mac"

Hope this helps to solve the issue

**Comment by Bidisha010496** [comment]
Hi @jhercher, we need to use Java 1.8 for running the build. Please let me know if you still face this issue with JDK 1.8

**Comment by jhercher** [comment]
Ah, thanks @Bidisha010496! The build was successful now :)

**Comment by Bidisha010496** [comment]
@jhercher Great to hear that ! Closing this issue.
