### ISSUE TITLE
Ontology import failed!

### ISSUE THREAD

**Issue by GULTENKARA** [usc-isi-i2/Web-Karma#496]
**Describe the bug**
Im installed Karma-Windows and I run Karma.exe file. I imported an ontology import from file. I get following error report.

![image](https://user-images.githubusercontent.com/76770265/123623771-852b0000-d816-11eb-904a-de55c9657664.png)

![image](https://user-images.githubusercontent.com/76770265/123624057-d0451300-d816-11eb-9299-2b9d789ec875.png)

 - OS: Windows
 - Browser chrome

**Comment by RichDijk** [comment]
I do have the same issue

**Comment by Bidisha010496** [comment]
Hi we have made a new release for the Karma-App. Could you please check and confirm if you are still facing the same issue ?
