### ISSUE TITLE
Build fails due to not resolved dependencies because of connection timeout to karam.isi.edu:80

### ISSUE THREAD

**Issue by almasch** [usc-isi-i2/Web-Karma#498]
The build fails with following error message of maven:

[ERROR] Failed to execute goal on project commands-worksheet: Could not resolve dependencies for project edu.isi:commands-worksheet:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at edu.isi.karma.services:entityExtraction:jar:0.0.1: Failed to read artifact descriptor for edu.isi.karma.services:entityExtraction:jar:0.0.1: Could not transfer artifact edu.isi.karma.services:entityExtraction:pom:0.0.1 from/to KarmaRepo (http://repo.karma.isi.edu/artifactory/libs-release-local): Transfer failed for http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/karma/services/entityExtraction/0.0.1/entityExtraction-0.0.1.pom: Connect to repo.karma.isi.edu:80 [repo.karma.isi.edu/52.38.17.139] failed: Operation timed out (Connection timed out) -> [Help 1]

**To Reproduce**
1. git clone https://github.com/usc-isi-i2/Web-Karma
2. cd Web-Karma
3. mvn clean install

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - maven 3.6.3
 - openjdk version "11.0.11" 2021-04-20

**Comment by alexath** [comment]
This seems to be the same issue with #495 .

repo.karma.isi.edu/52.38.17.139 is inaccessible.

**Comment by ChowRaj** [comment]
Hi, http://repo.karma.isi.edu/artifactory/libs-release-local is not working, I am getting connection refused error while building from maven.

Can you please help

**Comment by Bidisha010496** [comment]
Hi, there has been a new release of web-karma and this issue has been handled! Can you check if you can build the code ?

Also please use java 1.8 for build.

**Comment by ChowRaj** [comment]
Hi Bidisha ,

Thank you for the information. I will try and let you know if I further
face any issues regarding Karma.
Have a Good Day.

Regards,
Rajdip Chowdhury

**Comment by olanowak** [comment]
I'm afraid it still doesn't work 
```
curl http://repo.karma.isi.edu/artifactory/libs-release-local/edu/isi/karma-util/0.0.1-SNAPSHOT/maven-metadata.xml
curl: (28) Failed to connect to repo.karma.isi.edu port 80 after 131075 ms: timeout
```
