### ISSUE TITLE
Localhost:8080-Trouble connecting to server

### ISSUE THREAD

**Issue by dilan9461** [usc-isi-i2/Web-Karma#499]
![Ekran Alıntısı](https://user-images.githubusercontent.com/82340714/125679295-dc77efdb-6d71-43ae-ba20-708d0106a8b7.PNG)
Maven 3.0 and Java 1.7 are available but giving localhost error.
![Ekran Alıntısı1](https://user-images.githubusercontent.com/82340714/125680192-d6c9d4dd-15ed-4dfe-ba3b-58907c121aab.PNG)

**Comment by Bidisha010496** [comment]
Hi, there has been a new release of web-karma. Can you check if you still get this error ?

**Comment by dilan9461** [comment]
Hi, it still gives the same error.

**Comment by Bidisha010496** [comment]
Hi, the previous release was for the codebase. We have made a new release for the one-click installer application for Windows, Mac, and Linux. Could you try the same with the new application ?
If you still face the issue, please let me know the following: 
1. Which platform is your application running on? (Mac, Windows, or Linux)
2. Are you getting this issue with the one-click installer application? 
3. Can you list down the steps you are performing from downloading the application to opening it? It will help me to trace back.
