### ISSUE TITLE
Join csv tables

### ISSUE THREAD

**Issue by RichDijk** [usc-isi-i2/Web-Karma#500]
How do I relate two tables with an objectProperty using the web UI? I can not find this in docs or videos.
Thank you.

**Comment by caknoblock** [comment]
You cannot relate tables within the web UI.  Each table is handled independently, but then can be mapped into RDF where you can combine data across tables.  To specify a relationship across two tables, you will need to a common URI across the two tables that provides the mapping.

**Comment by RichDijk** [comment]
Thank you Craig, that's clear.
