### ISSUE TITLE
Wrong Karma App version string

### ISSUE THREAD

**Issue by tjroamer** [usc-isi-i2/Web-Karma#543]
**Describe the bug**
Web app version is showing v2.2 for the version 2.5.2

**To Reproduce**
1. Launch the Karma app
2. App is showing `Karma v2.2` on the top left corner

**Expected behavior**
Expected showing 2.5.2

**Screenshots**
![image](https://user-images.githubusercontent.com/386639/175820896-6b58f53e-08cc-49a9-86fe-7cf6a4750a1f.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version 102

**Comment by Bidisha010496** [comment]
Resolved. Thank you !
