### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by dhenry314** [usc-isi-i2/Web-Karma#93]
Here is the relevant output after attempting a build:

[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building ISI Karma Maven Webapp 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ webkarma ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ webkarma ---
[INFO] Installing /usr/local/Web-Karma/pom.xml to /home/dhenry/.m2/repository/edu/isi/webkarma/0.0.1-SNAPSHOT/webkarma-0.0.1-SNAPSHOT.pom
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building karma-util 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ karma-util ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ karma-util ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /usr/local/Web-Karma/karma-util/src/main/config
[INFO] skip non existing resourceDirectory /usr/local/Web-Karma/karma-util/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ karma-util ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 40 source files to /usr/local/Web-Karma/karma-util/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ISI Karma Maven Webapp ............................ SUCCESS [  0.387 s]
[INFO] karma-util ........................................ FAILURE [  0.673 s]
[INFO] karma-crf ......................................... SKIPPED
[INFO] karma-cleaning .................................... SKIPPED
[INFO] karma-common ...................................... SKIPPED
[INFO] karma-commands .................................... SKIPPED
[INFO] commands-common ................................... SKIPPED
[INFO] karma-jdbc ........................................ SKIPPED
[INFO] karma-not-common .................................. SKIPPED
[INFO] commands-update ................................... SKIPPED
[INFO] commands-alignment ................................ SKIPPED
[INFO] commands-worksheet ................................ SKIPPED
[INFO] commands-python ................................... SKIPPED
[INFO] commands-alignment-openrdf ........................ SKIPPED
[INFO] commands-cleaning ................................. SKIPPED
[INFO] commands-publish .................................. SKIPPED
[INFO] commands-publish-jdbc ............................. SKIPPED
[INFO] commands-publish-alignment-openrdf ................ SKIPPED
[INFO] commands-update-jdbc .............................. SKIPPED
[INFO] commands-import ................................... SKIPPED
[INFO] import-common ..................................... SKIPPED
[INFO] import-csv ........................................ SKIPPED
[INFO] import-database ................................... SKIPPED
[INFO] import-excel ...................................... SKIPPED
[INFO] import-file ....................................... SKIPPED
[INFO] import-ontology ................................... SKIPPED
[INFO] import-json ....................................... SKIPPED
[INFO] import-service .................................... SKIPPED
[INFO] import-spatial .................................... SKIPPED
[INFO] import-xml ........................................ SKIPPED
[INFO] commands-include .................................. SKIPPED
[INFO] karma-web ......................................... SKIPPED
[INFO] karma-offline ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.520 s
[INFO] Finished at: 2014-05-07T15:12:58-06:00
[INFO] Final Memory: 9M/23M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project karma-util: Fatal error compiling: directory not found: /usr/local/Web-Karma/karma-util/target/classes -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :karma-util

**Comment by mahtabmoh** [comment]
That's exactly what I get. Seems like the pom.xml file does not have repository.

**Comment by mahtabmoh** [comment]
And yes I'm running mvn clean install from Web-Karma directory. I highly appreciate if you help me with this issue.

**Comment by kaushalv274** [comment]
Hi,

Please make sure you have correct JAVA version and you are using the latest code. (Follow https://github.com/usc-isi-i2/Web-Karma/wiki/Installation%3A-Source-Code)

You should be able to successfully build Karma with latest master code and JAVA 1.8. 

If you are still facing issues, let me know

Operating System
JAVA version
Maven version 

Thanks

**Comment by mahtabmoh** [comment]
Hi,
Thanks for your response. Actually all the apps are up to date. I just installed Karma on Ubuntu VM, Apache Maven 3.3.9, and JAVA 9.

**Comment by mahtabmoh** [comment]
I still get this:

`[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ISI Karma Maven Webapp ............................. SUCCESS [  5.295 s]
[INFO] karma-util ......................................... SUCCESS [ 18.038 s]
[INFO] karma-typer ........................................ SUCCESS [  4.743 s]
[INFO] karma-common ....................................... SUCCESS [ 43.277 s]
[INFO] karma-commands ..................................... SUCCESS [  0.021 s]
[INFO] commands-common .................................... SUCCESS [  0.696 s]
[INFO] commands-update .................................... SUCCESS [  0.726 s]
[INFO] commands-worksheet ................................. SUCCESS [ 34.599 s]
[INFO] commands-alignment ................................. SUCCESS [  1.256 s]
[INFO] commands-python .................................... SUCCESS [  1.247 s]
[INFO] commands-alignment-openrdf ......................... SUCCESS [ 13.342 s]
[INFO] commands-publish ................................... SUCCESS [  2.081 s]
[INFO] karma-jdbc ......................................... SUCCESS [  1.533 s]
[INFO] commands-publish-jdbc .............................. SUCCESS [  0.087 s]
[INFO] commands-publish-alignment-openrdf ................. SUCCESS [  1.156 s]
[INFO] commands-update-jdbc ............................... SUCCESS [  0.358 s]
[INFO] commands-import .................................... SUCCESS [  0.024 s]
[INFO] import-common ...................................... SUCCESS [  0.422 s]
[INFO] import-csv ......................................... SUCCESS [  0.392 s]
[INFO] import-database .................................... SUCCESS [  0.509 s]
[INFO] import-excel ....................................... SUCCESS [  0.374 s]
[INFO] import-file ........................................ SUCCESS [  0.070 s]
[INFO] import-ontology .................................... SUCCESS [  0.546 s]
[INFO] import-json ........................................ SUCCESS [  0.381 s]
[INFO] import-service ..................................... SUCCESS [  0.353 s]
[INFO] import-spatial ..................................... SUCCESS [ 44.355 s]
[INFO] import-xml ......................................... SUCCESS [  0.324 s]
[INFO] import-avro ........................................ SUCCESS [  0.544 s]
[INFO] commands-include ................................... SUCCESS [  0.015 s]
[INFO] karma-web .......................................... SUCCESS [ 15.640 s]
[INFO] karma-offline ...................................... SUCCESS [  9.207 s]
[INFO] commands-bloom ..................................... FAILURE [ 23.429 s]
[INFO] karma-jsonld ....................................... SKIPPED
[INFO] karma-mr ........................................... SKIPPED
[INFO] karma-storm ........................................ SKIPPED
[INFO] karma-web-services ................................. SKIPPED
[INFO] web-services-rdf ................................... SKIPPED
[INFO] web-services-publish-es ............................ SKIPPED
[INFO] karma-spark ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:46 min
[INFO] Finished at: 2018-01-24T14:09:28+01:00
[INFO] Final Memory: 61M/308M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project commands-bloom: Could not resolve dependencies for project edu.isi:commands-bloom:jar:0.0.1-SNAPSHOT: Could not find artifact jdk.tools:jdk.tools:jar:1.6 at specified path /usr/lib/jvm/java-9-oracle/../lib/tools.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :commands-bloom
`

**Comment by kaushalv274** [comment]
Hi, 

We have figured out the issue. The issue is due to JAVA 9. We will shortly update our code and make it compatible with JAVA 9.

For now you can compile with JAVA 7/8. 

Thanks
Kaushal

**Comment by mahtabmoh** [comment]
Thank you very much.

Mahtab
